### ISSUE TITLE
[Feature] Making the genres, franchise, company, etc. labels act as search buttons.

### ISSUE THREAD

**Issue by Spinnich** [rommapp/romm#1019]
I thought this would be a nice feature request. For example, if I were to click on the "Role-playing (RPG)" label it would automatically show me all "Role-playing (RPG)" games available on my RomM instance. Ideally, this would show results from all platforms with the ability to manually filter after the fact.

![image](https://github.com/user-attachments/assets/1448416e-70f8-49e4-9cc2-cf9814a674ef)

**Comment by gantoine** [comment]
This is now available in the latest release.
