### ISSUE TITLE
[Feature] Set Default Core and BIOS

### ISSUE THREAD

**Issue by WirtsLegs** [rommapp/romm#1029]
With arcade especially it can be annoying to have to scroll through all the core and bios options to select the appropriate ones every time, and my wife when she plays it just confuses her

Ideally Id suggest an option to set a platform default for bios and core (if both are available for a given platform) and then all games in that platform have those settings selected by default. Then additionally being able to do per-game overrides that persist for all users (for admin) and just for yourself would be a nice add

**Comment by gantoine** [comment]
This will be available in the next release!
