### ISSUE TITLE
[Bug] Pressing the Browser 'back' button doesn't take you back to 'platform'

### ISSUE THREAD

**Issue by Ronald-Diemicke** [rommapp/romm#1031]
**RomM version**
3.3.0

**Describe the bug**
When you go to a 'platform', then pick a 'game' then hit your browser back button, you get a blank screen.

**To Reproduce**

1. Pick a platform (ex. 'SNES')
2. Click on any game (ex. 'Super Mario World')
3. Now, press your browser's back button
4. You should see a blank screen

**Expected behavior**
I'd expect to go back to the platform that I just came from.

**Screenshots**
Step 1:
<img width="1840" alt="Screenshot 2024-07-26 at 9 42 59 PM" src="https://github.com/user-attachments/assets/961f5f43-92ce-4874-806e-e750c98f8136">
<img width="1840" alt="Screenshot 2024-07-26 at 9 43 12 PM" src="https://github.com/user-attachments/assets/3c03bc86-bd50-40b6-bc75-5788a7021e23">
Step 2:
<img width="1840" alt="Screenshot 2024-07-26 at 9 43 15 PM" src="https://github.com/user-attachments/assets/424a2d01-ca14-4431-a133-8008b05b6c68">
Step 3:
<img width="1840" alt="Screenshot 2024-07-26 at 9 43 17 PM" src="https://github.com/user-attachments/assets/49dbd8e1-8f63-46a0-b298-6c621b892695">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

- Device: MacBook Pro M1 MAX
- OS: Sonoma 14.5
- Browser: Chrome
- Version: 126.0.6478.127

**Comment by gen-angry** [comment]
Sadly this issue still occurs for me in 3.4.0 in some cases.

It works correctly if I click a ROM in the main page from the 'recently added' list. Pressing back will take me back to the main page again. However, if I go to any platform from there, then to a ROM, I get this issue.

It will for a split second go to the platform URL, but then back forward to the ROM URL again and display a blank screen. It doesn't matter which URL I go to when I hold down the browser back button, it will always bring me back forward to the ROM URL with a blank screen. I have to actually click the logo on the top left to get it out.

Desktop: Win11, Firefox 129.

**Comment by zurdi15** [comment]
I made more improvements for this issue lately that will be shipped in the 3.5.0
If it happens again once we release it reopen the issue so we can check it deeper
