### ISSUE TITLE
[UI/UX] Platform sub-versions are not able to have their own icons

### ISSUE THREAD

**Issue by Casuallynoted** [rommapp/romm#1056]
At the moment, I have two platforms that operate as versions of existing platforms, the eReader (operating as a version of gba) and the Pocket Challenge V2 (as a version of the Wonderswan Color). They have dedicated icons in Romm, but Romm has opted to use the mainline platform icon instead. I thought I'd make an issue about this, because it definitely helps to be able to have specific icons for these alternate versions.

**Comment by gantoine** [comment]
This will be fixed in the next release!
