### ISSUE TITLE
[Bug] create user at first login

### ISSUE THREAD

**Issue by lokomass** [rommapp/romm#1066]
**RomM version**
3.4.0

**Describe the bug**
I have setup a login and password in my composé file and in the first login I see this screen :

![image](https://github.com/user-attachments/assets/fda584a3-e76a-402f-959f-89d72d0bb7fc)

I have already defined a user and password in my docker file, so I could login with my account without create new user ?

**To Reproduce**

set ROMM_AUTH_USERNAME
and ROM_AUTH_PASSWORD and go to romm url

**Comment by zurdi15** [comment]
Those variables are not used anymore. You need to create the first admin user with the wizard.

**Comment by gantoine** [comment]
@lokomass @StudioEtrange we're trying to reduce the use of 1-time env variables, for 2 reasons:

a) we've had many users start romm without properly setting user/pass info for admin users (no password, typo in password, whitespace, etc), then open issues when they can't login.
b) the expectation when updating env variables if that they'll have an effect on the running container. the fact that changing the admin env variable does not update the admin password is confusing to some users.

setting up the admin user is a quick 1-time action, and we feel its better served by an in-app flow. i've also gone ahead and removed any references to ROMM_AUTH_USERNAME and ROMM_AUTH_PASSWORD from the wiki.

**Comment by Skeeve** [comment]
How Do I start the wizard?

When I access the webpage I'm redirected to `…/login?next=setup`

**Comment by Skeeve** [comment]
Weird: After the fifth (or so) try to access `…/setup` I'm able to create the admin user.

**Comment by devloic** [comment]
yeah probably a cookie problem, I had to open a private window to be able to create the admin

**Comment by lokomass** [comment]
I’m coming back here because I’m using RomM again. I’m really struggling to get something stable. I use an automated script to install everything, and the fact that it’s not possible to create a user using variables is extremely limiting… I honestly find that really unfortunate. When reading the comments, I see many other people in the same situation. Why not simply allow the use of variables to create a user? Everyone would be free to use them or not!??

**Comment by gantoine** [comment]
> Why not simply allow the use of variables to create a user?

We could, but then would we document them? If we did some people would try to use it and fail (for the reasons listed above), and if we didn't, people would open new issues asking for it, instead of finding this one.

**Comment by StudioEtrange** [comment]
> > Why not simply allow the use of variables to create a user?
> 
> We could, but then would we document them? If we did some people would try to use it and fail (for the reasons listed above), and if we didn't, people would open new issues asking for it, instead of finding this one.

I do not understand this answser.  If it is not by using these specific variables, how to automate romm installation ?
For now an human action is mandatory ! Even if it is a quick human action., we need automation capability :)


In fact, what is the official way to fully automate romm installation ?

**Comment by gantoine** [comment]
> In fact, what is the official way to fully automate romm installation

It's not possible to fully setup romm in an automatic way at the moment, without injecting a user into the database as part of the automation process (this is possible with something like ansible).

**Comment by lokomass** [comment]
Honestly, I find it really unfortunate to remove such an important automation feature because of a small minority of people who don’t read the documentation properly.
Without reading the documentation, you can’t get the container working anyway…

It would be enough to say that if the user/password variables are provided, then an account is created, otherwise no account is created.

Currently, I run a request at the end of the installation to manually add my user, which is really not clean: I hash my password to build the request and inject it directly into the Docker database.

Personally, I think it’s really a shame that such a beautiful project removes such an important feature just out of « fear that some people won’t manage to use it ».

**Comment by Skeeve** [comment]
> It's not possible to fully setup romm in an automatic way at the moment, without injecting a user into the database as part of the automation process (this is possible with something like ansible).

That should be possible given the fact that there is a Dockerfile.

**Comment by zurdi15** [comment]
> > It's not possible to fully setup romm in an automatic way at the moment, without injecting a user into the database as part of the automation process (this is possible with something like ansible).
> 
> That should be possible given the fact that there is a Dockerfile.

What arcane is saying there is that currently we don't support it, not that is technically impossible
