### ISSUE TITLE
[Bug] User profile picture keeps deleting itself

### ISSUE THREAD

**Issue by Casuallynoted** [rommapp/romm#1067]
After a bit of time, an uploaded user profile picture will suddenly no longer appear in the UI. I'm wondering if this is something that is happening every time the docker container changes, somehow.

**Comment by zurdi15** [comment]
Does this happen with all the users in your instance? :(

**Comment by Casuallynoted** [comment]
You know, I'm the only person on my instance with a pic set o.o I'll change that and report back!

**Comment by gantoine** [comment]
I've set a custom image and i'll keep an eye on it, see if/when it disappears...

**Comment by gantoine** [comment]
Ok its been like 100+ stop/rm/up and I've yet to see my profile picture disappear. Going to close this one until I see it happen on my end.
