### ISSUE TITLE
[Feature] Append Switch Title-ID to Tinfoil feed

### ISSUE THREAD

**Issue by Pfuenzle** [rommapp/romm#1074]
Tinfoil needs to have the Title-ID in the ROM filename to successfully parse the ROM. Otherwise it doesn't show up in its menus.
So with the current implementation, the file itself needs to have the Title-ID in it's name, which is often not the case.

By doing a reverse lookup on the title-db RomM can get the title-id to add it to the filename.

It is possible to override the filename shown to be parsed using a shebang.

I tested the implementation like this:
```
TinfoilFeedFileSchema(
                url=str(
                    request.url_for(
                        "get_rom_content", id=file.id, file_name=file.file_name
                    )
                ) + "#Romname123 [01002CD00AXXXXXXX].nsp",
                size=file.file_size_bytes,
            )
```

with a file that has no Title-ID in it's filename and tinfoil successfully parsed the ROM name.

**Comment by gantoine** [comment]
> By doing a reverse lookup on the title-db RomM can get the title-id to add it to the filename.

How would you do a reverse lookup? IGDB title names sometimes don't match the ones in titledb, and titledb doesn't store the CRC/SHA1 hashes for games (only file sizes).

**Comment by gantoine** [comment]
We've decided to require that users who want to use tinfoil fully should manually add the titleID to the filename. This way we can match it with the titleDB list we have internally and populate the `titledb` field in the JSON response for tinfoil.
