### ISSUE TITLE
[Bug] 3.4.0 is Significantly slower at loading large libraries than 3.3.0

### ISSUE THREAD

**Issue by MightyRufo** [rommapp/romm#1075]
**RomM version**
v3.4.0

**Describe the bug**
Loading platforms with large amounts of games takes significantly longer than it did on 3.3.0 (PC game collection is 1700+)

**To Reproduce**
Click on a platform with a large amount of games

**Expected behavior**
Platform should load just as fast as before (on 3.3.0)

**Desktop (please complete the following information):**

- OS: Windows 11 (Server running Unraid, 7950x, m.2)
- Browser Opera
- Version of what? The OS or the browser?

**Additional context**
Nothing else has changed except the update of 3.4.0. It was a night and day difference as I was  browsing my pc library and noticed the notification on the bottom left. Updated, and continued on. That's when I noticed it was much, much slower. I restarted MariaDB and also optimized the database.

I have since rolled back RomM to 3.3.0 and the issue no longer remains.

**Comment by gantoine** [comment]
Yep I see it as well, I fix it and we can release a patch to bring the speeds back up!

**Comment by MightyRufo** [comment]
> Yep I see it as well, I fix it and we can release a patch to bring the speeds back up!

Thank you! RomM is amazing and you guys are doing an amazing job on this. I've wanted something like this for ages.

**Comment by Dalethium** [comment]
https://github.com/rommapp/romm/commit/9fb77f9a83634dfe094f24ec15ba35d9bd7b0dc7
I just built and tested this, and I can confirm that it went from my library timing out to it actually loading. It also definitely loaded the libraries faster than it did previously in the smaller ones.

Thank you so much!

**Comment by gantoine** [comment]
That's great to hear! We'll have a beta release up for testing in a couple days, and in the meantime I'll continue to test the performance of this change.

BTW given how sensitive the DB can be at time its always possible this regression will be reintroduced in the future (due to any number of bugs). If it ever happens please let us know so we can address it.
