### ISSUE TITLE
[Bug] slow download due to max CPU usage?

### ISSUE THREAD

**Issue by gen-angry** [rommapp/romm#1079]
**RomM version**
3.4.0

This issue still happened with 3.3.0.

**Describe the bug**
The download speed caps out at 15-25MB/s regardless of whether I download a large single file ISO or multi-parts that are zipped on the fly.

**To Reproduce**

1. Go to a large ROM, either an ISO or a multi part folder
2. Click on download.
3. Look at speed. 

**Expected behavior**
ROMs download at 80-90MB/sec capped to the speed of my network card on my desktop machine.

**Desktop (please complete the following information):**

- OS: win11
- Browser firefox
- Version 129

**Additional context**

I have this installed with latest docker on ubuntu 24.04 LXC container on a Proxmox host. I use this LXC to run several containers and be able to mount to a folder to my hard drive storage array.

The LXC has been assigned 8 cores (of a E5-2680v4) and 48GB RAM. Other containers in the LXC run idle 99% of the time but have no problem requesting all of the resources when they need it for temporary short spikes. However, the problem persists even if I shut down all other containers on this LXC leaving RomM as the sole running application.

I noticed that while Im downloading, one CPU core will peg to max leaving the others relatively idle. I wonder if RomM is set to only use one core/thread? Is there a way to see/set how many cores this application can use? I went through all of the wiki documentation and couldn't find anything about it.

Thank you :)

**Comment by adamantike** [comment]
Download speed and CPU usage will be fixed for single-file downloads in the next release.
For multi-file downloads, that are zipped on the fly, we are still exploring ways to reduce CPU usage.
