### ISSUE TITLE
[Bug] Can't upload 3DS games

### ISSUE THREAD

**Issue by Mephisto090** [rommapp/romm#1085]
**RomM version**
docker image rommapp/romm:latest

**Describe the bug**
German: Ich kann keine 3ds spiele hochladen. Siehe Screenshot
English: I can't upload 3ds games. See screenshot

**To Reproduce**
Just upload Pokemon as in my example via the website

**Screenshots**
![image](https://github.com/user-attachments/assets/f112e4fb-19b4-4feb-b615-c5069be6927b)
![image](https://github.com/user-attachments/assets/71720ed0-c7a7-44c2-8489-1e65bf547a8f)
Filesize: 891 MB

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version: 127.0.6533.100 (Offizieller Build) (64-Bit)

**Additional context**

**Comment by zurdi15** [comment]
Does this happen only in 3ds platform? Are you being able to upload 3ds or newer generation games?

**Comment by Mephisto090** [comment]
No Problem with Xbox 360. See Screenshot

![image](https://github.com/user-attachments/assets/0f9d49d1-b211-4d38-aa88-c2780c754e3c)

**Comment by Mephisto090** [comment]
i try it from antoher device (3ds)

**Comment by Mephisto090** [comment]
I think it's the file size, almost 1GB. The timeout of exactly 1 minute seems to be too short.

**Comment by gantoine** [comment]
Oh it's the 1GB/1 minute issue again...

**Comment by Mephisto090** [comment]
It's 891MB to be exact :D

**Comment by Mephisto090** [comment]
![image](https://github.com/user-attachments/assets/a9ac1a14-c10d-4d10-a008-d148432f980a)

That was 559,659MB

**Comment by Mephisto090** [comment]
![image](https://github.com/user-attachments/assets/61e6b068-d8d7-462d-8b6b-fc416d679934)

What can I say? I can see all the games now, but I can't play any of them.

**Comment by gantoine** [comment]
Oh you can't play 3DS games in romm, it's just a media manager for most platforms. https://github.com/rommapp/romm/wiki/EmulatorJS-Player

**Comment by Mephisto090** [comment]
It would be a pity if it were not possible to add the Citra Core. For RetorArch it would theoretically be possible according to google

https://www.reddit.com/r/RetroArch/comments/177g38z/cant_find_a_3ds_core_on_the_download_cores_list/
https://buildbot.libretro.com/stable/1.16.0/linux/x86_64/

**Comment by gantoine** [comment]
We've just merged in an improvement to uploads which should allow uploading large files without timeouts/OOM issues. Will be available in the next release.
