### ISSUE TITLE
[UI/UX] Home top-left romm icon not rendering correctly

### ISSUE THREAD

**Issue by TyroneSlothrop** [rommapp/romm#1087]
On mobile/iphone with chrome, v3.4.0 the 'home' top-left romm icon not rendering correctly, it seems be truncated or badly-proportioned. Looks fine on a PC though (the main romm logo), same container running. Can this be looked at and fixed please?

![image](https://github.com/user-attachments/assets/9730c40f-7267-4ff5-a37e-7ee7b4757ac5)

**Comment by gantoine** [comment]
Will be fixed in the next release
