### ISSUE TITLE
[Bug] RomM not changing color of status bar on iOS

### ISSUE THREAD

**Issue by MightyRufo** [rommapp/romm#1089]
**RomM version**
3.3.0 (the issue still appears in 3.4.0)

**Describe the bug**
Changing the UI from light to dark doesn't seem to change the white color in the status bar area.

**To Reproduce**
Turn on dark mode

**Expected behavior**
The background color of the status bar should match that of the theme, that way the UI appears seamless.

**Screenshots**
![image](https://github.com/user-attachments/assets/3fcda6c2-2a45-45dd-97ed-0447ae568046)

**Smartphone (please complete the following information):**

- OS: iOS 17.6.1 (14 Pro Max)
- Browser Safari

**Comment by gantoine** [comment]
I can't reproduce this on an iPhone 15 or in emulator, it's already the case on iOS (our UI library handles it for us).
