### ISSUE TITLE
[Feature] Header for Platform indication

### ISSUE THREAD

**Issue by Deekerman** [rommapp/romm#1091]
**Is your feature request related to a problem? Please describe.**
I have a few platforms and some share games so i can get confused which platform i am on

**Describe the solution you'd like**
an indication on the platform page of what the platform is

**Describe alternatives you've considered**
giving up on life

**Additional context**
I donno, could put it next to the filter or below it?

**Comment by gantoine** [comment]
Will be added in the next release
