### ISSUE TITLE
[Feature] Docker Healthcheck / Health API endpoint

### ISSUE THREAD

**Issue by saschabrockel** [rommapp/romm#1098]
**Is your feature request related to a problem? Please describe.**
I would like to know if the container is in a healthy state or if it is not responding anymore for example and can also automatically react to unhealthy states.

**Describe the solution you'd like**
It would be nice if either the Dockerfile would already include a Docker healthcheck like

```
HEALTHCHECK --interval=30s --timeout=10s --retries=3 \
  CMD curl -f http://localhost:8080/health || exit 1
```

It does not need to be curl. I can also be wget which is available already.

```
HEALTHCHECK --interval=30s --timeout=10s --retries=3 \
  CMD wget -nv -t1 --spider http://localhost:8080 || exit 1
```

**Describe alternatives you've considered**
Otherwise, at least create an API endpoint like /health which just returns status code 200 and we know the container is in a working state.

Currently, you can create a Docker healthcheck on http://localhost:8080 which is overload with `wget`.

**Comment by gantoine** [comment]
You can use `/api/heartbeat` to see if the app is up and running correctly, it'll return a 200 status code and a bunch of config properties in JSON format.

**Comment by saschabrockel** [comment]
Thank you @gantoine worth to note it somewhere in the docs :)

**Comment by zodac** [comment]
> You can use /api/heartbeat to see if the app is up and running correctly, it'll return a 200 status code and a bunch of config properties in JSON format.

Hi @gantoine, would there be any objection if I raised a PR to add this to the Dockerfile itself?

**Comment by gantoine** [comment]
@zodac The next release is going to include changes to the dockerfile, if there's anything missing once 3.6.0 is out we welcome a PR!

**Comment by zodac** [comment]
Cool, I'll keep an eye on the next release and then raise one if needed. 👍
