### ISSUE TITLE
[Feature] Ability to hide items

### ISSUE THREAD

**Issue by kacoo1** [rommapp/romm#1104]
**Is your feature request related to a problem? Please describe.**
Using NAS to store ROMs and ROMM picks up the hidden files. Would be great to have a way to either ignore hidden files or have the ability to hide items in the UI.

**Describe the solution you'd like**
The ability to hide items from showing in the UI.

**Comment by kacoo1** [comment]
> You can do it excluding the files from the scan in the config file. Here you have [an example](https://github.com/rommapp/romm/blob/release/examples/config.example.yml)

Awesome. Didn't see this. Thanks for pointing me in the right direction.

**Comment by DarkCTO** [comment]
Wait how did you do this?

**Comment by zurdi15** [comment]
> Wait how did you do this?

https://docs.romm.app/3.10.3/Getting-Started/Configuration-File/

**Comment by DarkCTO** [comment]
I get zero matches, even without any exclude except for platform.
In psx folder, I have either .chd file (single) or m3u (multi-part), which refers to hidden folders on the same level that stores the part CHDs. So confused.

<img width="2491" height="725" alt="Image" src="https://github.com/user-attachments/assets/37f8f762-eb1c-4441-9a9b-aa87cf78a57d" />



```
roms
------psx
----------single.chd
----------multi.m3u
----------.multi
----------------multi_part1.chd
----------------multi_part1.chd
```

**Comment by DarkCTO** [comment]
Rebuilt docker, seems to work now I'll try again...
So to hide all hidden folders I put .*/ ?

**Comment by DarkCTO** [comment]
Done. For future reference.

<img width="2479" height="113" alt="Image" src="https://github.com/user-attachments/assets/fb6d5340-63fb-4302-be74-8cf1ed7fb207" />
