### ISSUE TITLE
[Bug] "Decompress Game Core"

### ISSUE THREAD

**Issue by TheEscPilot** [rommapp/romm#1106]
**RomM version**
3.4.0 
Installed via Docker (Eurotimmy) from the UnRaid App store

**Describe the bug**
When attempting to play any rom through my browser, the screen will launch showing EmulatorJS, and show "Decompress Game Core 99%" and then freeze. This issue is occurring with every platform, across multiple computers and browsers (Firefox + Edge). Tried both in private sessions and normal browser sessions

**To Reproduce**

1. Go to '...' any rom with an associated emulator
2. Click on '....' the play button 
3. wait for Decompress Game Core to hit 99% and continue to wait longer

**Expected behavior**
Last time I loaded an instance of Romm, the games would start playing almost immediately. Is there a way I can redeploy the Game Cores without needing to completely re-initialize my DB?

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows (W), 
- Browser Firefox (W), Edge (W), Firefox (A), Chrome (A)
- Version Latest

**Smartphone (please complete the following information):**

- Device: Samsung A59
- OS: Android 14
- Browser Firefox (A), Chrome (A)
- Version Latest

**Additional context**
This was working previously, then I recreated my DB, and now the games wont launch as expected.

**Comment by TheEscPilot** [comment]
https://www.reddit.com/r/selfhosted/comments/1be0s5j/comment/lj3uxuj/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

Thanks for the update! 
Next time I'll check the discord before posting

**Comment by SaraVieira** [comment]
Is the fixed version v3.5.0-alpha.1?

**Comment by gantoine** [comment]
@SaraVieira Technically yes, but it's an alpha and therefore unstable. We can't provide support/help you fix your install if something goes horribly wrong and you're not in your Alpha Testers program.

**Comment by gantoine** [comment]
This is fixed in the latest release, please clear your cookies and cache after upgrading.

**Comment by akeh-gh** [comment]
Has this issue resurfaced at all?  I'm experiencing it on the latest tag of romm.  Just created an instance of romm for the first time.  Docker via Synology and accessing from my Android 14 (Graphene OS) Pixel 8.

**Comment by FabriciusFab** [comment]
> Has this issue resurfaced at all? I'm experiencing it on the latest tag of romm. Just created an instance of romm for the first time. Docker via Synology and accessing from my Android 14 (Graphene OS) Pixel 8.

I'm experiencing it using the docker latest tag installed on alpine, accessing from a Firefox web browser
