### ISSUE TITLE
[Feature] Enable / Disable EmulatorJS Functionality

### ISSUE THREAD

**Issue by Spinnich** [rommapp/romm#1107]
As the title states, a way to enable / disable EmulatorJS (or similar subsystems if existing/added) would be a welcome addition for admins. to have more granular control over their RomM platform. Ideally, this could just be some sort of toggle within the "Administration" page but a docker environmental variable would likely be sufficient if it works post-deployment.

To add to this while I'm thinking about it, if EmulatorJS supports it, granular control over each of it's functions would be even better! Think; enable / disabling specific emulator platforms, saves, save states, etc in addition to a single on/off switch.

**Comment by Spinnich** [comment]
Emulating in a web browser is a cool feature but not something I want users utilizing on my RomM deployment. This is just an opinion but I feel like it's a half baked experience and would rather "hide" it if possible.

I hadn't considered it until now, but maybe having this controlled at the user permission level would be better / make more sense?

**Comment by gantoine** [comment]
> This is just an opinion but I feel like it's a half baked experience and would rather "hide" it if possible.

Oh it's absolutely not a great experience, but it does work in most cases. Either way this is low priority, but I'll toss it in the backlog anyways.

**Comment by Spinnich** [comment]
Works for me, thank you!

**Comment by gantoine** [comment]
This will be included in the next release!
