### ISSUE TITLE
[Feature] File Path Added to ROM Info

### ISSUE THREAD

**Issue by Scoto1431** [rommapp/romm#1113]
**Is your feature request related to a problem? Please describe.**
Just a thought I have had while trying to sort out the metadata for my ROM files within RomM.

**Describe the solution you'd like**
Is it possible to maybe have the file path listed when you select a ROM or if its easier edit the ROM file? 

I see there is a field called File Name when you go to edit and Files when you click on the ROM just thought a file path field or string output somewhere may help for quicker identification of a ROM.

**Describe alternatives you've considered**
Perhaps it could go instead when you hover over the ROMs cover card? 

**Additional context**
Nothing at this time. 

Repost mostly from Discord per arcaneasada recommendation.

**Comment by gantoine** [comment]
This will be available in the next release!
