### ISSUE TITLE
[Feature] Multi-select and options in search results window.

### ISSUE THREAD

**Issue by InsertDisc** [rommapp/romm#1141]
Being able to select multiple roms from within the search window would make some management tasks much easier, like quick collection creation and bulk deletion. I don't know how hard this would be to implement, but it would be nice to be able to select multiple files and perform tasks after searching a keyword just like you can do in the platform view.

**Comment by zurdi15** [comment]
Implemented in #1393. Will be available in the next release 3.7.0
