### ISSUE TITLE
[Bug] Collections are missing after upgrading to ver 3.5.0

### ISSUE THREAD

**Issue by Budlyte** [rommapp/romm#1145]
**RomM version**
3.5.0

**Describe the bug**
Collections created in previous version now display a 404 error.

**Screenshots**
![image](https://github.com/user-attachments/assets/e984c97a-9e91-4329-b99f-8f7c325b5efb)

**Desktop (please complete the following information):**

- OS: Docker
- Browser: Chrome

**Comment by gantoine** [comment]
Oh not good! Your data is most likely safe, can you post your console logs? Then run a QUICK scan while I check the logs?

**Comment by Budlyte** [comment]
My console doesn't actually display any logs.   :/

![image](https://github.com/user-attachments/assets/972eeb2f-6d93-40d0-8762-cc40e0018ab9)

I'll have to check back tomorrow if the quick scan solves it. Need to get to bed.

**Comment by gantoine** [comment]
Sounds good, when you get the chance tomorrow, in your regular shell run `docker compose logs romm`.

**Comment by Djiit** [comment]
Hey, I've got the same error here on any platform. Main page is OK.
No specific brower console log, but this server log:

```
pydantic_core._pydantic_core.ValidationError: 1 validation error for SimpleRomSchema
files.0
  Input should be a valid dictionary [type=dict_type, input_value='wolfconfig.cfg', input_type=str]
```

Can reproduce on WiiU, a platform with multiparts (folder based) roms.

Hope it can help

**Comment by gantoine** [comment]
Running a quick scan should fix the problem, can you try that and let me know?

**Comment by Djiit** [comment]
Oh, yes!
