### ISSUE TITLE
[Bug] Multi Select in List View Does Not Bring up Menu (To delete, add to collection, etc)

### ISSUE THREAD

**Issue by danblu3** [rommapp/romm#1150]
**RomM version**
3.5.0

**Describe the bug**
I am not sure if this even worked in previous versions to be honest but a user within the discord bought it to our attention so thought I would log it on their behalf. 

The bug is when you select multiple titles within a platform display you get a little incrementing floating button in the bottom right hand corner, when you click that you get multiple options such as add to collection, delete etc.

Interestingly when you swap to list view and select multiple you get no prompt to delete all, add all to collection etc etc and even worse is when you go back to poster view you break the multi select and it does not work until you do a hard refresh. 

**To Reproduce**

1. Go to a platform
2. Change the view to list view
3. Select the checkbox on the left hand side and notice you get no options, and if you press the : next to the rom, you only affect that rom.
4. Change back to post, and notice the multi select does not work at all until you refresh.

**Expected behavior**
The checkbox adds the rom to a context menu where you can add to a collection, donwload all. Etc. 

**Screenshots**
![image](https://github.com/user-attachments/assets/88650c53-b7ed-4a2b-8536-31a312d387b4) No multi select context
![image](https://github.com/user-attachments/assets/9106f4fd-53b3-469c-a7d9-a353964994d9) Context

Raised on behalf of @Deinax 
https://discord.com/channels/1138838206532554853/1279728766272278652

**Comment by adamantike** [comment]
@danblu3, can you test if this is fixed in the latest 3.6.0 version?

**Comment by zurdi15** [comment]
I don't know when, but this was fixed somehow. Tested in #1382
