### ISSUE TITLE
[Feature] HQ Android Icon

### ISSUE THREAD

**Issue by Nomelas** [rommapp/romm#1153]
Installing romm as a chrome app on Android uses the favicon rather than a dedicated icon of higher resolution/quality. While it works, the icon looks a bit ugly and low quality.

**Comment by Nomelas** [comment]
![Screenshot_2024-09-01-14-33-58-21_b9946066a3dd2403bf3d1212ec29ddee](https://github.com/user-attachments/assets/f596db85-52c9-4ba6-9dc7-10acbaf574da)

**Comment by InsertDisc** [comment]
How did you get the dark background? Mine is white.

**Comment by gantoine** [comment]
it'll all fix itself depending on your system!

**Comment by Nomelas** [comment]
> it'll all fix itself depending on your system!

In the next release?

**Comment by Nomelas** [comment]
> How did you get the dark background? Mine is white.

It's transparent (my phone background is dark). Depends on your system, and I'm on Android 14. Are you on iOS?

**Comment by gantoine** [comment]
sorry yes should have specified, it's fixed on `master` and will be in `3.5.1`

**Comment by Nomelas** [comment]
![Screenshot_2024-09-05-00-15-30-10_b9946066a3dd2403bf3d1212ec29ddee](https://github.com/user-attachments/assets/397dfbf8-a7e1-4e46-98d9-209e636bdf97)
Perfect
