### ISSUE TITLE
[Bug] Checking 'default rom' doesn't work anymore

### ISSUE THREAD

**Issue by gen-angry** [rommapp/romm#1154]
**RomM version**
3.5.0

**Describe the bug**
When checking on 'default rom' with multiple versions, it generates a javascript console error. Going back out and in the rom shows that the default state did not save either.

It worked fine in 3.4.0

**To Reproduce**

1. Go to a rom with two different versions
2. Click on default checkmark

**Expected behavior**
Default checkmark stays on and it marks a particular rom version as the default version.

**Screenshots**
Error generated by console when checking a default option
![Screenshot 2024-09-01 210420](https://github.com/user-attachments/assets/1f7c41cd-408a-4988-9815-feb8c68d8a68)

**Desktop (please complete the following information):**

- OS: Win11
- Browser Firefox
- Version 129

**Additional context**
I had cleared all RomM data and re-imported my entire library due to a ton of changes. So the database data itself should be 'updated' fully.

**Comment by gantoine** [comment]
This should be fixed in the upcoming path release.
