### ISSUE TITLE
[Bug] BCJ2 filter is not supported by py7zr

### ISSUE THREAD

**Issue by gen-angry** [rommapp/romm#1155]
**RomM version**
3.5.0

**Describe the bug**
One of my 'roms' causes an error which aborts importing, it is a 7zip file.

```
romm  | ERROR:    [RomM][2024-09-02 01:31:22] (b'\x03\x03\x01\x1b', 'BCJ2 filter is not supported by py7zr. Please consider to contribute to XZ/liblzma project and help Python core team implementing it. Or please use another tool to extract it.')
romm  | 01:31:22 high: Job OK (e8020b3a-4829-4cc2-a95a-96e3bda8cf78)
romm  | 01:31:22 Result is kept for 500 seconds
```

**To Reproduce**

1. Upload a new 7zip rom file or click scan with a new one in rom folder
2. Scan will end prematurely with this error, stopping imports if there are more to do afterwards

**Expected behavior**
The scan to complete, or at least carry on if it can't extract the file.

**Desktop (please complete the following information):**

- OS: Win11
- Browser Firefox
- Version 129

**Additional context**
I can't really upload the file causing it as it's not exactly legal within github's TOS to do so.

**Comment by gantoine** [comment]
This should be fixed in the upcoming path release.
