### ISSUE TITLE
[Bug] Task exceeded maximum timeout value (14400 seconds)

### ISSUE THREAD

**Issue by Setsaria** [rommapp/romm#1168]
**RomM version**
Latest Version 3.5

**Describe the bug**
When I Launch a scan when it scan a big file ( 72Gb or more) the task  get timeout

INFO:	  [RomM][2024-09-04 05:24:03] Found 1 platforms in file system
INFO:	  [RomM][2024-09-04 05:24:03] · mac
INFO:	  [RomM][2024-09-04 05:24:03]   Identified as Mac 🎮
WARNING:  [RomM][2024-09-04 05:24:03]   ⚠️ No firmware found, skipping firmware scan for this platform
INFO:	  [RomM][2024-09-04 05:24:04]   19 roms found
INFO:	  [RomM][2024-09-04 05:24:04] 	 · Total.War.Warhammer.III.v4.2.3.Incl.DLC.MacOS
INFO:	  [RomM][2024-09-04 05:24:04] 		 · Total.War.Warhammer.III.v4.2.3.Incl.DLC.MacOS.dmg
ERROR:	  [RomM][2024-09-04 09:24:03] Task exceeded maximum timeout value (14400 seconds)

**To Reproduce**
To reproduce the error I juste have to launch a new scan of the platform Mac

**Comment by zurdi15** [comment]
You have an environment variable to modify the default timeout value. Check [https://github.com/rommapp/romm/wiki/Environment-Variables](here) the ``TIMEOUT_SCAN`` variable

**Comment by gantoine** [comment]
It needs to hash the contents of the file, which at 80G will take a looong time. RomM's not designed for modern PC/mac games, and you'll encounter issues with them.

**Comment by Spinnich** [comment]
> It needs to hash the contents of the file, which at 80G will take a looong time. RomM's not designed for modern PC/mac games, and you'll encounter issues with them.

Possible this is getting off topic. But maybe an admin. level toggle to enable / disable hashing per platform or this could be decided at the dev. level. There's definitely plenty of platforms where hashing doesn't make a much sense as I don't believe there's a known good database to reference them.

**Comment by gantoine** [comment]
> There's definitely plenty of platforms where hashing doesn't make a much sense as I don't believe there's a known good database to reference them.

Not not, but when we integrate other hashing tools (hasheous, playmatch) they'll have more value.
