### ISSUE TITLE
[Other] Fixing/Removing wrong properties

### ISSUE THREAD

**Issue by Skeeve** [rommapp/romm#1170]
This is a screenshot of a game that was wrongly recognized as a Yu-Gi-Oh! Game.

<img width="1370" alt="image" src="https://github.com/user-attachments/assets/3dd40c4c-91a1-44ad-b80c-23dfd5712bcc">

I can fix the name and (theoretically) the cover.

But I haven't figured out how to change the other properties:

- genres
- franchises
- collections
- companies

**Comment by zurdi15** [comment]
Tags can't be modified since we pull them from IGDB/Moby games, but eventually it will be editable. Can you search of there is an opened issue for it and upvote and if not, open this issue again and modify it to request editable tags?
