### ISSUE TITLE
[Feature] Toggleable Flag or Text option for Region and Language

### ISSUE THREAD

**Issue by Nomelas** [rommapp/romm#1179]
**Is your feature request related to a problem? Please describe.**
On Mobile, it shows a Flag for the Region and Languages but on Desktop, its Text.

**Describe the solution you'd like**
It would be nice if this was an option that could be set in the settings.

**Describe alternatives you've considered**
As an alternative, just making it always show a flag? Though having it be an option would be nice.

**Additional context**
Example on mobile:
![image](https://github.com/user-attachments/assets/0e9ba1f2-51e4-4933-b9b7-76c96e674c17)

Example on Desktop:
![image](https://github.com/user-attachments/assets/ee0a8e50-1010-426f-9495-f2c2f51171a6)

**Comment by zurdi15** [comment]
Hi, this is a matter of which browser you are using. Some display the flags, some don't. Which one are you using in both desktop and mobile?

**Comment by Nomelas** [comment]
Chrome for both. Android and windows 10.

**Comment by gantoine** [comment]
Yeah chrome on windows won't show the emojis, its a limitation of windows.
