### ISSUE TITLE
[Feature] ignore cue files  (PSX)

### ISSUE THREAD

**Issue by Nazgile94** [rommapp/romm#1180]
if added psx roms with bin + cue files, romm scanns them too and shows the games twice, the cue file + the bin file.

**Comment by adamantike** [comment]
Are you following the [recommended folder structure](https://github.com/rommapp/romm?tab=readme-ov-file#folder-structure), where multi-file ROMs (like bin+cue) must be in a separate folder?

For example:

```
        library/
        ├─ roms/
        │  ├─ ps/
        │     ├─ my_multifile_game/
        │     │   ├─ game1_cd1.bin
        │     │   ├─ game1_cd1.cue
        │     │
        │     ├─ game2.chd
```

**Comment by Nazgile94** [comment]
> Are you following the [recommended folder structure](https://github.com/rommapp/romm?tab=readme-ov-file#folder-structure), where multi-file ROMs (like bin+cue) must be in a separate folder?
> 
> For example:
> 
> ```
>         library/
>         ├─ roms/
>         │  ├─ ps/
>         │     ├─ my_multifile_game/
>         │     │   ├─ game1_cd1.bin
>         │     │   ├─ game1_cd1.cue
>         │     │
>         │     ├─ game2.chd
> ```

Ahhhhhh cue Files in this directory too, Just thinked multi Discs Like final Fantasy ix should BE there 

Okay my fault //closed :) and thanka
