### ISSUE TITLE
[Feature] please make a list of which bios files are for each platform, or allow all bios files to be in the same unsorted bios folder

### ISSUE THREAD

**Issue by Betonhaus** [rommapp/romm#1202]
most emulator systems have all bios files for all systems in a single folder, which means that most bios download packs do not seperate them into folders. while some are easy like gameboy.bin, others like sch1002 you have to look up, and there does not seem to be an organized list of what each bios file belongs to anywhere

**Comment by gantoine** [comment]
this list's keys are defined as <igdb_slug>:<filename>: https://github.com/rommapp/romm/blob/release/backend/models/fixtures/known_bios_files.json
