### ISSUE TITLE
[Feature] Customizable cover aspect ratios

### ISSUE THREAD

**Issue by cjwin2000** [rommapp/romm#1203]
**Is your feature request related to a problem? Please describe.**
Covers for some games on some platforms get cut off or look squished since they all use the same aspect ratio.

**Describe the solution you'd like**
I want to be able to set the aspect ratio of game covers by platform so that platform-specific covers can be used without cropping or deformation.

**Describe alternatives you've considered**
Can't think of any that would work well and not take significantly more work.

**Additional context**
None, let me know if anything needs further clarity.

**Comment by zurdi15** [comment]
This will be added in the next version
