### ISSUE TITLE
[Bug] Downloading games loads the full game into memory

### ISSUE THREAD

**Issue by AngellusMortis** [rommapp/romm#1213]
**RomM version**
3.5.1

**Describe the bug**
If you download a game, it loads the whole game into memory to provide it as a download. This can cause serious performance issues for larger games and even cause containers with memory limits to crash.

**To Reproduce**

1. Add a large multi-gigbyte game
2. Download it

**Expected behavior**

The issue is happening because you are trying to return the attached file in one shot ([FileResponse](https://github.com/rommapp/romm/blob/6022d365f3566294fde06c0b1201c67568f7a109/backend/endpoints/rom.py#L243C9-L243C21)). The file download should instead be streaming the download instead ([StreamingResponse](https://fastapi.tiangolo.com/advanced/custom-response/#streamingresponse)).

For smaller files there will be virtually no noticeable difference, but for larger files, it will be significantly more performant since FastAPI will not need to load the whole game into memory and likely crash itself as a result. It will instead stream small chunks at a time to the client as it downloads the file.

**Comment by MightyRufo** [comment]
I agree 100%

**Comment by adamantike** [comment]
Is this something any of you are experiencing issues with, and can see memory usage increase on file downloads? Or does it only come from reading the code?

Version 3.5.0 changed the way files are downloaded, for nginx to take care of serving the files to clients. No memory usage should surpass whatever value is set in nginx as buffering.

FileResponse seems to be just a remnant in some docstrings, but is not being used to serve the roms directly by FastAPI.

**Comment by AngellusMortis** [comment]
Trying to download a Switch definitely OOM killed my pod in my k8s cluster yesterday. That is why I was looking into it. It seems to be working now though. So maybe there is a case where it does not use sendfile correclty?

**Comment by gantoine** [comment]
Is it possible the files are unzipped and ZIPing with `stream_zip` them is causing the OOM error?

**Comment by AngellusMortis** [comment]
No. They were raw nps files.

**Comment by AngellusMortis** [comment]
I still have not gotten it to happen again. So, I am just going to close this out for now. If I reproduce it again, I will reopen the ticket and hopefully get some logs or something of it happening.
