### ISSUE TITLE
[Bug] Rendering issues with Flash games using Ruffle

### ISSUE THREAD

**Issue by zodac** [rommapp/romm#1216]
**RomM version**
3.5.1

**Describe the bug**
I've tried loading three Flash SWF games using RomM, and all three have rendering issues when compared to Ruffle (both standalone player and the [demo site](https://ruffle.rs/demo/)).

**To Reproduce**
I loaded the following games (downloaded from Flashpoint):

- Bowman 2
- Boxhead: The Rooms
- PaintBall: The Game

**Expected behavior**
The RomM Ruffle player to render the games the same way the Ruffle player itself does it.

**Screenshots**

### Bowman 2

The background seems to be transparent, making it difficult to view things. I tried using both light and dark UI settings in RomM, and in the browser, but it always uses a black background.

_RomM_
![image](https://github.com/user-attachments/assets/7e4683b5-a481-41ce-9d68-af18b27b8c77)

_Ruffle_
![image](https://github.com/user-attachments/assets/6bdd02ae-dbe7-4927-a5d2-232c023c56ae)

### Boxhead: The Rooms

The menu loads just fine, but once the game starts there is just a blue screen (with some HUD elements). The controls and sound work, but unable to see anything.

_RomM_
![image](https://github.com/user-attachments/assets/2242dbcb-9561-459f-8e0f-117a87a2d27e)

_Ruffle_
![image](https://github.com/user-attachments/assets/d4adbb94-c668-4f32-b7f7-6dfa1e677da4)

### PaintBall: The Game

Very minor, but the menu, game and text use painted lines, but the outline/shadow of these lines is missing in RomM.

_RomM_
![image](https://github.com/user-attachments/assets/e500ce36-c211-49e3-8681-9923bc1d7d1e)

_Ruffle_
![image](https://github.com/user-attachments/assets/11b79f7d-e301-4a2c-a93d-5b24c5842081)

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chrome v129, Firefox v130

**Additional context**
Deploying through Docker

**Comment by adamantike** [comment]
We just added a fix that solves the rendering issue for Boxhead: The Rooms, which will be available in the next release.

For Bowman 2, I found that removing the custom backgroundColor property we instantiate Ruffle with fixes it, and the game background becomes white.

I haven't had luck with Paintball: The Game, as I couldn't get past the "Play" splash screen, which always tries to redirect me to Claxon's website.

**Comment by zodac** [comment]
Wow, thanks so much @adamantike! Looking forward to trying them out.

For paintball, there's actually a [bug open on ruffle](https://github.com/ruffle-rs/ruffle/issues/17772) to fix that. But a workaround to test any rendering fix is to use the tab button on the keyboard which will highlight the selectable options, and then press enter when 'play' is highlighted.

**Comment by adamantike** [comment]
Thanks for the context, and for referencing that open bug! I can confirm that the same fix for `Boxhead: The Rooms` also fixed `PaintBall: The Game`! We were using a now obsolete renderer, so rendering should now be similar to Ruffle's demo site.

Regarding the `backgroundColor` change for `Bowman 2`, I will defer that to @gantoine. It looks like the there's no regression when removing that configuration option, at least for these three games. But not sure if it was added because of a different game that actually expected a background color to be set.

**Comment by zodac** [comment]
Thanks again @adamantike!

For the background, @gantoine, is there a way to configure background's per game rather than a default one, or something worth adding in future?

**Comment by gantoine** [comment]
You can make a feature request for it but no promises.

**Comment by zodac** [comment]
That's fair. I'll raise a new request and close one. Thanks to both of you. :)
