### ISSUE TITLE
[Other] Identifying and parsing Arcade systems

### ISSUE THREAD

**Issue by egcarrano** [rommapp/romm#1217]
I am loving RomM. I was looking for this kind of software for a long time. However I could not make it parse and scrape arcade based systems, such as Mame, FBNeo, CPS1, 2, and 3, Naomi and Atomiswave. The only arcade system I could make it work was Neo Geo MVS.

RomM finds the folder but it uses default icons to them and do not identify any game. Those systems use Mame default names for the roms.

Could you give me any advice to make it work?

**Comment by Gibbz** [comment]
I don't see any way to add mame in the library. Is it supported?
