### ISSUE TITLE
[Bug] PS1 not matching any games

### ISSUE THREAD

**Issue by dymas-cz** [rommapp/romm#1221]
**RomM version**
Version: 3.5.1 (running in Docker)

**Describe the bug**
When updating my library i get a match for more than 90% of my roms in all systems. In PlayStation 1 (mounted in /mnt/games/library/:/romm/library) i don't get any match and when trying to manually match it just gives me `No games to show The game you were looking for does not exist`. When i go to IGDB i can search for any of the games in my PS1 library just fine.

**To Reproduce**

1. Add games to PS1 library
2. Rescan all
3. No games matched in PS1 library

Manual
1. Manual match (tested on Croc 2, Tekken 3, Metal Gear Solid)
2. Search for game
4. Get error message `No games to show The game you were looking for does not exist`

**Expected behavior**
Match automaticly or match game manualy based on search by correct game name as copied from IGDB

**Screenshots**
![Screenshot_1](https://github.com/user-attachments/assets/2549a61b-2375-428c-9795-387e1c5e7824)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser Edge
- Version 129.0.2792.65

**Comment by gantoine** [comment]
you ps1 folder name needs to be `ps`, not `ps1` https://github.com/rommapp/romm/wiki/Supported-Platforms
