### ISSUE TITLE
[Feature] Make upload timeout configurable

### ISSUE THREAD

**Issue by yuri-becker** [rommapp/romm#1228]
**Is your feature request related to a problem? Please describe.**
When uploading larger files to RomM, the upload is cancelled after exactly two minutes. When the instance is on a remote server, uploads of even DVD games can take far longer.

**Describe the solution you'd like**
Ideally, admins would be able to configure the timeout, or completely disabling it. Possibly via Environment Variables.

**Describe alternatives you've considered**
An alternative would be to just statically disable the timeout or set it to a high enough time. 

**Additional context**
I originally commented this request on this commit: https://github.com/rommapp/romm/commit/e20465f268ee4618577fe048fbc84182181ceb8c?diff=unified#diff-90fd36aad18db541451cbf233c961cb25c21a3f107ff47e0f8b89057c590797c
This also shows the relevant piece of code.

**Comment by yuri-becker** [comment]
I would also be willing to implement this myself if you're open to it.

**Comment by gantoine** [comment]
Yeah go for it! You'll want to add an env variable for it and import it in `config/__init__.py` (like we do for `SCAN_TIMEOUT`)

**Comment by gantoine** [comment]
Closing this as its merged, will be in the next release.
