### ISSUE TITLE
[UI/UX] gamelist.xml

### ISSUE THREAD

**Issue by maciekish** [rommapp/romm#1244]
Really? Getting lots of config.txt and other junk. Shouldn't a project thats well past 2.0 be able to filter this out automatically? gamelist.xml OBVIOUSLY isn't a ROM...

![image](https://github.com/user-attachments/assets/c60b5144-48d7-433c-a21e-c223cc45da99)

**Comment by adamantike** [comment]
You can help us by using the [bug report template](https://github.com/rommapp/romm/blob/master/.github%2FISSUE_TEMPLATE%2Fbug_report.md), and indicating what's your folder structure, to find potential improvements for the scanning process.

**Comment by Kedryn** [comment]
> This is why you have the [config file](https://github.com/rommapp/romm?tab=readme-ov-file#configuration-file) available, to filter it if you don't want it to be scanned :)



I just wonder why exludes have to be in config file and not in an UI field...

**Comment by zurdi15** [comment]
> > This is why you have the [config file](https://github.com/rommapp/romm?tab=readme-ov-file#configuration-file) available, to filter it if you don't want it to be scanned :)
> 
> I just wonder why excludes have to be in config file and not in an UI field...

Just a matter of time, will be added at some point like the platform bindings of course

**Comment by gantoine** [comment]
@maciekish leave the attitude at the door next time, it's not welcome here
