### ISSUE TITLE
[Bug] Out of memory will caclulating checksum of compressed files

### ISSUE THREAD

**Issue by taki-sahli** [rommapp/romm#1262]
**RomM version**
3.5.1

**Describe the bug**
I found that ROMM use a lot of memory when scannes `7z` files (big size).

**To Reproduce**

1. Add new compressed file in any library with large size (ex: 100GB)
2. Start a `Complete rescan` for that library
3. Watch the memory usage of ROMM worker process.
4. Wait until system crashes 🥲.

**Expected behavior**
ROMM should use better way to calculate the hashe of a file without loading it all in memory (read and calculate by chunk ?).

**Screenshots**
![image](https://github.com/user-attachments/assets/469cc2a6-b84f-4138-b97c-288377967261)

**Desktop (please complete the following information):**

- OS: K3S (NixOS)
- Browser: Firefox
- Version: 131

**Smartphone (please complete the following information):**

**Additional context**
https://github.com/rommapp/romm/blob/6022d365f3566294fde06c0b1201c67568f7a109/backend/handler/scan_handler.py#L235
https://github.com/rommapp/romm/blob/6022d365f3566294fde06c0b1201c67568f7a109/backend/handler/filesystem/roms_handler.py#L251
https://github.com/rommapp/romm/blob/6022d365f3566294fde06c0b1201c67568f7a109/backend/handler/filesystem/roms_handler.py#L115

**Comment by danblu3** [comment]
https://github.com/rommapp/romm/pull/1226

Aware and being worked on for future release

**Comment by gantoine** [comment]
Closing this as the fix has landed on the main branch.
