### ISSUE TITLE
[Bug] Unable to select which rom to run in multi rom title card

### ISSUE THREAD

**Issue by mmahler** [rommapp/romm#1269]
**RomM version**
rommapp/romm:latest docker image @sha256:d3a0cd1d84a3f85f56d4995a2a29f3efd664e2d040bb09fa00be1aded4349ac4
(arm64) Which should be 3.5.1

**Describe the bug**
So I have a largish collection of roms. And I can scan them and get them all viewable pretty easily. Which I have in the file structure like "/romm/library/roms/snes/<game title>/different varient files" For example I might have the Euro release, US Release, JPN Release different versions that were at retail for each, and then sometimes also ROM hacks with amusing sprite swaps etc. They appear as a single title, which is awesome, and looking at the game details page I see the drop down of "files" but I can't seem to get a particular one to load up in emulatorJS. It seems to just pick the first file in the list.

**To Reproduce**

1. Go to 'Any title that has multiple files'
2. Select any single file from the "Files" dropdown
3. Click Play to launch emulators
4. Note the the game playing is the first lex sort order file, and not at all the one selected. 

**Expected behavior**
I would expect that either the file selection is passed onward to the emulatorJS screen, or better yet, if there are multiple roms per title, that the selection drop down is available when selecting BIOS, SAVE and STATE prior to launching the emulator. 

**Screenshots**
![image](https://github.com/user-attachments/assets/c7c789b8-b094-4f17-8f60-40b0822cb5c3)

**Desktop (please complete the following information):**

- OS: MAC Sonoma
- Browser Safari 
- Version 18.01

**Additional context**
<img width="913" alt="Screenshot 2024-10-28 at 1 52 53 PM" src="https://github.com/user-attachments/assets/983760b8-7389-4b3e-8cff-f7ab4b9fe69f">
No way to select file for the emulator

**Comment by gantoine** [comment]
You'll need to change how your regional files are stored, we expect all games to be at the same level. If the scan finds multiple of the same game from different regions, it will group them in the UI, but have a DB entry for each one, and you can swap versions before playing.
