### ISSUE TITLE
[Feature] Install Instructions for non-docker environments

### ISSUE THREAD

**Issue by brad-charboneau** [rommapp/romm#1270]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I simply want bare metal install instructions so that those of us using LXC Containers or VMs can install without docker.

**Describe alternatives you've considered**
I have not considered other options

**Additional context**
Myself and many others use Proxmox as a hypervisor and would like it if a solution can be provided to use native capabilities rather than nesting virtualization layers. since Baremetal instructions work the majority of the time for building out LXC Containers this would be beneficial.  If I have a detailed set of instructions I can likely script it out and create a pull request to include in your repo, if desired.

**Comment by zurdi15** [comment]
I don't think we are going to support a bare metal installation officialy. The closest thing you have to acomplish such task is to follow the [DEVELOPER_SETUP](https://github.com/rommapp/romm/blob/release/DEVELOPER_SETUP.md) and maybe the [dockerfile](https://github.com/rommapp/romm/blob/release/docker/Dockerfile) if you want to check what's done inside to build the image.

**Comment by dotbanana** [comment]
>  If I have a detailed set of instructions I can likely script it out and create a pull request to include in your repo, if desired.  
  
If you fork this for bare-metal please leave a link here.  
I also would be very interested.  
The fact that devs pack all stuff behind this abstraction layer and people basically use server-software like compiled binaries in the beginning of windows-time is concerning at best.

**Comment by adamantike** [comment]
The main reason for declining some of these requests, is not that open source maintainers are lazy, evil, or stupid to not understand the benefits of what's being proposed, although that seems to be the general reaction in some of these issues.

Trying to support every possible deployment mechanism, means that the maintainers will need to spend a lot of time and effort, for stacks they don't even use, to debug and fix issues when the contributor that implemented this "simple" requirement is no longer around. So is it better to accept the proposal, and revert it back when it becomes abandoned, unsupported, and with users asking for assistance?

The project has a very small number of contributors, so I encourage you to join the community, and start small by checking out what regular users are actually having issues with or waiting to be implemented.

**Comment by dotbanana** [comment]
> Trying to support every possible deployment mechanism, means that the maintainers will need to spend a lot of time and effort, for stacks they don't even use, to debug and fix issues when the contributor that implemented this "simple" requirement is no longer around.   

I would understand such an answer when we would be talking about some niche feature that has to be implemented first, but the python & shell-code is already there.  
With asking for this tool without Docker I am not wanting to make it more complicated, but actually more easy. In most other projects you have source code and no Docker-Container.  
A Docker is then often created by third party who maintains it then on Docker-hub for the casuals.   
But you've made it the other way around somehow and you actually think that this is normal. 
This is not normal.

**Comment by justin025** [comment]
The team is being disingenuous in stating a bare metal install would be difficult to maintain, no one writes code inside docker binaries anyway, you use a venv. How would it be any more difficult to properly support a one line command like pip install git+https if anything it would draw in more developers willing to tinker with the project, I was able to fix the problem in ~45 mins.

To give the main devs the benefit of the doubt it is possible they are using a nonfree version of redis which is why they only distribute binaries but that doesn't seem to be the excuse in this case.

I have a pretty messy implementation working. With a cleaned up pyproject.toml and a couple modifications to the config file the app can be run as an unprivileged user, but you do need to also have mysqld and redis-server running for the app to function properly. If the dev team reconsider their stance on baremetal installs I'll write a pr with a little python script to automate everything.

**Comment by gantoine** [comment]
I'm going to say this once and plainly so there's no confusion: we're not going to support an official bare metal setup and it places an undue burden on the development team. Anyone looking to tinker with the project and wanting to push fixes/features can follow the [developer setup guide](https://github.com/rommapp/romm/blob/release/DEVELOPER_SETUP.md) to get it running on their system in under 10 steps.

**Comment by guslanzetta1** [comment]
I too would like to run it on an LXC and that developer setup link is broken.
