### ISSUE TITLE
[Other] Archive emulator support

### ISSUE THREAD

**Issue by kriki200** [rommapp/romm#1279]
Hi, I went through the issues and the main page, but couldn't find any mentions of archive support, can you have compressed files for emulators and which formats do they support. And for the ROM's being hosted I've seen issues mentioning using 7z, so I assume this is supported aswell as zip and the game will get recognised correctly?

**Comment by gantoine** [comment]
Yes it can run archived/zipped games, and we're working on a fix for 7z files.

**Comment by kriki200** [comment]
> Yes it can run archived/zipped games, and we're working on a fix for 7z files.

Thanks :) .
