### ISSUE TITLE
[Feature] Adding screenscrapper.fr API for Images, Boxes and Description

### ISSUE THREAD

**Issue by thehagsn** [rommapp/romm#1281]
https://www.screenscraper.fr provides an API and offers lot of data including standarized pictures of the ingame, the boxes and cardridges, even short videoclips. Pulling Data from there gives the opportunity to have a very consistent design in how the games are showed in the library and gives some even the chance, to cange the style of the picture (for example a Picture of the Box, the Startmenu or Ingame Screenshot...)

It only needs a registration of the user and is free to use. I love to use it on my R36s.

**Comment by zurdi15** [comment]
Duplicated from #212 

Also, already working on it :)
