### ISSUE TITLE
[Bug] UI Settings "Group Roms" does not initially take effect

### ISSUE THREAD

**Issue by MattTW** [rommapp/romm#1283]
**RomM version**
3.5.1

**Describe the bug**
On a fresh install, the "Group Roms" setting displays as True, however roms are not grouped unless the setting is re-toggled.

**Additional context**
I can see in the code that the logic to read the setting is not consistent with the other UI Settings (i.e. default to true if the returned value is null/never been set).  I can submit a quick pull request to make this consistent.

**Comment by zurdi15** [comment]
Yeah this have been there for a while now, a PR would be much appreciated!
