### ISSUE TITLE
[Feature] Show Matched Roms Only - Filter Option in each console

### ISSUE THREAD

**Issue by Moonraka** [rommapp/romm#1285]
**Is your feature request related to a problem? Please describe.**
I want to filer matched roms only. So I don't have to see my un-matched roms I can't find or haven't manually matched.

**Describe the solution you'd like**
When I click on each individual console and the it starts to load the collection of roms. I want a filter option to show only matched roms. (Instead of the current options of Show Favorites, Show UnMatched, Show Duplicates)

**Describe alternatives you've considered**
The only thing I could try is to delete all my un-matched roms using the current app features. There is no easy of moving it to a different folder using Romm or filtering them out of my storage manually to remove from Romm, if I wanted to work on them at a later date.

**Additional context**
Just add a 4th option to show matched only.

![image](https://github.com/user-attachments/assets/3665f98b-656d-49ef-bafa-c924388c09bf)

**Comment by zurdi15** [comment]
Implemented in #1381. Will be available in the next release 3.7.0
