### ISSUE TITLE
[Bug] Issue uploading multiple files at the same time

### ISSUE THREAD

**Issue by Artiom97es** [rommapp/romm#1288]
**RomM version**
Version of RomM you are using: 
unraid latest => 3.5.1

**Describe the bug**
When you try to upload games thru the ui, its stop upload after some uploads, same behaviour with big files(more than 1gb) and small files(less than 800MB)

**To Reproduce**

1. Go to Main Menu
2. Click on Upload Menu
3. Select PlayStation
4. Add Games(more than 20)
5. Upload Some after 5 to 10 uploads, See error.

**Expected behavior**
Expect everything upload at once(or 5 by 5 without gettin error)

**Screenshots**
![imagen](https://github.com/user-attachments/assets/d6de09ef-57ea-42b8-9a24-8c34cbae0b99)

**Desktop (please complete the following information):**

- OS: Windows 11
-Web browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:132.0) Gecko/20100101 Firefox/132.0" 
(latest mozilla firefox)

**Additional context**
tried to learn and test things, so i tried to upload random roms just to see have it shows on RomM

**Comment by Artiom97es** [comment]
btw if you upload 1 by 1 it works perfect

**Comment by Artiom97es** [comment]
upsie, forgetted to change tittle, thanks

**Comment by gantoine** [comment]
Yeah it's very possible we don't support uploading that many, and it's timing out during the upload. Will backlog this but it's low priority ATM.

**Comment by Artiom97es** [comment]
(looks like on patch notes there is a fix for this, so its completed)
