### ISSUE TITLE
[Feature] Add log information when rom metadata purged

### ISSUE THREAD

**Issue by SatorSquare** [rommapp/romm#1292]
**Is your feature request related to a problem? Please describe.**
Currently, when RomM scans a platform it will remove roms from the database that are missing from the filesystem. However, it does not make a log entry in the console when it does so.

**Describe the solution you'd like**
I would like RomM to log whenever it purges rom metadata from the database.

**Additional context**
This was brought up during a discussion on whether or not RomM would retroactively remove rom metadata for roms that were newly filtered via the config.yml. The lack of logging created confusion on when RomM was or was not actually removing rom metadata.

**Comment by gantoine** [comment]
Will be in the next release.
