### ISSUE TITLE
[Bug] TypeError: Object of type datetime is not JSON serializable

### ISSUE THREAD

**Issue by SatorSquare** [rommapp/romm#1294]
**RomM version**
3.5.1

**Describe the bug**
A good number of identified roms seem to be throwing an error in the logs. It seems harmless, but I can't tell.

**To Reproduce**

1. Obtain a copy of "ESPN Great Outdoor Games: Bass 2002" for the gba
2. Scan it with API keys for both IGDB and Moby Games
3. Check the logs

**Expected behavior**
An error should not occur

**Screenshots**

![Capture](https://github.com/user-attachments/assets/20d1e954-4da6-4f58-90b3-c330d9fe8992)

**Desktop (please complete the following information):**

- OS: Windows

**Comment by gantoine** [comment]
Yeah it's a harmless error related to websockets during scans, you can ignore it.
