### ISSUE TITLE
[Other] Map multiple folders to same platform

### ISSUE THREAD

**Issue by short-circuit** [rommapp/romm#1313]
I would like to map multiple folders to the same platform.
I need this because I want to separate games by category.
How can this be achieved? 
Setting platform or version in `config.yml` does not change the behaviour in any way.

**Comment by gantoine** [comment]
Not possible at the moment, and not on the roadmap. This is something that can be handled at the filesystem level in linux, I'd suggest looking in that direction.

**Comment by short-circuit** [comment]
Any way to handle subfolders correctly at least? 
Adding my subfolders makes the folder itself being recognized as a game which then fails to scan. Subfolder of the subfolder is not being scanned.

**Comment by gantoine** [comment]
Subfolder of subfolders are also not supported, mount that subfolder directly as the game folder. You may be able to use igir to restructure your FS to match romm's. https://github.com/emmercm/igir
