### ISSUE TITLE
[UI/UX] View All ROMs

### ISSUE THREAD

**Issue by royaltongue** [rommapp/romm#1330]
Currently it seems that you can only view ROMs by selecting their corresponding console, or by creating Collections. It would be nice if there was a view where we could see every ROM available on the server.

**Comment by zurdi15** [comment]
hi! we are planning in converting the search dialog into a full view, similar to the platforms/collections but without filters to show everything in the library

**Comment by zurdi15** [comment]
Added in #1393 . Will be available in the next release 3.7.0
