### ISSUE TITLE
[Bug] IGDB is lost after "Complete rescan"

### ISSUE THREAD

**Issue by taki-sahli** [rommapp/romm#1332]
**RomM version**
3.6.0

**Describe the bug**
Some games, RomM matches the IGDB to incorrect ID.
To fix it, I use the "Manual Match".
The problem, after "Complete rescan", the matched IGDB ID is lost.

**To Reproduce**

1. Use "Manual match" to any game
2. Run "Complete rescan"
3. The match is lost.

**Expected behavior**
RomM should not reset IGDB ID.

**Screenshots**
Inside:
- The correct game
![{13A46036-BD7F-409C-BD84-213CC8AAC956}](https://github.com/user-attachments/assets/00c77ef4-4d7f-4059-9264-2d0f7338769b)

- After rescan, the game will reset to:
![{515DC1BF-B42E-4970-ABBB-ECB052EE4887}](https://github.com/user-attachments/assets/ae16c487-e962-42e6-ae35-da1d239a9fd1)

- In IGDB website, RomM uses the first result:
![{DC181F72-40E5-469A-9A51-AA06544E7D39}](https://github.com/user-attachments/assets/e30828b1-4aa0-4e2b-a165-88912182456d)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Firefox
- Version: 132.0.1

**Additional context**
As a sugestion, add new sepcial tag named `igdb` like the `rev`.
RomM uses this tag to directly match with IGDB ID wihout search, so after complete rescan, the IGDB ID is preserved and we avoid any mismatch.
ex: `Inside [rev-10,igdb-7342].7z`

**Comment by zurdi15** [comment]
The igdb tag is a good idea, we got that request a long time ago. But the complete rescan behaviour is an expected behavior, you should only perform it in case you want to override everything in the selected platform. In general you should perform a quick scan, that will only pick the unmatched games.

**Comment by taki-sahli** [comment]
I use the "Complete rescan" because of this bug https://github.com/rommapp/romm/issues/1328, the quick scan doesn't update (fix) the size of the game.
Alright I'll check about the igdb tag and create a new issue if needed.
Thank you.
