### ISSUE TITLE
[Bug] Scan request timeout

### ISSUE THREAD

**Issue by therobbiedavis** [rommapp/romm#134]
**RomM version**
1.6.1

**Describe the bug**
While running a scan, the request timeouts.

**To Reproduce**
1. Mount library with an rclone mount
2. Host romm using swag through cloudflare.
3. Click scan
4. Wait and see error

**Expected behavior**
Request should not time out.

**Screenshots**
![image](https://user-images.githubusercontent.com/7907265/229815263-d1ec7592-2bd9-4c5a-a326-d1f1ce728912.png)
![image](https://user-images.githubusercontent.com/7907265/229815423-eab4711f-667d-419d-969c-f3fe9df94a02.png)
![image](https://user-images.githubusercontent.com/7907265/229815618-09a4a507-76aa-4d97-be32-c9b8b0917875.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 111.0.5563.147

**Comment by zurdi15** [comment]
OK I think I can see the problem. When binding the library folder, you need to bind the folder that contains the `rom` folder. In your case this should be like:
 - `/root/Server/mnt/media_merge:/romm/library`

If I am not wrong, you are binding directly the `ROMs` folder.

Also, as RomM right now is case-sensitive, if you bin `/root/Server/mnt/media_merge:/romm/library` it will detect your `ROMs` folder as a platform folder. You can or rename `ROMs` to `roms` or make a symlink `roms -> ROMs`

**Comment by therobbiedavis** [comment]
Never mind, it seems to have gone through. Thank you for your hard work! Closing issue.
