### ISSUE TITLE
[Feature] Add usernames to log when file is downloaded

### ISSUE THREAD

**Issue by idio-sync** [rommapp/romm#1348]
**Is your feature request related to a problem? Please describe.**
Not a problem, but currently, only ip addresses are logged when a user initiates a download.

**Describe the solution you'd like**
If possible, it would be neat if the name of the user that initiated a download was also passed. This info would allow for more useful statistics collection.

**Additional context**
I'm working on a stats module for the Discord bot, and this would allow me to list download counts/data used by user, etc.

**Comment by VFansss** [comment]
Actually I know that this resembles quite a feature creep, but would be good to...keep a complete audit of those who login, play e download files.

That way, using a simple report the admin can measure how much the resources are used.

**Comment by gantoine** [comment]
Can you open this as a new issue, and first check if audit logs aren't already in issue list?
