### ISSUE TITLE
[Bug] Crash on library scan

### ISSUE THREAD

**Issue by kceleslie** [rommapp/romm#1352]
**RomM version**
Latest, cant find the version number in the GUI

**Describe the bug**
I'm probably doing something wrong but I'm not getting any log output to help trouble shoot. I've got a new install and when i manually upload a ROM it places it in the library folder then kicks off a scan. At that point the container restarts. I've tried tailing the log but I only get this

```
INFO:     [RomM][scan][2024-12-09 20:24:48] 🔎 Scanning                 
20:24:48 high: endpoints.sockets.scan.scan_platforms([2], <ScanType.QUICK: 'quick'>, [], ['igdb']) (fa3accef-ae99-4880-9f99-efccda9b4bf4)
```

**To Reproduce**

1. Go to Upload
2. Click on 'Select the system'
3. Upload the ROM
4. File is uploaded, it starts a scan then crashes

**Expected behavior**
It scans and adds the ROM. 

**Screenshots**
N/A

**Desktop (please complete the following information):**

Server is running on a linux distro (Debian) under K3S.  The data directory is a NFS share. I have verified that the container can write to the share (it will upload the file). 

**Smartphone (please complete the following information):**

n/a

**Additional context**
I've also tried adding all of my ROMs directly to the share but they are not picked up.  I've used the folder structure guide so decided to try it manually.  It might be how I have it setup, I just dont have any logging pointing me in the direction that i need to review. q

**Comment by zurdi15** [comment]
Can you share your compose and your tree directory?

**Comment by kceleslie** [comment]
Not sure what it was, but i was going through my k3s config and changed a few things to post and it worked (no longer crashed) and my ROMs started showing up. I'll go through the config to see if i can identity what caused it, but mine is good now. Thanks
