### ISSUE TITLE
[Bug] Plattform versions don't scrape against their master plattform name

### ISSUE THREAD

**Issue by Duglim** [rommapp/romm#1356]
If you setup a plattform version (e.g. a folder "mame" as a version of "arcade") the roms within this version ("mame") is using his own fodler name on scraping IGDB. Logically the scraping fails ("mame" is no valid IDGB slug).

Potential Fix: 
Roms in a plattform version use their master versions (here "arcade") on IDGB scraping. 

Additional idea:
Roms in a plattform version also use their master version for EmulatorJS (e.g. "mame" could get play-buttons)

Thx a lot for your great work!
Duglim

**Comment by gantoine** [comment]
`mame` is not a version of `arcade`, so you don't want to use it https://www.igdb.com/platforms/arcade
what you want instead is a mapping instead, like this:
```
system:
  platforms: { mame: 'arcade' n}
```
