### ISSUE TITLE
[Bug] Repeated CallbackIO write Operations During Scans for PS3 and Xbox Games in RomM

### ISSUE THREAD

**Issue by Salpertio** [rommapp/romm#1363]
RomM Version
Latest version available via Docker Compose on Unraid.

Describe the Bug
RomM exhibits repetitive and seemingly unnecessary "CallbackIO write" operations during scans, regardless of the platform (e.g., PS3, Xbox).

Initially, a PS3 game (Aliens vs. Predator) was scanned, and the logs showed repeated CallbackIO write entries for individual files within the game archive. Later, an Xbox game (Blinx - The Time Sweeper) was deleted from the library and rescanned. Despite the game being successfully re-added, the same repetitive CallbackIO write logs appeared during the rescan process.

This behavior suggests RomM may be unnecessarily extracting or reprocessing game archives rather than cataloging them based on file names and metadata. It leads to redundant file operations and excessive log entries.

To Reproduce

Add a PS3 game (e.g., Aliens vs. Predator) to the library and perform a scan.
Observe the logs showing repetitive CallbackIO write entries for files such as .PS3_TEXTURES.
Delete an Xbox game (e.g., Blinx - The Time Sweeper) from the library.
Rescan the directory containing the Xbox game to re-add it to the library.
Notice that the game reappears in the library, but the logs again show repetitive CallbackIO write entries for files like .dds textures.

Expected Behavior

RomM should catalog game archives primarily based on file names or metadata without fully extracting their contents during every scan.
Repeated "CallbackIO write" operations for the same files should not occur unless absolutely necessary (e.g., the archive has changed).
Cached metadata or results should be used for efficiency during subsequent scans.

Screenshots or Logs

PS3 Game Log Snippet:

CallbackIO: write. filename=Aliens vs. Predator/PS3_GAME/USRDIR/ENVS/MP/MP_REFINERY.PS3_TEXTURES
CallbackIO: write. filename=Aliens vs. Predator/PS3_GAME/USRDIR/ENVS/MP/MP_REFINERY.PS3_TEXTURES
...
Xbox Game Log Snippet:

CallbackIO: write. filename=Blinx - The Time Sweeper/media/r21b_ref.dds
CallbackIO: write. filename=Blinx - The Time Sweeper/media/r21b_ref.dds
CallbackIO: write. filename=Blinx - The Time Sweeper/media/r21c_ref.dds
...

Desktop Environment

OS: Unraid
Docker Compose Version: rommapp/romm:latest
Browser: [e.g., Chrome 119, Firefox 118]
Version: [Browser version, if applicable]

Additional Context
This issue occurs across multiple platforms, including PS3 and Xbox games. The repetitive logs suggest that RomM might be unnecessarily extracting or reprocessing game files during every scan rather than leveraging file names and metadata for cataloging. There may also be a lack of caching, leading to repeated operations for already-scanned files.

The behavior was observed during:

An initial scan of a PS3 game (Aliens vs. Predator), where repetitive logs appeared for the same .PS3_TEXTURES files.
Deleting an Xbox game (Blinx - The Time Sweeper) from the library and rescanning the directory, resulting in similar repetitive logs for .dds texture files.

Please advise if this callback behavior is expected or if it might be improved for efficiency and performance.

**Comment by zurdi15** [comment]
That's an expected behavior since RomM performs a hashing operation for every scanned game (except for PC titles). I'm a future release we maybe can add an option to decide which platforms must be hashed.

**Comment by adamantike** [comment]
This is actually that I forgot to delete this `print` statement: https://github.com/rommapp/romm/blob/release/backend/utils/archive_7zip.py#L21
