### ISSUE TITLE
[Bug] Can't edit password

### ISSUE THREAD

**Issue by jarjarfinks** [rommapp/romm#1370]
**RomM version**
latest docker

**Describe the bug**
As a "viewer" or "editor" user, I'm unable to  change the password of my profile

**To Reproduce**

1. Create editor or viewer user
2. Login as said user
3. Attempt to change password in  the "profile" section of the Web UI

Screenshot:
![image](https://github.com/user-attachments/assets/99c97c87-0bda-4902-b588-d1f5cac8859f)

**Expected behavior**
I should be able to change password

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Chrome

- OS: Bazzite
- Browser: Chrome

Here's the logs from docker when attempted:
``[nginx][2024-12-21 03:09:10]	10.11.1.50 - - "PUT /api/users/7?username=user&password=***&enabled=true&role=editor HTTP/1.1" 403 22 "https://emu.jfinks.com/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36" rt=0.007 uct="0.000" uht="0.007" urt="0.007"``

**Comment by gantoine** [comment]
This is fixed on master and will be in the next release.
