### ISSUE TITLE
[Bug] Can't toggle "check all" checkbox

### ISSUE THREAD

**Issue by barthofu** [rommapp/romm#1380]
**RomM version**
`v3.6.0`

**Describe the bug**
Can't toggle the "check all" checkbox on any platform romlist page. 

**To Reproduce**

1. Go to any platform romlist page (ex: `<base_url>/platform/1`)
2. Click on the checkbox in the first header column of the table (see related screenshot below)
3. Nothing happens

**Expected behavior**
It should toggle the checkboxes of all the currently filtered and shown lines in the table.

**Logs**
No related logs in the log output of the server.

**Screenshots**
![image](https://github.com/user-attachments/assets/388c9f4a-d799-4b28-8506-918dadfba7d4)

**Desktop (please complete the following information):**

- OS: `nixos 24.11`
- Browser: `firefox 131.0.3`

**Comment by zurdi15** [comment]
Fixed in #1382 for the next release 3.7.0
