### ISSUE TITLE
[UI/UX] Change the location of the Start, Select, Rewind, Fast and Slow buttons in the mobile web UI

### ISSUE THREAD

**Issue by n00b12345** [rommapp/romm#1384]
Would it be possible to shift the Select, Start, Fast, Rewind and Slow menus so that it's not hindering the playing area in mobile UI? Maybe by moving it to the right or the left?

It's not a problem in portrait mode, but only in landscape. Please see the screenshot.

![398124945-dff3a028-8b2e-4a74-af10-078dfeeeab9c](https://github.com/user-attachments/assets/a84daf64-ae20-4f87-bd9b-8ce7f2f1175c)

I had raised this issue as with Emulator JS repo, but it seems like it [can be customised](https://github.com/EmulatorJS/EmulatorJS/issues/926#issuecomment-2559998746). Would be grateful if you could consider this as a feature.

**Comment by gantoine** [comment]
You'll need to make this request on the emulatorjs project https://github.com/EmulatorJS/EmulatorJS
