### ISSUE TITLE
[Bug] RomM does't support MySQL?

### ISSUE THREAD

**Issue by gujiangjiang** [rommapp/romm#1395]
I'm using MySQL not MariaDB and it shows error blew
`
2024/12/26 22:38:31 | stdout | INFO:     [init][2024-12-26 14:38:31] Starting up, please wait...
-- | -- | --
2024/12/26 22:37:57 | stdout | ERROR:    [init][2024-12-26 14:37:57] Something went horribly wrong with our database
2024/12/26 22:37:56 | stderr | sqlalchemy.exc.InvalidRequestError: MySQL version 9.1.0 is not a MariaDB variant.
2024/12/26 22:37:56 | stderr | raise exc.InvalidRequestError(
2024/12/26 22:37:56 | stderr | File "/src/.venv/lib/python3.12/site-packages/sqlalchemy/dialects/mysql/base.py", line 2629, in _set_mariadb
2024/12/26 22:37:56 | stderr | self._set_mariadb(
2024/12/26 22:37:56 | stderr | File "/src/.venv/lib/python3.12/site-packages/sqlalchemy/dialects/mysql/base.py", line 2607, in _parse_server_version
2024/12/26 22:37:56 | stderr | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/12/26 22:37:56 | stderr | return self._parse_server_version(val)
2024/12/26 22:37:56 | stderr | File "/src/.venv/lib/python3.12/site-packages/sqlalchemy/dialects/mysql/base.py", line 2584, in _get_server_version_info
2024/12/26 22:37:56 | stderr | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/12/26 22:37:56 | stderr | self.server_version_info = self._get_server_version_info(
2024/12/26 22:37:56 | stderr | File "/src/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 518, in initialize
2024/12/26 22:37:56 | stderr | default.DefaultDialect.initialize(self, connection)
2024/12/26 22:37:56 | stderr | File "/src/.venv/lib/python3.12/site-packages/sqlalchemy/dialects/mysql/base.py", line 2833, in initialize
2024/12/26 22:37:56 | stderr | dialect.initialize(c)
2024/12/26 22:37:56 | stderr | File "/src/.venv/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 749, in first_connect
2024/12/26 22:37:56 | stderr | ^^^^^^^^^^^^^^^^^^^
2024/12/26 22:37:56 | stderr | return once_fn(*arg, **kw)
2024/12/26 22:37:56 | stderr | File "/src/.venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 1912, in go
2024/12/26 22:37:56 | stderr | fn(*args, **kw)
2024/12/26 22:37:56 | stderr | File "/src/.venv/lib/python3.12/site-packages/sqlalchemy/event/attr.py", line 497, in __call__
2024/12/26 22:37:56 | stderr | self(*args, **kw)
2024/12/26 22:37:56 | stderr | File "/src/.venv/lib/python3.12/site-packages/sqlalchemy/event/attr.py", line 483, in _exec_w_sync_on_first_run
2024/12/26 22:37:56 | stderr | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/12/26 22:37:56 | stderr | )._exec_w_sync_on_first_run(self.dbapi_connection, self)
2024/12/26 22:37:56 | stderr | File "/src/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 914, in __connect
2024/12/26 22:37:56 | stderr | self.__connect()
2024/12/26 22:37:56 | stderr | File "/src/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 674, in __init__
2024/12/26 22:37:56 | stderr | ^^^^^^^^^^^^^^^^^^^^^^^
2024/12/26 22:37:56 | stderr | return _ConnectionRecord(self)
2024/12/26 22:37:56 | stderr | File "/src/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 390, in _create_connection
2024/12/26 22:37:56 | stderr | ^^^^^^^^^^^^^^^^^^^^^^^^^
2024/12/26 22:37:56 | stderr | return self._create_connection()
2024/12/26 22:37:56 | stderr | File "/src/.venv/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
2024/12/26 22:37:56 | stderr | raise exc_value.with_traceback(exc_tb)
2024/12/26 22:37:56 | stderr | File "/src/.venv/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
2024/12/26 22:37:56 | stderr | ^^^^^^^^^^^^^^^^^^^
2024/12/26 22:37:56 | stderr | with util.safe_reraise():
2024/12/26 22:37:56 | stderr | File "/src/.venv/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 179, in _do_get
2024/12/26 22:37:56 | stderr | ^^^^^^^^^^^^^^
2024/12/26 22:37:56 | stderr | rec = pool._do_get()
2024/12/26 22:37:56 | stderr | File "/src/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
2024/12/26 22:37:56 | stderr | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/12/26 22:37:56 | stderr | fairy = _ConnectionRecord.checkout(pool)
2024/12/26 22:37:56 | stderr | File "/src/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
2024/12/26 22:37:56 | stderr | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/12/26 22:37:56 | stderr | return _ConnectionFairy._checkout(self)
2024/12/26 22:37:56 | stderr | File "/src/.venv/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 449, in connect
2024/12/26 22:37:56 | stderr | ^^^^^^^^^^^^^^^^^^^
2024/12/26 22:37:56 | stderr | return self.pool.connect()
2024/12/26 22:37:56 | stderr | File "/src/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3300, in raw_connection
2024/12/26 22:37:56 | stderr | ^^^^^^^^^^^^^^^^^^^^^^^
2024/12/26 22:37:56 | stderr | self._dbapi_connection = engine.raw_connection()
2024/12/26 22:37:56 | stderr | File "/src/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 146, in __init__
2024/12/26 22:37:56 | stderr | ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/12/26 22:37:56 | stderr | return self._connection_cls(self)
2024/12/26 22:37:56 | stderr | File "/src/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3276, in connect
2024/12/26 22:37:56 | stderr | ^^^^^^^^^^^^^^^^
2024/12/26 22:37:56 | stderr | with engine.connect() as connection:
2024/12/26 22:37:56 | stderr | File "/backend/alembic/env.py", line 81, in run_migrations_online
2024/12/26 22:37:56 | stderr | run_migrations_online()
2024/12/26 22:37:56 | stderr | File "/backend/alembic/env.py", line 97, in <module>
2024/12/26 22:37:56 | stderr | File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
2024/12/26 22:37:56 | stderr | File "<frozen importlib._bootstrap_external>", line 995, in exec_module
2024/12/26 22:37:56 | stderr | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/12/26 22:37:56 | stderr | spec.loader.exec_module(module)  # type: ignore
2024/12/26 22:37:56 | stderr | File "/src/.venv/lib/python3.12/site-packages/alembic/util/pyfiles.py", line 113, in load_module_py
2024/12/26 22:37:56 | stderr | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/12/26 22:37:56 | stderr | module = load_module_py(module_id, path)
2024/12/26 22:37:56 | stderr | File "/src/.venv/lib/python3.12/site-packages/alembic/util/pyfiles.py", line 95, in load_python_file
2024/12/26 22:37:56 | stderr | util.load_python_file(self.dir, "env.py")
2024/12/26 22:37:56 | stderr | File "/src/.venv/lib/python3.12/site-packages/alembic/script/base.py", line 583, in run_env
2024/12/26 22:37:56 | stderr | script.run_env()
2024/12/26 22:37:56 | stderr | File "/src/.venv/lib/python3.12/site-packages/alembic/command.py", line 403, in upgrade
2024/12/26 22:37:56 | stderr | fn(
2024/12/26 22:37:56 | stderr | File "/src/.venv/lib/python3.12/site-packages/alembic/config.py", line 608, in run_cmd
2024/12/26 22:37:56 | stderr | self.run_cmd(cfg, options)
2024/12/26 22:37:56 | stderr | File "/src/.venv/lib/python3.12/site-packages/alembic/config.py", line 631, in main
2024/12/26 22:37:56 | stderr | CommandLine(prog=prog).main(argv=argv)
2024/12/26 22:37:56 | stderr | File "/src/.venv/lib/python3.12/site-packages/alembic/config.py", line 641, in main
2024/12/26 22:37:56 | stderr | ^^^^^^
2024/12/26 22:37:56 | stderr | sys.exit(main())
2024/12/26 22:37:56 | stderr | File "/src/.venv/bin/alembic", line 8, in <module>
2024/12/26 22:37:56 | stderr | Traceback (most recent call last):
2024/12/26 22:37:54 | stdout | INFO:   [RomM][redis_handler][2024-12-26 14:37:54] Redis async connection established in /src/.venv/bin/alembic!
2024/12/26 22:37:54 | stdout | INFO:   [RomM][redis_handler][2024-12-26 14:37:54] Connecting to async redis in /src/.venv/bin/alembic...
2024/12/26 22:37:54 | stdout | INFO:   [RomM][redis_handler][2024-12-26 14:37:54] Redis sync connection established in /src/.venv/bin/alembic!
2024/12/26 22:37:54 | stdout | INFO:   [RomM][redis_handler][2024-12-26 14:37:54] Connecting to sync redis in /src/.venv/bin/alembic...
2024/12/26 22:37:51 | stdout | 12:M 26 Dec 2024 14:37:51.417 * Ready to accept connections tcp
2024/12/26 22:37:51 | stdout | 12:M 26 Dec 2024 14:37:51.417 * Server initialized
2024/12/26 22:37:51 | stdout | 12:M 26 Dec 2024 14:37:51.415 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
2024/12/26 22:37:51 | stdout | 12:M 26 Dec 2024 14:37:51.415 * Running mode=standalone, port=6379.
2024/12/26 22:37:51 | stdout | 12:M 26 Dec 2024 14:37:51.414 * monotonic clock: POSIX clock_gettime
2024/12/26 22:37:51 | stdout | 12:C 26 Dec 2024 14:37:51.413 * Configuration loaded
2024/12/26 22:37:51 | stdout | 12:C 26 Dec 2024 14:37:51.413 * Valkey version=7.2.7, bits=64, commit=00000000, modified=0, pid=12, just started
2024/12/26 22:37:51 | stdout | 12:C 26 Dec 2024 14:37:51.413 * oO0OoO0OoO0Oo Valkey is starting oO0OoO0OoO0Oo
2024/12/26 22:37:51 | stdout | 12:C 26 Dec 2024 14:37:51.413 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
2024/12/26 22:37:51 | stdout | INFO:     [init][2024-12-26 14:37:51] starting valkey-server
2024/12/26 22:37:46 | stdout | INFO:     [init][2024-12-26 14:37:46] Starting up, please wait...
2024/12/26 22:29:16 | stdout | INFO:   [RomM][redis_handler][2024-12-26 14:29:13] Redis async connection established in /src/.venv/bin/alembic!
2024/12/26 22:29:16 | stdout | INFO:   [RomM][redis_handler][2024-12-26 14:29:13] Connecting to async redis in /src/.venv/bin/alembic...
2024/12/26 22:29:16 | stdout | INFO:   [RomM][redis_handler][2024-12-26 14:29:13] Redis sync connection established in /src/.venv/bin/alembic!
2024/12/26 22:29:13 | stdout | INFO:   [RomM][redis_handler][2024-12-26 14:29:13] Connecting to sync redis in /src/.venv/bin/alembic...
2024/12/26 22:29:10 | stdout | 12:M 26 Dec 2024 14:29:10.427 * Ready to accept connections tcp
2024/12/26 22:29:10 | stdout | 12:M 26 Dec 2024 14:29:10.427 * Server initialized
2024/12/26 22:29:10 | stdout | 12:M 26 Dec 2024 14:29:10.427 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
2024/12/26 22:29:10 | stdout | 12:M 26 Dec 2024 14:29:10.427 * Running mode=standalone, port=6379.
2024/12/26 22:29:10 | stdout | 12:M 26 Dec 2024 14:29:10.426 * monotonic clock: POSIX clock_gettime
2024/12/26 22:29:10 | stdout | 12:C 26 Dec 2024 14:29:10.425 * Configuration loaded
2024/12/26 22:29:10 | stdout | 12:C 26 Dec 2024 14:29:10.425 * Valkey version=7.2.7, bits=64, commit=00000000, modified=0, pid=12, just started
2024/12/26 22:29:10 | stdout | 12:C 26 Dec 2024 14:29:10.424 * oO0OoO0OoO0Oo Valkey is starting oO0OoO0OoO0Oo
2024/12/26 22:29:10 | stdout | 12:C 26 Dec 2024 14:29:10.424 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
2024/12/26 22:29:10 | stdout | INFO:     [init][2024-12-26 14:29:10] starting valkey-server

`

How to solve this?

**Comment by zurdi15** [comment]
From MySQL 8.0, Mysql and MariaDB have diverged significantly. I suggest you to just stick to the docker-compose example and spin up a MariaDB container

**Comment by zurdi15** [comment]
good news! @adamantike managed to make mysql work

#1396
