### ISSUE TITLE
[Feature] Collections

### ISSUE THREAD

**Issue by doctorniz** [rommapp/romm#219]
It would be neat to be able to form different "playlists" of games, that we can get into quickly. For example a "Hannah" playlist for the games she likes to play often. Or a "SteamDeck" or "Odin" playlist for games we would like to port onto that system. Basically a tag system.
It would be even neater if we could download all the roms in that playlist in a single zip file to move from system to system. 

What do you think?
I like this better than Gameyfin and Emulator.js at present and have high hopes for this project.

**Comment by zurdi15** [comment]
I am planning on introduce ``collections``. It is pretty the same as your request, so of you don't mind I change the title to keep the track :)

**Comment by XargonWan** [comment]
Because of [this](https://github.com/zurdi15/romm/discussions/293) I would not mix collections and devices code side (then is up to the users).

**Comment by ameturpoet** [comment]
I would still love to see this implemented in RomM - I think it would be a genuinely transformative addition to the software. Allowing users to add roms to custom collections visible to all users with your own names and descriptions (And maybe an option to download everything in the collection at once) would be a great tool for curation of the best games, hidden gems, or romhacks for the users of a RomM server. I can't wait to see this feature implemented!

**Comment by Perrylicious** [comment]
Hi! I thought this topic fit my idea for a feature the best, so I'm going to append this here.

Imagine a use case where you have curated a large selection of games for several platforms. Now you want to take a **collection** on the road with you, maybe to put on a handheld device.

A user could put together a collection of such games and then use a button such as **"download collection"** to gather all the roms tagged into that collection, ideally sorted into their folder structure, into a ZIP file for downloading and putting on a device.

However, there are already curated lists of "must-play" games out there, such as the TinyBestSet GO list and its expansions. Users could possibly **import a collection** (i.e. a listing of games) from such a list to see what roms they are still missing in Romm and to later facilitate the download of that collection without pulling from an external source.
