### ISSUE TITLE
[Feature] ROM patching thought UI

### ISSUE THREAD

**Issue by binarygeek119** [rommapp/romm#227]
rom patching would be useful to those of us that play rom hacks/translations.

i think a sub page in the game details "Rom Hacks" then it would list in the original rom details with all the hacked roms of that game.

"Super Mario 64" = "Super Mario 64 - Star Road"

i think a auto name would work. filename + patch/hack name = filename - patch/hack.rom

and auto move the rom into a folder then in that folder a subfolder hacks

|rom
        | Super Mario 64
                                    | Hacks
                                                | Super Mario 64 -Star Road.rom
                                    | Super Mario 64.rom
        | nextgame.rom                             
        | etc

**Comment by XargonWan** [comment]
I already made an analisys of this issue here, feel free to get inspired or implement it in the same way: https://github.com/RetroMan-project/core/issues/30

**Comment by velmirslac** [comment]
Integration with [RomPatcher.js](https://github.com/marcrobledo/RomPatcher.js) might make this easier.

**Comment by GAntoine** [comment]
Support for #228 would be nice-to-have before attempting to implement this. I worry about patching large ROMs in JS, since it would mean patching them fully in RAM. It seems someone has written a little [python utility](https://github.com/Sebelino/pyromhackit) for this, although I haven't tried it yet.

**Comment by binarygeek119** [comment]
I would add from dlc and patch this folder structure

roms/ps3
- dlc
-- game1/dlc1
-- game1/dlc2
- patches
-- game1
-- game2
- game1.ps3
- game2.ps3
- hacks
-- game1.total_conversion.n64
-- game2.new_level.n64
- translations
-- game1.jpn2eng.nes
-- game2.spanish2eng.nes

In the webui in the game details add hack/patch then select what type of hack/patch

Patch
- official (from dev)
- unofficial (community made) [example: Skyrim unofficial patch v2]
Hacks
- total conversation [example: GTA vice City to bttf hill valley]
- minor hack
-- added content, new feature, character/vehicle mod (check boxs)
Translations
- Japanese to English (jpn2eng)
- Spanish to English (span2eng)
- Spanish to Japanese (span2jpn)

**Comment by gantoine** [comment]
Going to close this as won't due, due to its low priority and the fact that other tools can do this way better then we ever could. https://github.com/emmercm/igir
