### ISSUE TITLE
[Feature] Custom CSS injection

### ISSUE THREAD

**Issue by philipjholm** [rommapp/romm#278]
I was asked to create a feature request for this so here it is :)

It would be nice if a user could have the possibility to write custom CSS in the settings that would then be injected after the apps default styling. This would mean that more advanced users could personalize the app more and could even lead to people making themes for it in the future.

**Comment by GAntoine** [comment]
Theming is a cool idea, but low priority at the moment, as we're still trying to nail core functionality. If there's a specific change to the UI you think would benefit most users let us know!

**Comment by gantoine** [comment]
Going to close this as won't due due to it's low priority, and the high chance users will start raising questions about why their changes do/don't work. For those determined to make changes this is already possible using browser extensions/user scripts.
