### ISSUE TITLE
[Feature] Internationalization

### ISSUE THREAD

**Issue by studioj2y** [rommapp/romm#366]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Hi zurdi15, I noticed this project is en-US only at the moment, will you consider to support more languages? I can help translating to ch-ZH, maybe start from the UI then the ROMs, like matching pairs.

**Describe alternatives you've considered**

**Additional context**

**Comment by GAntoine** [comment]
So there's 2 parts to your request: internationalization for our UI, and alternative/region-specific names for platforms and games.

On the UI side, the plan **long-term** is likely to support i18n with crowdsourced translation using something like https://kazupon.github.io/vue-i18n. While we're a ways away from that, there's structural work we could do now to make supporting it easier in the future.

As for platform/rom names, IGDB does offer alternative/region-specific names via the API, which we can pull into the product. And when we get around to [supporting other scrapers](https://github.com/zurdi15/romm/issues/212), there's likely more we can do then.

@studioj2y  Does that makes sense?

**Comment by studioj2y** [comment]
Yes GAntoine, that makes sense perfectly. 
I am familiar with i18n and I will be ready to provide help when needed. 
Thanks.
