### ISSUE TITLE
[Feature] Base URL config option

### ISSUE THREAD

**Issue by BitterSweetcandyshop** [rommapp/romm#379]
**Is your feature request related to a problem? Please describe.**
just setting up nginx configs and I noticed I was struggling because everytime I would load from "https://mydomain.com/romm" romm would look for "https://mydomain.com/assets" when it's really under "https://mydomain.com/romm/assets"

**Describe the solution you'd like**
under enviroment in the docker config to add a BASE_URL=romm

**Describe alternatives you've considered**
Lots of struggling with nginx to make it work, all the programs I currently use support this one way or another

**Additional context**
I'm not great with nginx really, but it would be nice to also see some proxy examples for people to use.

**Comment by GAntoine** [comment]
> It would be nice to also see some proxy examples for people to use.

Personally I use subdomains like `games.domain.com`, as I found support for subpaths tends to be limited when self-hosting. If there's a clean way to implement this on a code-level (which doesn't require manually updating every `history.push` and `/assets` src) I'm all for it.

**Comment by JacobDB** [comment]
I would greatly appreciate support for this; I like to put my self-hosted applications at a directory path for slightly more "security through obscurity." For example, you can easily do a DNS lookup to find "romm.example.com," but if you have `server.example.com/romm`, that's much harder to locate. Additionally, it's nice being able to only have to manage SSL for one subdomain.

If adjusting your code is too much to ask, perhaps you could document all of the "root" URLs that would need to be rewritten? I wouldn't mind writing my own Apache rules to forward everything appropriately, but I have no idea what needs to be forwarded.

**Comment by zurdi15** [comment]
> If adjusting your code is too much to ask, perhaps you could document all of the "root" URLs that would need to be rewritten? I wouldn't mind writing my own Apache rules to forward everything appropriately, but I have no idea what needs to be forwarded.

You can check the API docs under http://yourromminstance/api/docs
