### ISSUE TITLE
[Bug] Special characters awareness

### ISSUE THREAD

**Issue by XargonWan** [rommapp/romm#454]
Try to match the names by ignoring the special characters if no match is found, for example in this case the game was not found because the rom name contains a "-" instead of a "/" that of course it's an illegal character for file paths.

![image](https://github.com/zurdi15/romm/assets/6771419/848269a0-5cd5-4a27-a963-57a94b31ba7c)

![image](https://github.com/zurdi15/romm/assets/6771419/5ea7ba7b-9b05-4f13-8f06-3f879fdd44f4)

**Comment by XargonWan** [comment]
Another example is the use of `-` instead of `:` in the filenames that it cannot be recognized by RomM.

For example Animal Crossing: Wild World cannot be matched because the filename contains `-` instead of `:` that it's an invalid character for a filename (yeah not on linux but you got the point :P).

![image](https://github.com/zurdi15/romm/assets/6771419/9318b5b1-491b-4727-b3bb-e8536d378fed)

![image](https://github.com/zurdi15/romm/assets/6771419/6dcbd5a4-de85-4f2a-be1a-1f6ab0dcd8f4)

**Comment by XargonWan** [comment]
A different example: same name as IGDB but both got a special character in the middle:

![image](https://github.com/zurdi15/romm/assets/6771419/7ea86891-2828-498d-8fe2-29a292a599c6)

![image](https://github.com/zurdi15/romm/assets/6771419/c2e8fa93-6b5e-4aca-a36e-b3faec37a935)

**Comment by gantoine** [comment]
Closing in favor of #392
