### ISSUE TITLE
[Feature] Docker container ignores user parameter

### ISSUE THREAD

**Issue by Bankst** [rommapp/romm#516]
**RomM version**
2.1.0

**Describe the bug**
Container ignores specified `user` parameter, instead requiring uid/gid 1000 to have access to any volume mounts.

**To Reproduce**
Set `user` parameter in docker-compose.yaml, i.e. `user: "3000:3000"`

**Expected behavior**
Container obeys defined user when accessing files, running application

**Comment by gantoine** [comment]
@psych0d0g Any chance this is something you're familiar with? I understand user permissions but I'm not exactly sure how to update perms within romm.
