### ISSUE TITLE
[Feature] Add 'Scan for New Platforms'

### ISSUE THREAD

**Issue by Span24** [rommapp/romm#568]
Is your feature request related to a problem? Please describe:
Yes
When adding new platforms to a large collection then 'scanning' for new roms in that collection RomM will scan every configured platform instead of just the newly added platform, taking considerable time on larger collections particularly if there are a number of previously unidentified roms which RomM must chew through first.

Describe the solution you'd like:
Add a function to the scan section to 'scan for new platforms'. Such a function could quickly look for new platforms then scan only those found.  This could save considerable time with large collections.

![image](https://github.com/zurdi15/romm/assets/50145815/abe54c97-c59c-4dc8-91dd-777964218edf)

**Comment by gantoine** [comment]
This is neat but definitely a nice-to-have more then anything, I'll backlog it if someone wants to pick it up.

**Comment by gantoine** [comment]
Yeah I want to clarity that my answer is by no means a "no", I can see the benefit in this. That being said scan do run in the background, so you can close the browser window while it scan and it'll just keep going (unless it crashes lol).

**Comment by gantoine** [comment]
Update: this will be released in the upcoming 3.1 release!
