### ISSUE TITLE
[Feature] Include docker environment variables in config.yml

### ISSUE THREAD

**Issue by Span24** [rommapp/romm#578]
RomM uses the environment variables in the docker template to set things such as asynchronous tasks, db type, auth, etc.  Some other docker apps also allow for these to be (optionally) set and read from their configs.  For many users it is easier to edit the config.yml than to add additional environment variables (not included in the default template).  Additionally, reading them from the config.yml would require only a restart of the container on edit, unlike editing the template which requires a reload/install of the template. 

Examples and explanations could be easily included in the config.yml.  See attached examples:
![image](https://github.com/zurdi15/romm/assets/50145815/1bfbc95b-6ed6-4e61-8907-62540b7106bd)

**Comment by zurdi15** [comment]
@gantoine thoughts about this? I have contradictory feelings

**Comment by daedric7** [comment]
Wouldn't a .env file suffice here ? The docker-compose.yaml could read the $var from the .env, but use a sane default if absent.

**Comment by gantoine** [comment]
Alright after reading the above and thinking about it some more, I don't think we should change the way things are set up right now. The way I see it, env variables are for concerns of the docker container, like database connection, secret keys and task settings, whereas the config is for library concerns, like platforms bindings, folder names and file exclusion.

This isn't currently the case for variables like `ROMS_FOLDER_NAME`, but we've refactored that in #491.
