### ISSUE TITLE
[Feature] Guest mode

### ISSUE THREAD

**Issue by Tiagoez** [rommapp/romm#579]
Is your feature request related to a problem? Please describe.
having many services that use their own authentication system.

Describe the solution you'd like
A guest mode that allows users to view and download without requiring a login

Describe alternatives you've considered
Support for LDAP

Additional context
None

**Comment by gantoine** [comment]
Going to close this as too much work, given that this can be done right now by creating a viewer-role user with `guest:password` as login credentials.
