### ISSUE TITLE
[UI/UX] Ignore custom/unidentified platforms when initiating a scan with "Rescan Identified" enabled

### ISSUE THREAD

**Issue by Casuallynoted** [rommapp/romm#599]
At the moment, when starting a scan with the "Rescan Identified" checkbox checked, it will scan through every platform for IGDB matches. It may be more efficient to have it skip any platforms that are not found on IGDB/any custom platforms so reduce unnecessary IGDB queries.

**Comment by gantoine** [comment]
This should be improved in the upcoming 3.1 release
