### ISSUE TITLE
[Feature] Retroachievement

### ISSUE THREAD

**Issue by Dreadlocke12** [rommapp/romm#628]
**Is your feature request related to a problem? Please describe.**
Not directly a problem but my rom library is mainly in German. Retroachievement does support however not every rom in German language so I have 2 version of the same game in my library. I usually tag the RA compatibel version with (Achievement) then so I can see which version is supported and which not. 

**Describe the solution you'd like**
In RA the Supported Game Files are listed and you can see which one are supported based on their md5 hash value. (For ps1 games with multiple files it is the hash of the .cue file). I was wondering if it is possible to show either the md5 value of the files in the overview or to add a RA icon for example to the cover if it is supported.

**Comment by gantoine** [comment]
We're very limited in what we can show in the overview the overview, but what you can do is enable "group roms", then under any game (detail view) with multiple versions you'll see a "versions" toggle, which will also show all tags including `(Achievements)`.

**Comment by Dreadlocke12** [comment]
Ok i will try that. I thought by scanning the library having an option to check the md5 hash and then show it as information below the size for example would be usefull. I can then compare it with the supported game files in retroachievments on my own.

**Comment by zurdi15** [comment]
> Ok i will try that. I thought by scanning the library having an option to check the md5 hash and then show it as information below the size for example would be usefull. I can then compare it with the supported game files in retroachievments on my own.

We will likely do something like this when we add the .DAT support to match roms by md5 in any case

**Comment by gantoine** [comment]
Closing this as unrelated to development of retroachievement support.
