### ISSUE TITLE
[Feature] Scan Job Timeout value configuration

### ISSUE THREAD

**Issue by CygnusHyoga** [rommapp/romm#632]
**Is your feature request related to a problem? Please describe.**

Having huge library and scan it doesn't finish because of the 4 hour timeout.  I'm always frustrated when try to run a full scan and can't scan all libraries.

[scan.py](https://github.com/zurdi15/romm/blob/1a8fb4c496d24d85141be4a10628b439998c7851/backend/endpoints/scan.py#L117) --> job_timeout=14400,  # Timeout after 4 hours

**Describe the solution you'd like**

Give an option to disable timeout, via an environment value.

**Describe alternatives you've considered**

Add timeout setting by environment variable: to enable or disable it (ideal) or personalise timeout value in hours

**Additional context**

I think this issue is related to this proposal: https://github.com/zurdi15/romm/issues/573

Thank you! I love the concept of RomM, it's wonderful!

**Comment by gantoine** [comment]
A timeout needs to be set, otherwise you'll have jobs that hand forever and take up the worker. Going to backlog this as low priority, since it's nice-to-have but not a necessity atm.

**Comment by CygnusHyoga** [comment]
Thanks for putting feature to backlog. 

For incoming user who have the same problem with a huge library, a temporary fix I found is this:

1. - first  run a 'Complete Rescan' (at 4 hours it's stop)
2. - then run a SCAN without mark 'Complete Rescan' option (and without Rescan Unidentified), and the scan start in the last platform where its left.
3. Execute step 2, as many times as necessary to complete the huge library scan (keep in mind the 4 hours interval)
