### ISSUE TITLE
[Bug] Defining a platform location twice causes the previous entries to be removed

### ISSUE THREAD

**Issue by Kelduum** [rommapp/romm#639]
**RomM version**
RomM 2.3.1 (Docker)

**Describe the bug**
When defining a platform in `config.yml` user `system:`>`platforms:`, specifying two local directories with the same IGDB slug will cause the second one encountered in a scan to remove the existing entries.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add, `mame: 'arcade'` and `fbneo: 'arcade'` to the config.yml under platforms.
2. Place files in both directories.
3. Run a scan.
4. Note how the second instance encountered causes all the entries in the first to be removed from the DB.
5. Subsequent scans will repeat this.

**Expected behaviour**
Both sets of files should be combined under the platform.

**Additional context**
It's likely that #621 will provide a better workaround for this, with a temporary workaround being to scan one platform location and then add that location to the `exclude:`>`platforms:`.

Ultimately there should be some accommodation for files for a single source to potentially be found in multiple locations, but a warning in the example config would be good in the short-term.

**Comment by gantoine** [comment]
That's expected, since the relationship is bi-directional and romm wouldn't know where to place games uploaded via the UI.

**Comment by Kelduum** [comment]
> That's expected, since the relationship is bi-directional and romm wouldn't know where to place games uploaded via the UI.

As a new user that seems very counter-intuitive - if it didn't know where to put things, it should probably just ask which of the options it should use, and shouldn't just remove potentially huge volumes of data.

As an example, my clean instance has been pulling data from IMDB for a solid week now, as the scan can never actually *finish* - there's a few platforms I keep separated for various reasons which have been fighting amongst themselves, and the daily scans mean its keeps going - so a few hundred people doing this would probably anger IGDB! :)

Admittedly, this may well be moot (barring warnings in the config file and/or something to stop people doing it accidentally) when #621 hits release.

**Comment by gantoine** [comment]
Yeah that's likely, when 3.0 launches run a scan and update this issue with your results.
