### ISSUE TITLE
[Feature] Support read-only library

### ISSUE THREAD

**Issue by fatflyingpigs** [rommapp/romm#64]
**Is your feature request related to a problem? Please describe.**
I keep my library read-only, mainly so apps such as this cannot accidentally delete files (either because of an app bug, or my own user error). Currently the docker mounts `/library` for games and `/library/resources` for image resources related to each game. When mounting the former as RO and the latter as RW, docker will throw an error similar to `error mounting to rootfs at read-only file system: unknown`. This is due to adding the RW folder as a subfolder of a RO mount. This can be overcome by adding a folder called "resources" within my game library (but I'd rather not have this empty folder in my host's library mount folder).

**Describe the solution you'd like**
It would be useful to separate the location of the game library and the downloaded resources. Entirely separate directories would be ideal. Or maybe some setting/config to set the location?

**Describe alternatives you've considered**
The image assets could also be stored in the DB. Though it could result in DB bloat, and may require some implementation of sqlite VACUUM for deleted/removed games.

**Additional context**
Great app! Very glad you've shared this with all of us~!

**Comment by zurdi15** [comment]
RomM is now more flexible with folder structure. In this version you can acomplish the read only library system if you follow the high priority structure [v1.5](https://github.com/zurdi15/romm/releases/tag/v1.5)

I will remain the issue open as in the future I will implemente to let the users define where the resources folder should be
