### ISSUE TITLE
[Feature] Allow users to change password

### ISSUE THREAD

**Issue by jcsomerville** [rommapp/romm#663]
Once a user is logged in with the credentials provided by the host, it would be advantages to allow the user to then change their own password. 

There shouldn't be any security issue since the user who logged in would have just used the original password set.

**Comment by SenilePenguin** [comment]
Just wanted to check, are there are any plans or ETAs for this feature? It would be nice to have users provide their own passwords, at least until we get some sort of OAuth implemented ;)

**Comment by gantoine** [comment]
Nothing concrete yet, but I promise we'll do it!

**Comment by gantoine** [comment]
This is now complete and available in the latest release!
