### ISSUE TITLE
[Feature] Tag games and give access by tag

### ISSUE THREAD

**Issue by jcsomerville** [rommapp/romm#666]
If possible, it would be great if we could have the ability to limit a specific users scope.

I have young family members who would enjoy using RomM very much.

A way to limit a users scope could be using tags so they only see games tagged with their tag.

Example: user 'Bud' has the tag 'Kids' applied to them. I go through and apply the tag to any game I feel is appropriate for them.

Tags also could be applied to exclude games, such as 'Adult'.

This would be awesome. Also could be applied to series, 'Pokemon' etc.

**Comment by gantoine** [comment]
Going to close this in favor of collections. We're going to create a new user type which only has access to pre-build collections shared with them/made public, which should cover the use case well.
