### ISSUE TITLE
[Feature] Integration with a multi-platform ROM frontend/launcher

### ISSUE THREAD

**Issue by ffiarpg** [rommapp/romm#676]
**Is your feature request related to a problem? Please describe.**
It is a hassle to setup emulation on a new computer or steam deck and copy my games off a server on demand to play them. It's also a hassle to sync saves between say a pc and a steam deck.

**Describe the solution you'd like**
I'd like a client-server setup where I can setup my games once on a server such a romm and quickly setup a client on a new machine and point it to the server to access all of my games to install on demand with a gamepad, similar to game stores like steam. Ideally with game save sync.

**Describe alternatives you've considered**
There is not a great multi-platform client-server system to host games (and optionally saves) on a server and access them via a client (windows linux or macOS front-end). The closest I've found is Playnite with LANCommander/emulibrary plugins which is Windows only at the moment.
A few paths I've considered:
-a hosted share of files with the client handling everything. Can't find a client that can reliable handle downloading games from a remote path except playnite with emulibrary which is windows only. Playnite next version will switch to some multi platform libs but dev is not promising linux support any time soon.
-an existing multi-platform gamepad friendly launcher that supports external sources and cloud save functionality. Heroic Games Launcher seems like a decent candidate. It has strong steam deck support. It uses a library called gogdl for GOG.com integration which is written in python and could probably be modified to swap all GOG calls to instead call a self hosted game server like romm. This is currently the front-runner in my eyes especially since I'm most familiar with python and that lead me to romm. There might be other options out there, I'd certainly like to understand the future direction of this project to see if that is an idea worth pursuing and putting effort into.

**Comment by zurdi15** [comment]
Hi! we have plans for device-sync features in the mid term, but developing a client is not in the roadmap because RomM development team can't afford it right now.

You can find more information [here](https://github.com/zurdi15/romm/discussions/293)

**Comment by gantoine** [comment]
The first beta of the Playnite plugin was just released, check it out! https://github.com/rommapp/playnite-plugin

**Comment by ffiarpg** [comment]
Please reopen. The request was for a multiplatform launcher and playnite only supports windows.

**Comment by gantoine** [comment]
Here's a list of open-source launchers I've found after a quick search:

- [Playnite](https://github.com/JosefNemec/Playnite)
  - Pros: plugin support, great documentation, active development,
  - Cons: windows-only
- [Heroic Games Launcher](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher)
  - Pros: active development, cross-platform
  - Cons: **no plugin system**, limited to GOG/Amazon/Epic Game
- [Lutris](https://github.com/lutris/lutris)
  - Pros: active development
  - Cons: **no plugin system**, linux-only
- [GameVault](https://github.com/Phalcode/gamevault-app)
  - Pros: 🤷🏼 
  - Cons: **no plugin system**, monetized
  
The lack of a plugin system is a major hurdle, as it would require us to integrate directly into another project. That would place an undue burden on the maintainers, having to maintain against our API.

**Comment by ffiarpg** [comment]
Understood, appreciate the feedback. Still crossing my fingers for Playnite Linux support.

**Comment by ffiarpg** [comment]
What about Retrohub? They just added an integrations API.

https://github.com/retrohub-org/retrohub/releases

**Comment by binarygeek119** [comment]
Launchbox has a plugin system but is not open source

**Comment by gantoine** [comment]
> What about Retrohub? They just added an integrations API.

I'll add it to the list, but I think it's too small of a project (~100 stars) to focus on at the moment.

> Launchbox has a plugin system but is not open source

I've got a list of emulation-specific launchers (Launchbox, ES-DE, Pegasus, Mednafen, Bizhawk, OpenEmu, etc.), which I consider different from these multi-platform launchers. We do plan to work on these eventually!
