### ISSUE TITLE
[UI/UX] Pagination bar unusable in listview when rom list is large

### ISSUE THREAD

**Issue by w00tlarr** [rommapp/romm#677]
RomM version
V2.3.1

Describe the bug
Pagination bar is not implemented. When I reach to the bottom at 60 at listview to the pagination bar, it keeps going down and I am unable to use te pagination bar as it keep appending and pushing the pagination bar. I have a large list of roms, so this is very helpful to scroll through and skip jump to other pages right away rather than keep scrolling and scrolling to where I need to be.

To Reproduce
Open a Platform with large list of roms, and try to use the pagination bar below - it will keep pushing down and it won't be reachable.

Desktop (please complete the following information):
Windows 11, MS Edge Chromium

![image](https://github.com/zurdi15/romm/assets/126688857/72b2ffc0-9f13-4281-90f3-fb0f76ce1ec7)

**Comment by zurdi15** [comment]
Hi! yes, sorry for the confusion, the pagination is not a thing in table view in this case, it's just a part of the component we use to display the table but we can't disable it, we just support filter/search roms or dynamically load when scrolling.

It's not planned to support pagination right now for how backend works, but I think we can manage to remove the footer to avoid confusion

**Comment by w00tlarr** [comment]
Ah... with large libraries, scrolling is painful to browse and search is not really by single A, B, C.. capable so it hard to filter to have a smaller subset. Well - it's not critical but if I can recommend as a feature enhancement, it would be helpful to browse over large libraries.

I hope one day I can learn VueJS to do this filtering on my own PR. Just can't commit to that now.

**Comment by zurdi15** [comment]
Yeah as feature would be nice to have, but in this case is not a matter of vuejs, that's the easy part. We could already do it with couple of code lines. The bottleneck is the backend :/

**Comment by gantoine** [comment]
This is be fixed in the 3.2.0 release
