### ISSUE TITLE
[Feature] Remember fullscreen choice

### ISSUE THREAD

**Issue by alexfornuto** [rommapp/romm#701]
**Is your feature request related to a problem? Please describe.**
Another QoL request.  When testing games through the web UI, I prefer not to start them in fullscreen. This means repeatedly unchecking the "Full screen" check box each time.

**Describe the solution you'd like**
One of two solutions:
- Make the "Full screen" checkbox remember the last state,
- Allow users to define a default value for this option.

**Describe alternatives you've considered**
The alternative is just more clickity clacks of the mizouse. 

**Additional context**
If needed, will provide.

**Comment by gantoine** [comment]
This will be fixed in v3.2 release!
