### ISSUE TITLE
[Bug] DB migration "Duplicate entry '30' for key 'PRIMARY'"

### ISSUE THREAD

**Issue by Fabaderheld** [rommapp/romm#705]
**RomM version**
3.0.1

**Describe the bug**
After fixing #697 this error occurs
```
sqlalchemy.exc.IntegrityError: (mariadb.IntegrityError) Duplicate entry '30' for key 'PRIMARY'
[SQL: INSERT INTO platforms VALUES (?,?,?,?,?,?,?)]
[parameters: (23, None, 'dc', 'dc', 'Dreamcast', '', 30)]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
ERROR:    [init][2024-03-14 08:46:39] Something went horribly wrong with our database
```

**To Reproduce**
Start DB migration

**Expected behavior**
Migrating DB

**Comment by gantoine** [comment]
You're likely stuck half way through the migration, and unless you're willing to open the DB in something like DBeaver and start messing with rows, I'm afraid the only option is to start with a fresh mariadDB instance and volume. 😞
