### ISSUE TITLE
[Feature] Password recovery system

### ISSUE THREAD

**Issue by zurdi15** [rommapp/romm#706]
**Is your feature request related to a problem? Please describe.**
From @smallthe in discord:

It looks like the latest 3.0.1 update fixed the authentication issue.  But I'm wondering how to reset the password if it is forgotten.  Because in this situation it could cause the loss of a large database if it is not possible to change the password manually.

**Describe the solution you'd like**
A recovery system for forgotten passwords

**Comment by gantoine** [comment]
Closing in favour of #663

**Comment by adamantike** [comment]
This issue comes from a time where RomM only had username/password. However, as we have added email address as part of the user information, a "Recover password" flow would be possible now.
