### ISSUE TITLE
[UI/UX] Player view overflowing viewport + ad hoc suggestions

### ISSUE THREAD

**Issue by JMBeresford** [rommapp/romm#714]
On a wide viewport the player view will exceed the height of the window:
![image](https://github.com/zurdi15/romm/assets/1373954/a5436768-5b79-4642-894d-7706690e11c3)

This is due to the forced 16:9 aspect-ratio of the EJS container [here](https://github.com/zurdi15/romm/blob/b3ad9eb22b189b4ac6fd043f0af607cfbb5aee49/frontend/src/views/Play/Base.vue#L124) along with an inherited `width: 100%;` style prop. My suggestion is to limit the wrapper size to bounds of the viewport, and the aspect-ratio property will continue to work w/ added spacing on the respective axis:
![image](https://github.com/zurdi15/romm/assets/1373954/cba4c0df-9814-4cfb-865b-3bb1c71eab23)

Additionally, I think (among some other more minor UI/UX concerns) it would be prudent to have some sort of back navigation in the provided overlay UI. e.g. a 'back to roms' button or menu entry

I took the time to clone the repo and get the app up and running, and will gladly push up my fix for one or both of these issues if this would be helpful. What is the procedure for PRs (i.e. what target branch, other expected due diligence not noted in the docs)?

**Comment by zurdi15** [comment]
Fixed in [v3.0.2](https://github.com/rommapp/romm/releases/tag/3.0.2)
