### ISSUE TITLE
[Feature] Change detection rescan debouncing

### ISSUE THREAD

**Issue by simonaplin** [rommapp/romm#719]
**Is your feature request related to a problem? Please describe.**
My instance has been doing nothing but rescanning the same platform for over an hour now. The reason appears to be that I was curating during the scan, deleting and renaming ROMs as they were imported. It seems this queued up multiple rescans based on file changes.

**Describe the solution you'd like**
If a rescan of a particular platform is scheduled but not yet started subsequant requests to rescan that platform should be discarded. 

**Describe alternatives you've considered**
Restarting ROMM didn't help, the scheduled rescans continued.

**Comment by gantoine** [comment]
Huh I'm pretty sure I wrote a check for that, but while I debug this you can disable filesystem watcher with `ENABLE_RESCAN_ON_FILESYSTEM_CHANGE=false` or increase the delay with `ENABLE_RESCAN_ON_FILESYSTEM_CHANGE=60 # 60 minutes`
