### ISSUE TITLE
[Feature] GoG.com integration, auto-update games library

### ISSUE THREAD

**Issue by ecker00** [rommapp/romm#720]
**Is your feature request related to a problem? Please describe.**
GoG is a great source for DRM free games and installers, an integration would make it easy to truly own your game installers with it's latest updates and patches.

**Describe the solution you'd like**
Possibility to give RomM my Gog.com username and password, and set it to download all my game installers. Every night it would check for updates.

**Describe alternatives you've considered**
Currently I manually do this, it's a lot of work to maintain and checking for updates and patches is even worse.

**Comment by gantoine** [comment]
Other apps like [Playnite](https://playnite.link/) already integrate with GoG (via plugins), and now that R[omM also integrates with Playnite](https://github.com/rommapp/playnite-plugin) I don't think this is within the scope of RomM.

**Comment by ecker00** [comment]
I've also given it some more thought and this should be a standalone service, that saves into the same storage location as RomM. I've started drafting up some python working with GoG's API, we'll see what comes of it down the line.

**Comment by gantoine** [comment]
>  this should be a standalone service

like playnite or gog galaxy? playnite already has both gog and romm plugins, unless you're looking for something cross-platform

> that saves into the same storage location as RomM

ah so you want to use romm as the storage system for your gog games?

curious to see what comes out of this!

**Comment by ecker00** [comment]
We already do use RomM to store all our games, works great! (Categories or tags would be welcomed feature). We only collect DRM free games (humble bundle, itch, gog). I am building a media library that the family and children can enjoy, one day even these games will be considered retro. And DRM is always a deal breaker for longevity.

Would be nice with a better approach to deal with game updates and new purchases. I found a few other open source projects which handles downloading from GoG, but most are manual or UI based, but they are a good foundation to work from. I'm imagining it as a background service running along side the RomM container in Docker, which keeps your self-hosted library up to date.

https://github.com/eddie3/gogrepo
https://github.com/Sude-/lgogdownloader

**Comment by ecker00** [comment]
Think you can safely close this issue, unless you are also triggered by this idea and want to integrate it directly into RomM. As I mentioned, I think it will work quite well as a stand-alone project, just configure it to write to the same directory for each platform.

**Comment by gantoine** [comment]
It's not a bad idea, but it's so low on the list of priorities that I worry we'd never get to it.
