### ISSUE TITLE
Should my PS1 roms be playable with eJS?

### ISSUE THREAD

**Issue by gantoine** [rommapp/romm#728]
### Discussed in https://github.com/zurdi15/romm/discussions/727

<div type='discussions-op-text'>

<sup>Originally posted by **crispybegs** March 17, 2024</sup>
hi all,
i just checked my ROMM instance and saw the emulatorJS inclusion.. very good very nice.

Older systems like BG / GBA / Wonderswan etc are playable in my browser, but PS1 is not.
I checked the eJS [page](https://github.com/EmulatorJS/EmulatorJS) and it says Playstation is supported, but none of my ROMM roms have a play symbol.

Is there something I need to do to make those playable?</div>

**Comment by gantoine** [comment]
Not playable until release BIOS support in an upcoming 3.x version https://github.com/zurdi15/romm/wiki/EmulatorJS-Player

**Comment by crispybegs** [comment]
> @crispybegs Not playable until release BIOS support in an upcoming 3.x version https://github.com/zurdi15/romm/wiki/EmulatorJS-Player

aha ok, thanks!

**Comment by IvanMazzoli** [comment]
It seems that EmulatorJS added support for PSX!

https://emulatorjs.org/docs/systems/playstation
