### ISSUE TITLE
[Bug] "network error" when trying to play "Monsters, Inc." from GBA

### ISSUE THREAD

**Issue by Urkaz** [rommapp/romm#729]
**RomM version**
3.0.1

**Describe the bug**
When trying to run the game "Monsters, Inc." from GBA, the emulator displays a "network error" while showing "net::ERR_RESPONSE_HEADERS_MULTIPLE_CONTENT_DISPOSITION" in the Chrome console.
It may be a problem related to the name of the game or something like that due to it having a comma (https://kb.blackbaud.com/knowledgebase/Article/69701).

This only seems to happen in Google Chrome (on Edge it loads correctly), and it persists even after changing the rom name to remove all commas or other special characters (it may be a problem with the save states or save files?).
Also, I tested my dump in other emulators and in the emulatorJS demo page (https://demo.emulatorjs.org/) and it works correctly, so the problem has to be in RomM

**To Reproduce**
1. Have a "Monsters, Inc." GBA copy and place it in the library.
2. Click the play button and start the emulator.
3. See the error

**Expected behavior**
The rom should load.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome 122.0.6261.129

**Comment by gantoine** [comment]
Damn great debugging work 👌 This'll be fixed in the next release!

**Comment by Urkaz** [comment]
This is fixed in [3.1.0-rc.1](https://github.com/rommapp/romm/releases/tag/3.1.0-rc.1) and it works correctly :D
Thank you!
