### ISSUE TITLE
[Other] Do not package Redis in the container

### ISSUE THREAD

**Issue by DarkVirtue** [rommapp/romm#741]
Distributing the Redis keystore server inside the romm container goes against common practice for building containers - that is, one service per container. Redis being in the container restricts user options and wastes resources. It's fine that a keystore like Redis is a hard dependency for romm as long as that's clear in the documentation, like the SQL database is.

I'm already running Redis containers for several other services - I pull the Redis container once to use for multiple instances. Others may prefer to use a central Redis instance to serve multiple services. Using Redis replication for high availability is also much more difficult.

Including Redis in the container also creates a vendor lock-in. Users may not want to use Redis, especially now that [Redis is no longer open source](https://redis.com/blog/redis-adopts-dual-source-available-licensing/). For example, users may prefer [Redict](https://codeberg.org/redict/redict), [KeyDB](https://github.com/Snapchat/KeyDB), or [Dragonfly](https://github.com/dragonflydb/dragonfly).

**Comment by zurdi15** [comment]
Hi! Redis was a separated container until ``3.0``, but we decided to integrate it into RomM container listening to users feedback.

However in the next release we will make it optional, using the internal if not configured an external one.

About using other solutions, that's something we didn't explore yet, so I don't think that's going to be a feature in the short term.

**Comment by gantoine** [comment]
Like zurdi mentioned the option to run your own will come back very soon!

> I pull the Redis container once to use for multiple instances

I'd recommend against this in general, as some libraries (sidekiq, celery) could cause key collisions. In. our case we namespace key storage when accessing cache directly and through rq-scheduler, but something to keep in mind.

> Including Redis in the container also creates a vendor lock-in

The current version of redis we include is FOSS, and upgrading is a manual process; version needs to be set in the `Dockerfile`, so it's unlikely to get upgraded by accident. When the times comes to upgrade, we'll consider alternatives like Redict.

**Comment by DarkVirtue** [comment]
>>   I pull the Redis container once to use for multiple instances

> I'd recommend against this in general, as some libraries (sidekiq, celery) could cause key collisions. In. our case we namespace key storage when accessing cache directly and through rq-scheduler, but something to keep in mind.

Sorry, what I mean here is I pull one Redis *image* (such as `redis:alpine`) and then deploy multiple containers using that image. They're still independent instances of Redis. The image takes up disk space once regardless of the number of Redis containers running from that image.

Thanks for the input and I'll be looking forward to the next release.

**Comment by gantoine** [comment]
> Sorry, what I mean here is I pull one Redis image (such as redis:alpine) and then deploy multiple containers using that image.

Ah thanks for clearing that up, I do the same thing in my setup (seeing as redis is pretty light).

And thanks for the feedback! I'm going to close this one, but feel free to open a discussion about redis in the [Discussions](https://github.com/rommapp/romm/discussions) section with your thoughts, or bring it to the Discord. Truth is we'll have to deal with this eventually, but the longer we can wait the better.
