### ISSUE TITLE
[Bug] Romm doesn't start properly when lxc reboots in Proxmox

### ISSUE THREAD

**Issue by MtnDewster** [rommapp/romm#744]
**RomM version**
3.0.1

**Describe the bug**
Romm not starting properly when lxc reboots in Proxmox. Website loads fine, but no roms are there as if it can't connect to the database.

**To Reproduce**
1. Restart lxc container in Proxmox.
2. When loaded, go to Romm and roms wont be there.

**Expected behavior**
Should start up like normal and show all your roms.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 124

**Additional context**
Here are the logs it shows when this happens.

> 2024/03/20 22:17:41 [error] 18#18: *6 connect() to unix:/tmp/uvicorn.sock failed (111: Connection refused) while connecting to upstream, client: MY_COMPUTER_IP_ADDRESS, server: localhost, request: "GET /api/users/me HTTP/1.1", upstream: "http://unix:/tmp/uvicorn.sock:/users/me", host: "SERVER_IP_ADDRESS", referrer: "SERVER_IP_ADDRESS"
> 
> INFO:      [nginx][2024-03-20 22:17:41]    MY_COMPUTER_IP_ADDRESS - - "GET /api/users/me HTTP/1.1" 502 157 "SERVER_IP_ADDRESS" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:124.0) Gecko/20100101 Firefox/124.0" rt=0.000 uct="-" uht="-" urt="0.000"

**Comment by gantoine** [comment]
We've changed to gunicorn in the upcoming 3.1 release, which should stop these sock disconnect issues. That being said give it shot when it goes live, and comment here if it's still happening.
