### ISSUE TITLE
[Bug] Last update to INIT file has and issue

### ISSUE THREAD

**Issue by evilbobbins** [rommapp/romm#749]
**RomM version**
3.x

**Describe the bug**
when starting a fresh install on Unraid the docker image fails on Init
/init: line 105: PUID: unbound variable

**To Reproduce**
1. install app on unraid
2. check logs 
3. show error '/init: line 105: PUID: unbound variable'

**Expected behavior**
Init should pass and docker should run

**Desktop (please complete the following information):**
 - OS: Unraid 6.12.8

**Additional context**
Install working fine previouse evening pre update

**Comment by shyonae** [comment]
What did you do to fix this? Having the same issue.

**Comment by shyonae** [comment]
![image](https://github.com/rommapp/romm/assets/88051140/67b42f2f-e0e7-4cff-95a1-8147b3f67eb6)
This is the image I have right now, pulled today, I still get the same error

**Comment by gantoine** [comment]
What's the error you're seeing when running the image? And can you pin romm to 3.0.3, stop it, delete the container, delete all romm images, and start it again?
