### ISSUE TITLE
[Bug] turbografx16--1 platform tag displays default controller icon

### ISSUE THREAD

**Issue by ameturpoet** [rommapp/romm#760]
**RomM version**
3.0.1

**Describe the bug**
Instead of the TurboGrafx-16 controller icon shown for the `turbografx-16-slash-pc-engine-cd ` platform, the turbografx16--1 platform instead shows the default controller icon.

**To Reproduce**
1. Create folder named turbografx16--1 with HuCard roms, scan the folder
2. See that RomM uses the default controller icon for the platform

**Expected behavior**
The TurboGrafx-16 controller icon is displayed instead.

**Comment by gantoine** [comment]
This will be fixed in the next release!
