### ISSUE TITLE
[UI/UX] Add platform controller icons for PC-FX, Astrocade, Nuon, Tiger Gizmondo and Tapwave Zodiac

### ISSUE THREAD

**Issue by ameturpoet** [rommapp/romm#761]
There are some supported platforms which still do not have specific icons - it would be nice to see them get their own platform icons instead of the default platform icon.

**Comment by Casuallynoted** [comment]
Hello! This sounds like a job for me :) I'll see if I can't put some icons together this week and submit them to the project!

**Comment by Casuallynoted** [comment]
NGL, Libretro has fantastic icons for all of these - I'm going to submit a PR with the icons and attribution :)

**Comment by gantoine** [comment]
Thanks @Casuallynoted, these will be included in the next release
