### ISSUE TITLE
[Bug] Login not working

### ISSUE THREAD

**Issue by ethronrion** [rommapp/romm#765]
**RomM version**
3.0.1

**Describe the bug**
Since updating to 3.0.1 and the necessity of logging in I can't seem to access romm anymore.
When logging in (credentials are correct) first I get a CSRF error, so I deactivated CSRF for now (testing instance, no access from anyone apart from me).
When I log in romm immediately redirects me back to the login page. I'm attaching the network trace in case you can see something in there,

**To Reproduce**
1. Go to login page
2. Enter credentials
3. Click on login
4. Redirect to login

**Expected behavior**
Being logged in and able to browse/add roms.

**Screenshots**
Screenshot of Network Trace
![Screenshot from 2024-03-27 14-50-29](https://github.com/rommapp/romm/assets/33331353/7c1430ea-af1d-4f75-ba2e-58650938ad25)

**Desktop (please complete the following information):**
 - OS: Manjaro
 - Browser Firefox
 - Version 124.0.1

**Additional context**
Container being hosted on unRAID with separate mariadb container. Redis from romm-image is being used.
Authentication was disabled before upgrading to 3.x, in case that matters.

**Comment by gantoine** [comment]
can you try to login, get redirected, then post the container logs?

**Comment by ethronrion** [comment]
Sure.
I redacted some of the lines, as they don't seem to have anything to do with the issue:

INFO:      - "POST /login HTTP/1.0" 200 OK
INFO:     [nginx][2024-03-27 15:11:03]  client_ip - ethronrion "POST /api/login HTTP/1.1" 200 32 "http://server_ip:8091/login" "Mozilla/5.0 (X11; Linux x86_64; rv:124.0) Gecko/20100101 Firefox/124.0" rt=0.418 uct="0.000" uht="0.418" urt="0.418"
INFO:      - "GET /roms?size=15&order_by=id&order_dir=desc HTTP/1.0" 403 Forbidden
INFO:     [nginx][2024-03-27 15:11:03]  client_ip - - "GET /api/roms?size=15&order_by=id&order_dir=desc HTTP/1.1" 403 22 "http://server_ip:8091/" "Mozilla/5.0 (X11; Linux x86_64; rv:124.0) Gecko/20100101 Firefox/124.0" rt=0.006 uct="0.000" uht="0.005" urt="0.005"
INFO:      - "GET /platforms HTTP/1.0" 403 Forbidden
INFO:     [nginx][2024-03-27 15:11:03]  client_ip - - "GET /api/platforms HTTP/1.1" 403 22 "http://server_ip:8091/" "Mozilla/5.0 (X11; Linux x86_64; rv:124.0) Gecko/20100101 Firefox/124.0" rt=0.006 uct="0.000" uht="0.005" urt="0.005"
INFO:      - "GET /users/me HTTP/1.0" 403 Forbidden
INFO:     [nginx][2024-03-27 15:11:03]  client_ip - - "GET /api/users/me HTTP/1.1" 403 22 "http://server_ip:8091/" "Mozilla/5.0 (X11; Linux x86_64; rv:124.0) Gecko/20100101 Firefox/124.0" rt=0.006 uct="0.000" uht="0.006" urt="0.006"
INFO:      - "GET /stats HTTP/1.0" 200 OK
INFO:     [nginx][2024-03-27 15:11:03]  client_ip - - "GET /api/stats HTTP/1.1" 200 77 "http://server_ip:8091/" "Mozilla/5.0 (X11; Linux x86_64; rv:124.0) Gecko/20100101 Firefox/124.0" rt=0.010 uct="0.000" uht="0.010" urt="0.010"
INFO:     [nginx][2024-03-27 15:11:03]  client_ip - - "GET /assets/platforms/linux.ico HTTP/1.1" 404 125 "http://server_ip:8091/" "Mozilla/5.0 (X11; Linux x86_64; rv:124.0) Gecko/20100101 Firefox/124.0" rt=0.001 uct="-" uht="-" urt="-"

Thanks for looking into this!

**Comment by gantoine** [comment]
Yeah seems the login endpoint 200s, but every request after 404s. Can you try a) in an incognito window, b) in another browser and c) clearing cookies for romm on your main browser? You're specifically looking for two called `session` and `csrftoken`.

**Comment by ethronrion** [comment]
Already tried with an incognito window and also a different browser, as well as incognito in that one as well.
All exhibit the same weird behaviour.
All log in (200s), all seem to load some of the images of the scanned roms, and immediately redirect me to the login screen (403 on api/platforms).


INFO:      - "GET /platforms HTTP/1.0" 403 Forbidden
INFO:     [nginx][2024-03-27 16:22:05]  client_ip - - "GET /api/platforms HTTP/1.1" 403 22 "http://server_ip:8091/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36" rt=0.002 uct="0.000" uht="0.002" urt="0.002"
INFO:      - "GET /users/me HTTP/1.0" 403 Forbidden
INFO:     [nginx][2024-03-27 16:22:05]  client_ip - - "GET /api/users/me HTTP/1.1" 403 22 "http://server_ip:8091/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36" rt=0.002 uct="0.000" uht="0.003" urt="0.003"
INFO:      - "GET /stats HTTP/1.0" 200 OK

Even after cleaning out all cookies related to the server's IP I get the same behaviour of login window - logging in - immediate 403 on some assets, not all, and redirect to login window

**Comment by gantoine** [comment]
can you post your docker compose?

**Comment by ethronrion** [comment]
I don't really have a compose file, due to unraid, but I can share my docker run command from unraid if that's okay:

docker run
  -d
  --name='RomM'
  --net='bridge'
  -e TZ="Europe/Berlin"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="unRAID"
  -e HOST_CONTAINERNAME="RomM"
  -e 'IGDB_CLIENT_ID'='redacted'
  -e 'IGDB_CLIENT_SECRET'='redacted'
  -e 'DB_HOST'='dbhost'
  -e 'DB_PORT'='3306'
  -e 'DB_USER'='romm'
  -e 'DB_NAME'='romm'
  -e 'DB_PASSWD'='redacted'
  -e 'ROMM_AUTH_SECRET'='redacted'
  -e 'ROMM_AUTH_USERNAME'='user'
  -e 'ROMM_AUTH_PASSWORD'='redacted'
  -e 'DISABLE_CSRF_PROTECTION'='true'
  -l net.unraid.docker.managed=dockerman
  -p '8091:8080/tcp'
  -v '/mnt/user/Games/':'/romm':'rw'
  -v '/mnt/user/Games/library/':'/romm/library':'rw'
  -v '/mnt/user/Games/resources':'/romm/resources':'rw'
  -v '/mnt/user/Games/logs/romm':'/romm/logs':'rw'
  -v '/mnt/user/Games/config/':'/romm/config':'rw'
  -v '/mnt/user/Games/assets':'/romm/assets':'rw'
  -v '/mnt/user/Games/romm_redis/':'/redis-data':'rw' 'zurdi15/romm:3.0.1'

I disabled CSRF as that wouldn't even let me log in (in neither browser, nor incognito windows)

**Comment by ethronrion** [comment]
Will do. Thanks for looking at it anyway :)
Will let you know if 3.1 fixes the issue!

**Comment by ethronrion** [comment]
I don't know why, but after redeploying the container it just worked.
I didn't change any of the environment variables, nor did I clear out the persistent data. It just worked with 3.0.3
