### ISSUE TITLE
[Feature] Game notes for Romm

### ISSUE THREAD

**Issue by miltuss** [rommapp/romm#774]
Good morning, 

 I think it would be useful for Romm users to be able to write notes on the page of each game

 It would be really nice to be able to write notes directly in a text editor integrated into Romm. 
  A simple notes field on each page of the games would do the trick, it could even be made up of several note blocks like comments that could be added, edited and deleted.

 notes could be used for various things, like noting down game codes, speedrunning tips... but could also be used to comprehensively note how to install a specific version of a game on Windows or Linux

**Comment by gantoine** [comment]
This is now available in the latest release!
