### ISSUE TITLE
[Feature] PS2 emulation with Play! JS

### ISSUE THREAD

**Issue by miltuss** [rommapp/romm#775]
The Play! emulator emulates the PS2, and works in a similar way to EmulatorJS directly in the https://github.com/jpd002/Play- browser.

Play! requires no additional bios configuration, and works automatically with PS2 romms.

Play! could complement emulator JS in supporting PS2 games in Romm if integrated.

**Comment by ddcash** [comment]
PS2 emulation would be awesome!

**Comment by truevox** [comment]
Wow, yeah - I would love to see PS2 emulation. It's basically the last system (that and Dreamcast) that I feel EmulationJS is missing.

**Comment by gantoine** [comment]
Well I have this a shot over the weekend and, rendering issue aside, the performance on both my M1 Pro and Windows PC leave much to be desired. Play! works well on android and windows as executables, but is severely limited in browser. At this time we're not going to be pursuring this any further, though if someone was to get this past the finish line the branch is [`romm-775`](https://github.com/rommapp/romm/tree/romm-775).

<img width="887" alt="Screenshot 2024-09-22 at 11 14 12 PM" src="https://github.com/user-attachments/assets/358fe6f8-0068-44a0-b7b5-d916ce76e481">
<img width="747" alt="Screenshot 2024-09-22 at 11 18 21 PM" src="https://github.com/user-attachments/assets/44b9734c-d1c4-4f11-936c-d123a38dc373">

**Comment by mdPlusPlus** [comment]
Since September '24 versions 0.67, 0.67-1, 0.68, 0.69, 0.70, 0.71 and 0.72 of Play! have been released. Has anything been done in these releases to address the performance issues? If so, it might be worth to reevaluate the integration.

**Comment by gantoine** [comment]
@mdPlusPlus interested in taking a look at their changelog, or the latest demo to gauge the performance?

**Comment by Seltzer-R** [comment]
@gantoine I tested the latest version with Twisted Metal - Head On and performance was alright.  Definitely fits my definition of playable but had some audio hitching and the typical ps2 rendering bugs but nothing major.  Twisted Metal - Black was unable to render any of the text within the menus but getting in game it ran between 40-60fps depending on what was on screen.  I will test more games later but these two were the only ISO files I had on hand.  Unfortunately, I think its very game dependent with play! as far as end experience

**Comment by Seltzer-R** [comment]
Sticking to games listed as playable this time, I tested RE4, and champions of norrath.  Both stuttered to the point they are pretty much unplayble.  Its getting their... but definitely needs more time in the oven.  Tested on build 0.75
