### ISSUE TITLE
[Other] Add TZ to documented Environment Variables

### ISSUE THREAD

**Issue by ShadowPeo** [rommapp/romm#777]
There is an undocumented Environment Variable of TZ= With Timezone, which defaults to UTC. I know this is pretty much standard now but I feel it should be in the documentation

**Comment by gantoine** [comment]
It's not something we explicitly set in the code, it's possible the underlying image `node:lts-alpine` uses it, but we don't.

**Comment by ShadowPeo** [comment]
No problem, its useful to know either way however as it made it a hell of a lot easier to troubleshoot not to have to constantly convert to/from UTC
