### ISSUE TITLE
[Bug] switch_titledb.json can't be fetched due to permission in backend folder

### ISSUE THREAD

**Issue by TheCyberQuake** [rommapp/romm#783]
**RomM version**
v3.x (whatever the latest that gets pulled using unraid on 4/2/24 using :latest)

**Describe the bug**
When trying to scan my library, my Switch games cause the entire scan to error out on the first game
`[Errno 13] Permission denied: '/backend/handler/fixtures/switch_titledb.json'`

**To Reproduce**
1. Put Switch XCI roms into switch folder
2. Run a scan
3. Error after Fetching the Switch titleDB index file and Scheduled switch titledb update started

**Expected behavior**
Games to scan

**Screenshots**
![image](https://github.com/rommapp/romm/assets/23409605/f8f054e6-7ca3-497f-99ed-69f514778ec0)

**Desktop (please complete the following information):**
 - OS: Kubuntu 22.04
 - Browser Firefox Flatpak
 - Version 124.0.1

**Additional context**
N/A

**Comment by gantoine** [comment]
This is fixed in 3.1.0-rc.1 if you want to try it! There are some migrations notes you'll want to read https://github.com/rommapp/romm/releases/tag/3.1.0-rc.1

**Comment by TheCyberQuake** [comment]
Yep, seems to work!
For the migration notes, the note about removing the volume bound to /romm/logs might need to be more explicit with saying to remove it, as I could not get it to start up properly until I removed it. The current phrasing makes it seems like it isn't required, but unless I just had a fluke it was required for me to get things working.

**Comment by gantoine** [comment]
> the note about removing the volume bound to /romm/logs might need to be more explicit with saying to remove it

thanks, updated the release notes to be more explicit
