### ISSUE TITLE
[Feature] Automatic file management

### ISSUE THREAD

**Issue by adrianipopescu** [rommapp/romm#793]
**Is your feature request related to a problem? Please describe.**
I have a lot of roms that would be ideal to be categorized automatically similar to how arrs treat content

**Describe the solution you'd like**
Automatic renaming and folder structure generation for easy archiving, file browsing, and consumption

**Describe alternatives you've considered**
Tried running regex bashes based on the current path but couldn't get too far without the smart tagging using the data store from Romm

**Additional context**
This could also allow for additional metadata files such as manuals (excluding osts) and even secondary content such as dlcs or patches. Bonus points for having a "dead drop" folder where I can deposit my backups and they can be automatically picked up and relocated and named.

**Comment by adrianipopescu** [comment]
I was reindexing my old games that I manually named when archiving them, and on top of the above, a killer feature would be to have the igdb id in the name so that whenever my nas dies again, it'll be straightforward to readd everything without manual matching.

**Comment by gantoine** [comment]
Closing this as it duplicates the functionally of other tools like https://github.com/emmercm/igir, and we'd never be able to match their level of support/features.
