### ISSUE TITLE
[Feature] Favorite/Recently played games to show on the home screen.

### ISSUE THREAD

**Issue by slimshizn** [rommapp/romm#798]
**Is your feature request related to a problem? Please describe.**
Would like the ability to favorite games in order to quickly get back to them to play.

**Describe the solution you'd like**
Favorites and recently played section on the home screen.

**Describe alternatives you've considered**
None.

**Comment by rareromfish** [comment]
I would like to add to this request, for a filter option for just your favorites when browsing platform libraries. This feature would be enormously helpful for me.

**Comment by gantoine** [comment]
This is now available in the latest release!
