### ISSUE TITLE
[Bug] Unidentified ROMs filter not loading all ROMs in platform

### ISSUE THREAD

**Issue by Casuallynoted** [rommapp/romm#802]
If you go into a platform’s library and filter by unmatched, it only shows stuff that’s been displayed already - it doesn’t seem to show any games past the initial loaded set. Currently experiencing this on both 3.0.3 and 3.1rc2

**Comment by gantoine** [comment]
Seems unmatched filtering (maybe all filtering) is happening on the client, whereas it should be happening on the server.
