### ISSUE TITLE
[Bug] Weird unexpected folder not being excluded

### ISSUE THREAD

**Issue by TheDevilOfJesters** [rommapp/romm#809]
**RomM version**
3.0.3

**Describe the bug**
I have RomM running on my Synology NAS and for some reason there's these '@eaDir' folders that will not be excluded when searching 

**To Reproduce**
save a zip or 7z to a directory you put games
scan for the new games
@eaDir folder exists when it should be getting filtered 

**Expected behavior**
@eaFolder not being seen on frontend 

**Screenshots**
![image](https://github.com/rommapp/romm/assets/39665009/8a543cd1-089b-4db5-a968-89adbfa48a39)
![image](https://github.com/rommapp/romm/assets/39665009/9a904edc-c61b-43a4-9168-6905e2a4b870)

**Additional context**

My config.yml 
    `
    exclude:
      # Exclude platforms to be scanned
      platforms:
      'Rpcs3'
      ' @eaDir'
      '@eaDir'
    
      # Exclude roms or parts of roms to be scanned
      roms:
      ' @eaDir'
      '@eaDir'
        ## Single file games section.
        # Will not apply to files that are in sub-folders (multi-disc roms, games with updates, DLC, patches, etc.)
        single_file:
          # Exclude all files with certain extensions to be scanned
          extensions:
            - 'xml'
          # Exclude matched file names to be scanned
          names:
            - 'info.txt'
            - '._*' # Supports unix filename pattern matching
            - '*.nfo' # Can also exclude files by extension
    
        ## Multi files games section
        # Will apply to files that are in sub-folders (multi-disc roms, games with updates, DLC, patches, etc.)
        multi_file:
          # Exclude matched 'folder' names to be scanned (RomM identifies folders as multi file games) 
          names:
            - 'my_multi_file_game'
            - 'DLC'
            - ' @eaDir'
            - '@eaDir'
          # Exclude files within sub-folders.
          parts:
            # Exclude matched file names to be scanned from multi file roms
            # Keep in mind that RomM doesn't scan folders inside multi files games,
            # so there is no need to exclude folders from inside of multi files games.
            names:
              - 'data.xml'
              - '._*' # Supports unix filename pattern matching
            # Exclude all files with certain extensions to be scanned from multi file roms
            extensions:
              - 'txt'
    
    system:
      # Asociate different platform names to your current file system platform names
      platforms:
        # [your custom platform folder name]: [RomM platform name]
        gc: 'ngc' # In this example if you have a 'gc' folder, RomM will treat it like the 'ngc' folder
        psx: 'ps' # In this example if you have a 'psx' folder, RomM will treat it like the 'ps' folder
      # Asociate one platform to it's main version
      versions:
        naomi: 'arcade'
    
    filesystem:
      # The folder name where your roms are located
      roms_folder: 'library' # For example if your folder structure is /home/user/library/roms_folder
`

**Comment by sondregronas** [comment]
Did you update the path of `config.yml` to `/romm/config/config.yml` (A breaking change from v3) - aka are you able to verify that the config file is loaded?

**Comment by gantoine** [comment]
What sondregronas said, and can you verify that your YAML is in fact valid with an online yaml validator?

**Comment by TheDevilOfJesters** [comment]
hi, my YAML was invalid and I was mounting to the wrong location, it is working now.

Thank you so much I have no idea how I overlooked that I should be binding to a config folder DX it's right in the migration guide
