### ISSUE TITLE
[Feature] Recursive folder scanning

### ISSUE THREAD

**Issue by BobGallardo** [rommapp/romm#813]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add recursive scanning in rom folders.

**Describe alternatives you've considered**
Re-organize some of my platform folders into a flat structure instead of some using additional organization within a platforms rom folder. 

**Additional context**
I have some large rom collections that are organized with subfolders by region. Sometimes it doesn't make sense to have thousands of roms in a single folder.

**Comment by gantoine** [comment]
> Sometimes it doesn't make sense to have thousands of roms in a single folder.

Sometimes the world doesn't make sense 🙂 
Our rigid folder structure allows for easy parsing of multi-file roms. Since there's no standard for rom file organization, mandating a single folder/platform is the best we can do.

**Comment by MightyRufo** [comment]
Folders should be scanned as a "base game folder". And any files within, including sub folders, should be part of that game.
