### ISSUE TITLE
[Feature] Interactive tag buttons on game info pages

### ISSUE THREAD

**Issue by ameturpoet** [rommapp/romm#814]
It would be great once the collections feature is finished that you could click on one of the tag cells (Genre, Franchise, Collection, Company, etc.) or the Remake/Expanded sidebar elements could actually link to the respective game or collection in the RomM database - it feels strange that they're there but cannot be interacted with.

**Comment by CGVakula** [comment]
I will add to the above. 
It would also really like to put a tag on what has been played and what has not been played and if needed, sorted by that tags. Best template how can manage by tags, realised in GOG Galaxy. Something like that would be very useful here.

**Comment by gantoine** [comment]
This is available in the latest release!
