### ISSUE TITLE
[Bug] Copy download link doesn't work

### ISSUE THREAD

**Issue by IvanMazzoli** [rommapp/romm#818]
**RomM version**
RomM 3.1.0-rc.3

**Describe the bug**
When clicking the copy download link button, nothing happens.

**To Reproduce**
1. Go to any game in your library
2. Click on the copy button
3. Try to paste (eg. in a txt file)
4. Nothing has been copied

**Expected behavior**
When clicking the copy button, the download link should be copied to the clipboard. Even better, a small toast with "Download link copied to the clipboard" should be displayed to the user.

**Screenshots**
![image](https://github.com/rommapp/romm/assets/7896815/9928147a-2325-42cb-8597-04ca556ba4bb)

**Desktop:**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 124.0.6367.60 (Official build) (64 bit) (cohort: M124 Rollout) 

**Additional context**
Also tried with Microsoft Edge, can reproduce the issue. Tried with single file ROMs games (eg. NES) and multi file ROMs (eg. PS1) and both produces the same issue.

**Comment by zurdi15** [comment]
To be honest I only tested it in Firefox. Could you test with firefox and post the results?

**Comment by IvanMazzoli** [comment]
I had to switch PC, now I'm on Windows 11 and with Firefox (fresh installation) I still can't copy the download link. Here's the console error message: 
<img width="683" alt="image" src="https://github.com/rommapp/romm/assets/7896815/b36c9e00-152b-4287-b7cb-3cd8fdfbad5e">

**Comment by gantoine** [comment]
lmaooooo i can't believe i didn't see this in the PR 🤦🏼 `navigator.clipboard` is only available in secure contexts (`https` pages), and looking at your screenshots you're accessing it via an ip address.

@zurdi15 you used to be able to use `document.execCommand` as a workaround, but that was deprecated years ago and browsers are finally starting to remove it. i think the best thing is to just hide the button if the context isn't secure (not https web page)

**Comment by IvanMazzoli** [comment]
I don't really like the idea of not being able to just share the link if my connection isn't secure... what about a different approach like Google Photos?
![image](https://github.com/rommapp/romm/assets/7896815/d01390c8-0876-4672-948d-349bfa8741a2)
If a secure context isn't available, just grey out the copy button but allow the user to copy it manually. In this case a better icon for the copy button would be a share one, like _share-variant_.

**Comment by zurdi15** [comment]
> lmaooooo i can't believe i didn't see this in the PR 🤦🏼 `navigator.clipboard` is only available in secure contexts (`https` pages), and looking at your screenshots you're accessing it via an ip address.

wow how is this possible? how could I use `navigator.clipboard` then because ``localhost`` is taken as secure context?

In any case I like the google photos approach, if that method is not available we show a popup with the link to copy it manually

**Comment by gantoine** [comment]
> is it because localhost is taken as secure context?

yes something like that!

> if that method is not available we show a popup with the link to copy it manually

makes sense to me, assigning this to you and backlogging it

**Comment by gantoine** [comment]
This will be available in the next release (3.2.0).

**Comment by noisybagel** [comment]
Has the fix for this been removed from more recent versions of RomM? I can't seem to copy links.

**Comment by Spinnich** [comment]
> Has the fix for this been removed from more recent versions of RomM? I can't seem to copy links.

Are you not using HTTPS to access your server? If you're not using HTTPS, I would expect you'd see an errors like the following in RomM...
- `Couldn't copy to clipboard. This requires a secure (HTTPS) connection.`
- `Clipboard is not available in this context. Select the link below to copy it manually.`
- `Can't copy link to clipboard, copy it manually`

**Comment by noisybagel** [comment]
Correct not on https, however not getting the window prompt option to select the link.

**Comment by Spinnich** [comment]
> Correct not on https, however not getting the window prompt option to select the link.

Hrm, at the end of the day I'm pretty sure the best solution is just going to be getting HTTPS traffic to your instance via a reverse proxy as browsers are just going to continue being more and more hostile to unencrypted connections.

That said, assuming we're talking about the "Copy Download Link" button, you don't get a prompt like this?

<img width="1362" height="698" alt="Image" src="https://github.com/user-attachments/assets/4831dc1d-1718-4065-a38b-42605f2135ff" />

**Comment by noisybagel** [comment]
Yeah, no prompt:

<img width="905" height="551" alt="Image" src="https://github.com/user-attachments/assets/53d7580e-86b1-4d70-b54c-2ed3ca2eed43" />

I'll look into reverse proxy.

EDIT:
Ah, I figured it out. The other copy download link that I wasn't aware of gives you the prompt. This part on the files page doesn't, however. My main thing though, was trying to copy the hashes, which I can't even select as it's abbreviated.

**Comment by Spinnich** [comment]
> Yeah, no prompt:
> 
> <img alt="Image" width="905" height="551" src="https://private-user-images.githubusercontent.com/173446895/630622446-53d7580e-86b1-4d70-b54c-2ed3ca2eed43.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODU3Njc3ODYsIm5iZiI6MTc4NTc2NzQ4NiwicGF0aCI6Ii8xNzM0NDY4OTUvNjMwNjIyNDQ2LTUzZDc1ODBlLTg2YjEtNGQ3MC1iNTRjLTJlZDNjYTJlZWQ0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwODAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDgwM1QxNDMxMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YWIzNjg3NWIxOTJiZDA3OThhYmRlMmVkNTdlODg5MTc4ZjUzNDkxMzYxYTI3NDg2OGM2ODQ4YTQ0YWU3ZGE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZyZXNwb25zZS1jb250ZW50LXR5cGU9aW1hZ2UlMkZwbmcifQ.-qOP6XK8DariWbyYgvSYKFeX0AKDuDUD9YgWzP-_R2k">
> I'll look into reverse proxy.
> 
> EDIT: Ah, I figured it out. The other copy download link that I wasn't aware of gives you the prompt. This part on the files page doesn't, however. My main thing though, was trying to copy the hashes, which I can't even select as it's abbreviated.

Ooooh, so you're talking about copying file hashes. It's the same issue of the clipboard not being available utilizing HTTP, but you're correct that there is no prompt unlike the screen capture I posted above.

I'll bring it up with the team to see how we want to handle this. It might just be "use HTTPS moving forward" or we might make a workaround similar to the "Copy Download Link" button.
