### ISSUE TITLE
[Bug] Bug title

### ISSUE THREAD

**Issue by jackskhakis** [rommapp/romm#827]
**RomM version**
3.1.0

**Describe the bug**
Unable to use coleco emulation in emulatorjs, every game shows 'no bios' full screen.

**To Reproduce**
1. Upload a coleco rom
2. Scan game
3. Attempt to launch in browser

**Expected behavior**
Play the game.

**Screenshots**
![Screenshot (2)](https://github.com/rommapp/romm/assets/124077612/42b36050-62fd-4a6b-8765-d3cce249b09d)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 
 - Version 124.0.6367.63

**Additional context**
I tried adding colecovision.rom to the roms folder also

**Comment by gantoine** [comment]
BIOS support isn't yet available, I wasn't aware colecovision needed bios files. I'm working on this soon so it'll be available once BIOS support ships.
