### ISSUE TITLE
[Feature] Completion checkbox

### ISSUE THREAD

**Issue by CGVakula** [rommapp/romm#829]
It would really like to put a the checkbox on what has been played. And after that sorted what has not been played and if needed, sorted by that tags. Best template how can manage by tags, by my opinion, realised in GOG Galaxy. Something like that would be very useful here.
This will greatly help you navigate the list of failed and completed games.

I think the checkbox could be looks like that:
![2024-04-30_15-52-04](https://github.com/rommapp/romm/assets/133823294/a332d049-08b9-4080-8aa1-fc56df6b564f)
![table](https://github.com/rommapp/romm/assets/133823294/8f5d7c0a-f7a5-46cd-a0e1-79b6d6f33718)

**Comment by gantoine** [comment]
Closed as complete
