### ISSUE TITLE
[Feature] Add support for localization

### ISSUE THREAD

**Issue by IvanMazzoli** [rommapp/romm#831]
**Is your feature request related to a problem? Please describe.**
English is for sure one of the most spoken languages around the world, but adding localization support for multiple languages would be a nice feature.
There are already a ton of strings in the project and starting now will ease the addition and translation of new strings in the next updates.

**Describe the solution you'd like**
Export all the hardcoded (are they?) strings in an XML/other type of file or use an online tool like [Crowdin](https://crowdin.com/) to allow contributors to add their native language to the project. Every user should be also allowed to choose their preferred language. If a string is not translated, it should fall back to the english one.

**Describe alternatives you've considered**
A good english course for the ones who doesn't speak it!

**Additional context**
I would be happy to help with the Italian translation for the project, as I recently did for EmulatorJS.

**Comment by Nazgile94** [comment]
any way to change the language of igdb

it pulls the descriptions and data in english - not as bad, but having it in other languages , spanish, german ... etc would be nice to setup

and UI language change :-)

**Comment by gantoine** [comment]
This will be available in the next release!
