### ISSUE TITLE
[Bug] ROM Names/Titles that contain an ampersand result in a missing file when downloading

### ISSUE THREAD

**Issue by Zadeis** [rommapp/romm#833]
**RomM version**
3.1.0

**Describe the bug**
Just as the title states. When downloading any rom/file that contains an ampersand (&) in it results in a file not found/server error. This happens in both Firefox and a chromium based browser (thorium in my case).

**To Reproduce**
1. Go to a rom with an '&' in the file name.
2. Click on download.

**Expected behavior**
I would expect the file to download with out issue.

**Desktop (please complete the following information):**
 - OS: Android, Linux or Windows
 - Browser Firefox or Chromium based browser
 - Latest Releases of browsers mentioned

**Smartphone (please complete the following information):**
 - Device: Galaxy Fold5
 - OS: Android 14, OneUI 6.1
 - Browser: Firefox or Chromite
 - Latest Releases

**Additional context**
My apologies if this has been reported already. I searched around and found a similar bug report referring to commas but not ampersands.

**Comment by gantoine** [comment]
Will be fixed in the next release
