### ISSUE TITLE
Image not updated

### ISSUE THREAD

**Issue by Dreadlocke12** [rommapp/romm#839]
**RomM version**
3.1.0

**Describe the bug**
I have scanned the firet Final Fantasy Romm from NES and for some reason it believes it is Final Fantasy ++ which seems to be a remake from 2007. If i search for other suggestion and select the correct one all information is getting updated beside the image. If i remove the image and then select the correct entry it is still showing Final Fantasy ++ as image.
**To Reproduce**
1. Go to Edit → Delete Cover
2. Click on Manual Search
3. Non Cover will be replaced by the wrong image

**Expected behavior**
Correct image should be updated

**Screenshots**
![Screenshot_20240505-143910_1](https://github.com/rommapp/romm/assets/56894437/e954c413-0c0b-42d9-bb71-4ab297a08552)
![Screenshot_20240505-143927_1](https://github.com/rommapp/romm/assets/56894437/840fd079-1093-4781-ba43-139dfa552808)

**Smartphone (please complete the following information):**
 - Device: Fairphone 4
 - OS: Android 13
 - Browser Firefox
 - Version: 125.3.0 (Build #2016017559)

**Comment by Dreadlocke12** [comment]
![Screenshot_20240505-143910_1](https://github.com/rommapp/romm/assets/56894437/e954c413-0c0b-42d9-bb71-4ab297a08552)
![Screenshot_20240505-143927_1](https://github.com/rommapp/romm/assets/56894437/840fd079-1093-4781-ba43-139dfa552808)

**Comment by zurdi15** [comment]
Hi! Did you try to refresh the page?

**Comment by Dreadlocke12** [comment]
I fixed it now. Refreshing the page did not work but clearing the cookies.
