### ISSUE TITLE
[Bug] Scan not adding new roms?

### ISSUE THREAD

**Issue by karl0ss** [rommapp/romm#841]
**RomM version**
3.1.0

**Describe the bug**
Upgraded from working 2.x install, Have added some new games, but nothing was found during the cron scan, manually kicked off a scan in the ui, but nothing seems to scan in, also doesn't appear to be anything in the logs related to it

**To Reproduce**
Try to scan new roms for platform
Never finishes and just keeps scanning

**Expected behavior**
Scan in new roms?

**Screenshots**
![image](https://github.com/rommapp/romm/assets/2493260/3ce70272-9d19-40ea-9d64-269b1014c875)

**Desktop (please complete the following information):**
Offical Docker Image

**Smartphone (please complete the following information):**
Chrome on Windows 11

**Comment by karl0ss** [comment]
Chome debug console seems to be spamed with 
![image](https://github.com/rommapp/romm/assets/2493260/1a4e2502-14bd-46af-b78d-24994eb9e521)

**Comment by zurdi15** [comment]
Hi! can you post the container logs?

**Comment by karl0ss** [comment]
How can i force the logs? i just wiped all the logs from my logs folder, restarted and did the process again, but it hasn't written anything to the log files?

**Comment by karl0ss** [comment]
[portainerlogs.txt](https://github.com/rommapp/romm/files/15246500/portainerlogs.txt)

Ive attached the portainer logs from the restart/process

**Comment by zurdi15** [comment]
could you share the logs when you perform a scan?

**Comment by karl0ss** [comment]
I have performed a scan during the period of the logs.....

I will try again and see if I can capture anything else....

This has been working fine - 
![image](https://github.com/rommapp/romm/assets/2493260/eedeb411-9429-42dc-8370-767e50d5bafd)

**Comment by zurdi15** [comment]
Oh damn sorry, you are totally right, i'm totally blidn. There are the scan socket petitions but with a status code 400. Can you try cleaning cache/cookies and try to scan again? Seems like something could be got stuck from the 2.x version

**Comment by WalterSchirmacher** [comment]
I had an issue recently where scanning was starting but never finishing (it just kept scanning but never finding anything). I shut down RomM, deleted the redis backup file "dump.rdb", then restarted RomM, and this solved the problem.

**Comment by karl0ss** [comment]
Nginx proxy manager wasn't set to allow web sockets, having enabled that, all is working..

**Comment by DarSin1** [comment]
> Nginx proxy manager wasn't set to allow web sockets, having enabled that, all is working..

This was exactly my issue as well. Adding websockets in nginx fixed the scanning and adding roms.
