### ISSUE TITLE
[Bug] Android Chrome not loading more than 60 entries

### ISSUE THREAD

**Issue by sergiohf** [rommapp/romm#853]
**RomM version**
Romm 3.1.0 - Docker - Big Bear Romm

**Describe the bug**
Using romm via mobile phone ( Chrome for Android), every system only shows 60 games and do not load any more games. If i filter by name, other games are shown, but only the 60 first games. The game loading works in Chrome for Windows, so it is a mobile issue

**To Reproduce**
1. Open romm via mobile phone on Chrome or any other browser (tested also in dolphin)
2. Click on any plataform with more than 60 games
3. When scroll down, the list stops loading in 60 games. If i change view to list, you can see that only 60 games are loaded but you cant navigate or load more games

**Expected behavior**
Loading more than 60 games

**Screenshots**
![Screenshot_2024-05-18-11-13-49-659_com android chrome](https://github.com/rommapp/romm/assets/59039520/59c8b072-07ea-48ed-b8ae-1b8a443d275f)

**Smartphone (please complete the following information):**
 - Device: Poco F4
 - OS: Android 14
 - Browser Chrome
 - Version 125.0.642252

**Additional context**
The log on CasaOS shows (ommited personal information):
big-bear-romm    | INFO:	  [nginx][2024-05-18 14:14:58]	xxx.xx.0.1 - - "GET /api/heartbeat HTTP/1.1" 200 562 "<host>/platform/6" "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Mobile Safari/537.36" rt=0.595 uct="0.000" uht="0.596" urt="0.596"
big-bear-romm    | INFO:	  [nginx][2024-05-18 14:14:58]	xxx.xx.0.1 - - "GET /api/roms?platform_id=6&size=60&cursor=&search_term=&order_by=name&order_dir=asc HTTP/1.1" 200 225150 ""<host>/platform/6" "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Mobile Safari/537.36" rt=0.173 uct="0.000" uht="0.172" urt="0.174"

**Comment by gantoine** [comment]
Easy 10s fix for this would be to add a "Load more" button at the bottom. So if the page doesn't auto-load, the user can click the button.

HOWEVER, now that fetching roms basically runs in linear time, if we can fix rendering on the gallery view, maybe we can just fetch **all games** for a platform and render them? 👀

**Comment by sergiohf** [comment]
I have updated to version 3.20 and now is working fine.
