### ISSUE TITLE
[Bug] Error during scheduled scan

### ISSUE THREAD

**Issue by Druidblack** [rommapp/romm#860]
**RomM version**
3.2.0-rc.1

**Describe the bug**
During the scheduled scan, I do not start scanning with a complete check of all platforms, but for some reason from a specific platform "Neo Geo CD" and it ends with the error "Task exceeded maximum timeout value (180 seconds)". If I start the scan manually with "Quick scan", then the scan starts normally and goes on all platforms.

Log https://controlc.com/cd6505be

**Expected behavior**

**Screenshots**
![Безымянный](https://github.com/rommapp/romm/assets/70659424/d1332c3e-e071-4815-b069-7646faf58f12)

**Comment by Druidblack** [comment]
I did not set the SCAN_TIMEOUT parameter in my settings.

**Comment by Druidblack** [comment]
![Безымянный](https://github.com/rommapp/romm/assets/70659424/ffae5531-2f50-48a4-8ca4-d2b1dc2cf34d)
In version 3.1.0, when scanning with frequency settings. The scan does not start, and if you run the scan manually, nothing happens. In the logs, he writes that the scan has started, nothing else happens.
My game folders are mounted over the network.


Without the option of periodic scanning, manual scanning is started normally. If I didn't describe it clearly, then I can make a video about how it happens.

**Comment by gantoine** [comment]
>  My game folders are mounted over the network.

We should support this, but it could be causing an issue. So to recap, nightly scans don't work/run, and manual scans end immediately, with no errors in the logs?
