### ISSUE TITLE
[Bug] No content is shown, 502 Bad Gateway in dev console

### ISSUE THREAD

**Issue by IvanMazzoli** [rommapp/romm#864]
**RomM version**
[v3.2.0-rc.1](https://github.com/rommapp/romm/releases/tag/3.2.0-rc.1)

**Describe the bug**
Out of the blue, Romm stopped working. It shows as if it was just installed, empty, and the developer console of the browser displays a lot of 502 errors. The container console doesn't show any error.

**To Reproduce**
That's unknow. After updating to 3.2.0-rc.1 it worked fine for a couple of days. No clue what happened, but now it's in this state.

**Expected behavior**
Be able to see my content 😉.

**Screenshots**
![image](https://github.com/rommapp/romm/assets/7896815/3e3dbbac-a855-4d45-ad7d-d15cc8d9801e)
I have also already set a user picture, as you can see, it's not shown.

![image](https://github.com/rommapp/romm/assets/7896815/9d6f4245-948a-4f96-9bbc-5e9c39e3d870)

**Desktop:**
 - OS: Windows 10
 - Browser Chrome/Firefox
 - Version 124.0.6367.208/125.0.3

**Additional context**
Running in HTTP, not HTTPS. Also tried with a PC in the same network and the problem still occours.

**Comment by gantoine** [comment]
Post the docker container logs

**Comment by gantoine** [comment]
> *8 connect() to unix:/tmp/gunicorn.sock failed (111: Connection refused) while connecting to upstream

Try switching to the latest RC, 3.2.0-rc.1 (or wait a day for the next RC to drop)

**Comment by IvanMazzoli** [comment]
Yeah, I'm already on rc1.
I'll wait for the next rc and keep you guys updated

**Comment by IvanMazzoli** [comment]
RC2 seems to have fixed the issue, thanks again for your work!
