### ISSUE TITLE
How to change arcade‘s core

### ISSUE THREAD

**Issue by vincywindy** [rommapp/romm#873]
![image](https://github.com/rommapp/romm/assets/30209724/49801039-7259-499b-a3d8-45d02975bca1)
emulatorjs has 3 types of core to select. romm use MAME2003 Core as default but it is not support custom bios now, and fba support it.
![image](https://github.com/rommapp/romm/assets/30209724/282a2ad0-4e6f-4160-9870-8f70c5981e0e)

**Comment by gantoine** [comment]
No way to select the core right now, but we can add an selector in the UI when you go to play.

**Comment by gantoine** [comment]
This has been added in the latest release.
