### ISSUE TITLE
[Bug] Game and Watch Platform might use the wrong database url

### ISSUE THREAD

**Issue by green-scorch** [rommapp/romm#877]
**RomM version**
3.1.0

**Describe the bug**
Game and Watch games do not get detected.
I guess it looks up the wrong url since the [Supported Platforms](https://github.com/rommapp/romm/wiki/Supported-Platforms) also link to [https://www.igdb.com/platforms/game-and-watch](https://www.igdb.com/platforms/game-and-watch) 
but the url needs to be [https://www.igdb.com/platforms/g-and-w](https://www.igdb.com/platforms/g-and-w)

I didn't find any settings to change it manually so maybe you might add it as a feature in the future?
Or it is already included and I didn't find it.

Best regards and thank you for your hard work and awesome repo!

**Comment by zurdi15** [comment]
Seems like IGDB changed the Game and Watch slug. I'll update the wiki but in any case you need to change your folder name of bind it to ``g-and-w`` throught the config
