### ISSUE TITLE
[Bug] Custom hi-res cover are still low-res.

### ISSUE THREAD

**Issue by DarkSuperT** [rommapp/romm#881]
**RomM version**
3.1.0 and 3.2.0-rc.3

**Describe the bug**
When uploading a hi-res custom cover, it still default to the basic 264x352 resolution, making it even worse than the native 264x352 cover.

**To Reproduce**
1. Upload a hi-res cover.
2. Watch it become all aliased
3. You can even download the new one to see it's still low-res

**Expected behavior**
Displaying a nice and crisp cover.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge + Chrome

**Additional context**
As we discussed about it on Discord, I'm creating this issue here so you can backlog it ! :)

**Comment by gantoine** [comment]
This will be fixed in the next release!
