### ISSUE TITLE
[Bug] Titles boot to retroarch

### ISSUE THREAD

**Issue by jackskhakis** [rommapp/romm#886]
**RomM version**
3.20-rc.4

**Describe the bug**
When attempting to boot a segacd game after uploading a bios, emulatorjs will load all the way then display a retroarch page with the core listed. also would like ability to choose fbneo for arcade as it defaults to mame2003

**To Reproduce**
Add a rom to segacd, scan, upload bios, launch.
Upload certain roms to arcade, scan, launch.

**Expected behavior**
Expect games to launch in correct core

**Screenshots**
![Screenshot (3)](https://github.com/rommapp/romm/assets/124077612/943f5eaa-3e41-47d9-8322-ebc836d0e5ca)

![Screenshot (5)](https://github.com/rommapp/romm/assets/124077612/a134d339-087d-40b5-a8ba-e6a60f3646c3)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 125

**Additional context**

**Comment by jackskhakis** [comment]
Update on this issue, it seems to only be when trying to launch from the platform list, as it doesnt offer the bios files in the drop down menu. launching via the game's page allows you to pick the bios and launches the game correctly
![Screenshot (6)](https://github.com/rommapp/romm/assets/124077612/7a7ba3c0-86d5-424f-90a9-60eef89a4ed5)

**Comment by gantoine** [comment]
Thanks for the update! Found the bug, and I'll have a fix included in the next release. #891
