### ISSUE TITLE
[Bug] New version available, but it's older than the one in use

### ISSUE THREAD

**Issue by IvanMazzoli** [rommapp/romm#888]
**RomM version**
3.2.0-rc.4

**Describe the bug**
When running the latest release, 3.2.0-rc.4, it says that a new version is available to download, version 3.1.0.

**To Reproduce**
1. Login and see bottom left of the page.

**Expected behavior**
It shouldn't warn me that a new version is available if the one in use it's newer than the one suggested.

**Screenshots**
![image](https://github.com/rommapp/romm/assets/7896815/d5a56591-a223-49f7-b288-6fd128e44142)

**Desktop (please complete the following information):**
Doesn't matter

**Smartphone (please complete the following information):**
Doesn't matter

**Additional context**
Nothing to add.

**Comment by gantoine** [comment]
`3.2.0-rc.4` is not the latest release, it's a release candidate meant for our beta testers and users who love to _live on the edge_. The [latest release](https://github.com/rommapp/romm/releases/latest) (at the current time) resolves to `3.1.0`. We don't do any semantic comparisons on the UI for such a small thing, just a string compare.
