### ISSUE TITLE
Add Ruffle  flash emulator

### ISSUE THREAD

**Issue by monkeyx-net** [rommapp/romm#889]
Would you consider adding the ruffle flash emulator. It has a web component so can integrate into the browser.

https://github.com/ruffle-rs/ruffle/?tab=readme-ov-file#web-or-extension

Another member on discord mentioned that integrating the Flashpoint API would also be needed

https://github.com/FlashpointProject/flashpoint-database

If I can help in anyway with this addition then please let me know.

**Comment by gantoine** [comment]
This will be available in the next release!

**Comment by monkeyx-net** [comment]
Great news
