### ISSUE TITLE
[Feature] Interactive Table of Contents in the README

### ISSUE THREAD

**Issue by Nicmorris1820** [rommapp/romm#890]
**Is your feature request related to a problem? Please describe.**
Navigating the README can be overwhelming for some users who are looking for a specific element.

**Describe the solution you'd like**
An interactive table of contents keeps users from leaving the repository because they get frustrated trying to find information.  User retention is good for development purposes.  Each new user is a potential contributor.

**Describe alternatives you've considered**
There really is no alternative to fixing this issue. 

**Additional context**
A table of content in the style I propose
<img width="860" alt="Screen Shot 2024-05-22 at 8 12 33 PM" src="https://github.com/rommapp/romm/assets/102493952/7aff62f2-4f9e-41a9-8d45-5c74c5b6909f">

**Comment by gantoine** [comment]
Love this idea, would you be keen to make this change against the current `master` branch?

**Comment by Nicmorris1820** [comment]
Yes I can do this! Sorry been busy with school and I have work tonight, give me a couple of days and I can do it!
