### ISSUE TITLE
[Bug] gamepad usb not recognized

### ISSUE THREAD

**Issue by lokomass** [rommapp/romm#897]
Hi
In the emulator, gamepad is not détected, but its works on demo.emulatorjs.org
Whats Im doing wrong ?
Thanks

**Comment by gantoine** [comment]
Hmm not sure, we don't do anything special with emulatorjs. Let me try with a gamepad tonight on my macbook. What browser and OS are you using?

**Comment by lokomass** [comment]
Windows 10 pro , FF 115

**Comment by lokomass** [comment]
I think I found why.
If I test whit my http local address, this is not work.
But if I test with my external dns https, its works !

**Comment by gantoine** [comment]
Cool so it seems it needs a secure context (HTTPS) to accept gamepad input. Might be something specific to FF, might be emulatorjs. Either way this is resolved, and if someone comes across it they know how to fix it now.

**Comment by lokomass** [comment]
now, I just need to understand the database errors, but I'm lost :(
