### ISSUE TITLE
[Bug] Some titles are duplicated as they are identified twice from different files.

### ISSUE THREAD

**Issue by Filipe-Souza** [rommapp/romm#903]
**RomM version**
3.1.0

**Describe the bug**
Some titles are duplicated as they are identified twice from different files (for example emulator saves file types, input log from RetroArch).

**To Reproduce**
1. Create your roms directory and play with one or more roms within the directory.
2. Create a savestate.
3. Perform a "Complete rescan" on the library

**Expected behavior**
Save states and other emulator specific files should be not treated as library items, since they cannot be played was proper roms files.

**Screenshots**
![Captura de tela 2024-05-31 094106](https://github.com/rommapp/romm/assets/5497281/eeda4279-cb62-4b41-af9d-89033454ef1f)
![Captura de tela 2024-05-31 094159](https://github.com/rommapp/romm/assets/5497281/7cdf2aaf-be13-470b-ab6b-8d5891b5cc52)
![Captura de tela 2024-05-31 094355](https://github.com/rommapp/romm/assets/5497281/677c392d-cedc-475e-9860-97aeb56df858)
![Captura de tela 2024-05-31 100058](https://github.com/rommapp/romm/assets/5497281/f922404e-5519-4965-a8e7-47eb5d1626fc)

**Desktop (please complete the following information):**
 - OS: Debian GNU/Linux 12 (bookworm) 
 - Browser Microsoft Edge 
 - Version Version 125.0.2535.67 (Official build) (64-bit)

**Comment by zurdi15** [comment]
RomM doesn't care about which extension the files have, so it won't decide if something is a game or not. In this case, if you want to keep this structure you will need to exclude those files through the [config file](https://github.com/rommapp/romm/blob/release/examples/config.example.yml) and perform a quick scan to remove them from the gallery

**Comment by gantoine** [comment]
You can also move them into a folder, so they'll be marked as mutli-file roms. This way you can always download them from the UI:
- Mario Kart DS (U) (SCZ)
  - Mario Kart DS (U) (SCZ).dsv
  - Mario Kart DS (U) (SCZ).nds
