### ISSUE TITLE
[Bug] "New version available" link opens to a 404

### ISSUE THREAD

**Issue by Urkaz** [rommapp/romm#909]
**RomM version**
v3.1.0

**Describe the bug**
Pressing on the "See what's new!" on this notification:
![image](https://github.com/rommapp/romm/assets/521864/02f5b22c-51aa-429c-bd1e-05c8c0ddb396)
opens the URL
https://github.com/rommapp/romm/releases/tag/v3.2.0
which is invalid and results in a 404 error page by GitHub. I've seen this bug in older versions, and the problem is caused by the tag name, being "v3.2.0" on the URL opened but "3.2.0" on the releases page:
https://github.com/rommapp/romm/releases/tag/3.2.0

**To Reproduce**
1. Press the "See what's new!" when a new version is available.

**Expected behavior**
The link should open a valid page.

**Comment by gantoine** [comment]
Hah funny enough we just fixed this on 3.2.0, so when 3.3.0 comes up it'll work properly. Thanks for letting us know!
