### ISSUE TITLE
[Bug] Update Tag Still there after updating

### ISSUE THREAD

**Issue by Deekerman** [rommapp/romm#910]
**RomM version**
3.2.0

**Describe the bug**
![image](https://github.com/rommapp/romm/assets/33733383/3bb070e1-4997-4288-951b-af84b9dfa5ef)

**To Reproduce**
update then go to site

**Expected behavior**
not get told to update to what i am currently on

**Screenshots**
again 
![image](https://github.com/rommapp/romm/assets/33733383/065da574-6aa3-4340-89f8-5a26faf8832a)

**Comment by gantoine** [comment]
This will be fixed in the next release!
