### ISSUE TITLE
[Feature] Multi-platform games grouping

### ISSUE THREAD

**Issue by krin-san** [rommapp/romm#913]
**Is your feature request related to a problem? Please describe.**
When game has been released on multiple platforms, it'll be nice to have a way to group or link to game roms from other platforms on the `/rom/...` page. !532 (in v2.2.1) allows grouping multi-region/-language roms but it only works per platform.

Here's an example for the game [Ms. Pac-Man](https://www.mobygames.com/game/576/ms-pac-man/) which has been release on dozens of platforms. Romm Search screen find all versions by game title:
<img width="1037" alt="Screenshot 2024-05-27 at 11 07 30" src="https://github.com/rommapp/romm/assets/2318002/33e4f1e4-12f2-49ff-9f91-f0f8ec7d971e">
but Rom pages only list versions from the same platform:
<img width="365" alt="Screenshot 2024-05-27 at 11 11 52" src="https://github.com/rommapp/romm/assets/2318002/24fe30b4-2dcf-4f09-a80e-73a09e52b15f"> <img width="365" alt="Screenshot 2024-05-27 at 11 12 01" src="https://github.com/rommapp/romm/assets/2318002/c605441b-f666-4971-9112-cf98e723b5cb">

**Describe the solution you'd like**
Use IGDB "Ports" or MobyGames "Releases" info to cross-reference releases of the same game on different platforms. This info can be used to link games in UI in at least 2 ways:
1. Put other game releases below the game cover art, in the same section where non-interactible "remake" and "expanded" covers appear
<img width="290" alt="Screenshot 2024-06-01 at 20 17 15" src="https://github.com/rommapp/romm/assets/2318002/eefa6591-7711-4e79-855e-abbeefc56b96">

2. Put other releases into the "Version" drop down, like on the image below
<img width="189" alt="Screenshot 2024-06-01 at 19 56 23" src="https://github.com/rommapp/romm/assets/2318002/eeb5188d-e5da-477f-82e0-427ecf5d918c">

**Comment by gantoine** [comment]
This is now possible with Collections, and we're likely not going to implement this idea seeing as it overlaps with collections.

**Comment by adrianipopescu** [comment]
Sorry to reopen this but while I do understand that collections are a workaround, they do not fundamentally represent the same request: showing one game in all views and perhaps even inside collections while also it meta representing multiple roms and exposing the correct one based on the view.

Ex: If I browse foe spectrum zx games or amiga, I first see selected / can interact with the contextually correct one, while also allowing for per-console support of various revisions, all aggregated, but distinct.

This can also tie into a potential dlc or expansion disk view for consoles like xbox360 or ps3.

Overall I feel that collections in its expression favors an arbitrary grouping based on subjective preferences whereas this is a more fundamental objective grouping.
