### ISSUE TITLE
[Bug] Using the Manual Search function to get metadata while on list view returns user to first page.

### ISSUE THREAD

**Issue by JJAHAX2** [rommapp/romm#915]
**RomM version**
3.2.0

**Describe the bug**
While using the manual search function to get metadata for a game while on list view will send you back the first page of the list after choosing an option.

**To Reproduce**
1. Go to any platform with more than one page of roms.
2. Click on change view button
3. Go to any page after page 1.
3. Click "Manual Search" and pick any title to get metadata from.
4. You will now be back at page 1

**Expected behavior**
After choosing a game to grab metadata from it should return you to where you were previously.

**Comment by gantoine** [comment]
This will be fixed in the next release.
