### ISSUE TITLE
[Bug] Changed, removed or new game files does not get updated

### ISSUE THREAD

**Issue by philipjholm** [rommapp/romm#917]
**RomM version**
v3.2.0

**Describe the bug**
Not sure if this is a bug or should be a feature request. If a already added game gets changed, let's say the files in the folder are renamed or removed the files don't get updated in the next scan. They are still shown on the game details page. Also, removing a whole game folder completely does not remove it from the ROMM library.

**To Reproduce**
Here is a example.
1. Make a folder called "Doom" and place its file it, for example "Doom_v1.zip". Let ROMM scan it and add to library.
2. Change name of file to "Doom_v2.zip".
3. Do a re-scan.
4. The file is still called "Doom_v1.zip" and can't be downloaded.

**Expected behavior**
If files in a games folder gets updated they should be updated periodically

**Comment by gantoine** [comment]
Thanks for bringing this up! This has actually been addressed in unrelated work centered around hash calculations for rom files (SH1/CRC), so it will be fixed in the next release.

**Comment by gantoine** [comment]
Wanted to give you a quick update: this fix won't be in the next release (3.3.0) since the work they're embedded into is being delayed a bit. It will be available in 3.4.0. Since the work itself is done, I'm going to close this issue for now.

**Comment by philipjholm** [comment]
Fantastic news nonetheless! Thanks a lot for your dedication.
