### ISSUE TITLE
[Bug] EmulatorJS N64 Not supporting all cores.

### ISSUE THREAD

**Issue by Zestiality** [rommapp/romm#918]
**RomM version**
Version of RomM you are using
3.2.0

**Describe the bug**
Romm Currently only supports one core for the N64 "[mupen64plus_next](https://emulatorjs.org/docs/systems/nintendo-64)"
but ive been told by the Owner of Emulatorjs that it also supports [parallel-n64](https://emulatorjs.org/docs/systems/nintendo-64)
with most of the games i run on n64 they either crash 10-15 mins in or crash via mainmenu.

**To Reproduce**
1. Open Romm 
2. Find and play any N64 rom you own.
3. See errors happen live.

**Expected behavior**
an option to pick between cores like the psx has "which may fix many issues for n64 i or others currently have "

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 11]
 - Browser [Thorium - Chromium Based Browser]
 - Version [124.0.6367.218] 

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by gantoine** [comment]
This will be fixed in the next release.
