### ISSUE TITLE
[Bug] Platform Version Icon issue

### ISSUE THREAD

**Issue by Konscription** [rommapp/romm#919]
**RomM version**
Version 3.2.0

**Describe the bug**
I set up a platforms versions linking a gba-videos to gba. the icon shows gba on the control panel > config. the bug is that the icon in the library for that platform is a default icon instead of the gba icon.

**To Reproduce**
1. Go to control panel > config. 
2. Click on Gear to allow for adding to the Platforms Versions section
3. Click on ADD
4. under Platform Versions set gba-videos
5. under Main platform set gba
6. confirm
7. have a rom in gba-videos/roms folder
8. scan
9. in the library a default icon shows.

**Expected behavior**
expect to see Main platform icon used for different platform versions.

**Screenshots**
config page:
![image](https://github.com/rommapp/romm/assets/1774045/48263ee0-0fc0-449c-820d-b8c223d7ce01)

platforms:
![image](https://github.com/rommapp/romm/assets/1774045/7f5913cb-e48c-4346-a0cd-67269d434abe)

sidebar:
![image](https://github.com/rommapp/romm/assets/1774045/ca69859f-4f2b-44e9-a929-ec592bfa50f4)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave browser
 - Version: 1.66.118

**Smartphone (please complete the following information):**
 - Device: Samsung Z Fold 4
 - OS: Android 14
 - Browser Brave
 - Version 1.66.118

**Comment by gantoine** [comment]
This will be fixed in the next release.
