### ISSUE TITLE
[Feature] Store multiples revisions of the same game in one folder

### ISSUE THREAD

**Issue by ConnerWithAnE** [rommapp/romm#921]
I have multiple versions of Pokemon Ruby, the original and two revisions. There is a drop down to select between different versions when I select one but when I look at all games for the platform there are multiples. It would be nice if there could be a general "Pokemon Ruby" folder which could hold all three, then there wouldn't be the issue of multiples.

**Comment by zurdi15** [comment]
Hi! You have an option to group the same game into one to have just one entry in the control panel!

**Comment by ConnerWithAnE** [comment]
Oh awesome thank you! It was set by default but did not reflect for some reason! Would be awesome if some of this stuff was in the wiki or the website, just a walkthrough of all the stuff!
