### ISSUE TITLE
[Feature] Move from Redis to Valkey

### ISSUE THREAD

**Issue by Morethanevil** [rommapp/romm#925]
Since Redis changed license it would be awesome to use [Valkey](https://github.com/valkey-io/valkey) instead. It is fully compatible because it is a fork from the last really open source version of Redis 7.2.4

**Comment by gantoine** [comment]
I'm all for this, but since the license change doesn't affect us (yet), it's low priority at the moment. Anyone who wants to avoid redis can run their own valkey container and point romm to it with the env variables.

**Comment by Morethanevil** [comment]
As you said, anyone can run their own container, you don't even need to set other env. It is a dropin replacement. Only replace `image: redis:alpine` with `image: valkey/valkey:alpine` this is all it needs 😃

**Comment by adamantike** [comment]
We will wait for all the upstream Docker images we use to support Alpine 3.20, and then replace the bundled Redis installation with Valkey.

**Comment by adamantike** [comment]
Next version will run a bundled Valkey server, if running without an external Redis/Valkey provided by the REDIS_HOST environment variable!
