### ISSUE TITLE
[Feature] Add additional links to ROM page

### ISSUE THREAD

**Issue by zodac** [rommapp/romm#930]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to include additional links for some ROMs. For example, if the game is supported, I'd like to be able to add a link to the game's entry in RetroAchievements, so I can view it all in one place.

**Describe the solution you'd like**
Ideally, I'd love to be able to put this in a file next to the ROM, rather than having it be manually entered through the UI. (I think there was some talk of using metadata files for ROM scanning in future? But happy for it to be available in any way if that's too much work.

**Describe alternatives you've considered**
Not have the link. :)

**Comment by gantoine** [comment]
There's a note section added in 3.2.0, you can add your links to that note and style them with markdown any way you want.

**Comment by gantoine** [comment]
> I'd like to be able to add a link to the game's entry in RetroAchievements

RetroAchivement support will come in it's own time, but it'll be integrated directly via the RA API.
