### ISSUE TITLE
[Bug] Loading a PSP game it gets stuck on decompress game core

### ISSUE THREAD

**Issue by Vylooo** [rommapp/romm#935]
RomM 3.2.0
Version of RomM you are using

**Loading a PSP game it gets stuck on decompress game core**

**To Reproduce**
1. Find a PSP game.
2. Start Emulation
3. Stare at screen that says decompress game core

The game to load and work

![image](https://github.com/rommapp/romm/assets/35816401/e8f6b70d-025d-4ef0-9860-8cc26903a703)

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser Edge

**Comment by gantoine** [comment]
Any errors in the browser developer console or the docker container logs?

**Comment by Vylooo** [comment]
![image](https://github.com/rommapp/romm/assets/35816401/8e5e0b33-2a62-42bb-a3a0-bfbf1b04bf94)

**Comment by gantoine** [comment]
No errors from what I can see. Are you trying to play with or without a PSP bios selected?

**Comment by UnhealthyKraken** [comment]
I just tried a PSP game myself and also have the same problem.

The only error is in the console is about a image file not being found

> GET http://192.168.1.245:8110/assets/emulatorjs/loading_black.png 404 (Not Found)

It doesnt matter how long you leave the page open, it never seems to get past "Decompress Game Core"

**Comment by Vylooo** [comment]
> I just tried a PSP game myself and also have the same problem.
> 
> The only error is in the console is about a image file not being found
> 
> > GET http://192.168.1.245:8110/assets/emulatorjs/loading_black.png 404 (Not Found)
> 
> The result is the same whether or not I select a bios file.
> 
> The file format is .cso, not sure if that is the issue or not
> 
> It doesnt matter how long you leave the page open, it never seems to get past "Decompress Game Core"

Same result.

**Comment by zerojay** [comment]
Pretty sure PSP isn't currently a supported platform, at least according to emulatorjs.

**Comment by gantoine** [comment]
> Pretty sure PSP isn't currently a supported platform, at least according to emulatorjs.

Looks like you're right, we'll disable it in the next update.

**Comment by Budlyte** [comment]
Can you update the Wiki too please?  It currently lists Playstation Portable as supported.

https://github.com/rommapp/romm/wiki/EmulatorJS-Player#supported-systems
