### ISSUE TITLE
[Bug] Profile image and app icon sometimes produce a 404

### ISSUE THREAD

**Issue by Casuallynoted** [rommapp/romm#944]
Sometimes, the app icon (in the top left corner) and the profile picture (bottom left) will fail to appear and produce a 404 in the browser console. Using Firefox as my browser in this instance.

![image](https://github.com/rommapp/romm/assets/6272557/1e3d7fd5-d8ef-4def-b78c-810c4bec504b)

**Comment by gantoine** [comment]
This should be fixed in the next release (3.3.0)!
