### ISSUE TITLE
[Bug] Websocket connection failure

### ISSUE THREAD

**Issue by prettydiff** [rommapp/romm#946]
**RomM version**
3.2.0

**Describe the bug**
The browser is reporting WebSocket connection failures during scanning.
* Firefox: `Firefox can’t establish a connection to the server at ws://games.x/ws/socket.io/?EIO=4&transport=websocket.`
* Chrome: `index.ec7ff87d.js:60 WebSocket connection to 'ws://games.x/ws/socket.io/?EIO=4&transport=websocket' failed: `

**To Reproduce**
1. Conduct a library scan
2. Open the developer tools of your browser to the console tab

**Expected behavior**
WebSocket does not fail to connect.

**User**
 - OS: Windows 10

**Server**
- OS: Docker on Open Media Vault (Debian)

**Network**
- Home network: 192.168.x.x/24

**Additional context**
I cannot tell if my scans run super long without finding new content because my library is massive or because of this defect.

**Comment by gantoine** [comment]
Can you post the container logs? And are you running romm behind a reverse-proxy like caddy or npm?

**Comment by update-freak** [comment]
I had also this issue.
Scan the library with https://romm.exampleurl.net -> did not work for me
Scan the library with http://192.168.178.27:1028 -> worked for me

For the https://romm.exampleurl.net I use I reverse proxy in Synology to route from http://192.168.178.27:1028 to https://romm.exampleurl.net

**Comment by likegdz** [comment]
Hello, I have the same thing happening to me, if I use a reverse proxy for romm the scans don't work, if I access directly through the IP they do - is there a config I might be missing>

**Comment by gantoine** [comment]
@likegdz https://docs.romm.app/latest/Getting-Started/Reverse-Proxy/

**Comment by likegdz** [comment]
Thank you, that did it!

**Comment by mdPlusPlus** [comment]
I'm no expert, but usually when theres websockets involved there's stuff like this needed (see [Jellyfin](https://jellyfin.org/docs/general/post-install/networking/reverse-proxy/nginx/)):

```
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "Upgrade";
```

I can see you're including `/config/nginx/proxy.conf` in your docs, but this file isn't present for me. I'm running NGINX in a separate container. I can only assume that this file contains something along those lines above. Maybe you want to clarify that in your docs. 

(Mentioning #270 for visibility)

Edit: While on the topic of that, your docs seem to suggest inconsistent use of `client_max_body_size 0;` and `proxy_max_temp_file_size 0;`. The former only on manual NGINX configurations, the latter only when using NGINX Proxy Manager. I'm not sure if that's correct.

Edit2: This config works for me, including scans:

```
server {
    [...]

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Protocol $scheme;
    proxy_set_header X-Forwarded-Host $http_host;

    location / {
        proxy_pass http://[REDACTED]:8080;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";

        # Hide version
        server_tokens off;

        # Security headers
        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header X-XSS-Protection "1; mode=block" always;
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
        add_header Referrer-Policy "no-referrer-when-downgrade" always;
    }
}
```
