### ISSUE TITLE
[Feature] Preferred/Default Game Language

### ISSUE THREAD

**Issue by alex-taxiera** [rommapp/romm#959]
**Is your feature request related to a problem? Please describe.**
Yes. When your library has multiple copies of the same game from multiple regions (USA, JP, GER, FRA, etc.) and you have grouped them in the UI, it is a pain to select the language on each game. It seems random which version is populated by default.

**Describe the solution you'd like**
A user setting to select "preferred" or default language would be excellent. If you want your games in English, selecting English should force the game selector to an English version of the game. If there is no English version it could be random (or the setting could be a list and select by priority).

**Describe alternatives you've considered**
Ungrouping is the only way I think you can easily get around this now, but it's even worse with the library so bloated.

**Comment by gantoine** [comment]
This will be available in the next release!
