### ISSUE TITLE
[Bug] Custom Covers Not Saved

### ISSUE THREAD

**Issue by jcsomerville** [rommapp/romm#961]
**RomM version**
3.3.0-beta.2

**Describe the bug**
Uploading custom covers does work for a little while but eventually are lost. 

**To Reproduce**
1. Upload custom cover game without cover.
2. Enjoy the cover
3. After some time of not using RomM I have to refresh to get my platform icons to reappear and I think something with the refresh/caching is causing issues with artwork to disappear.

**Expected behavior**
Custom cover art to stay where you uploaded it.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 TLS
 - Browser Firefox, Brave

**Smartphone (please complete the following information):**
 - Device: Galaxy s23
 - OS: Android
 - Browser: Brave, Chrome

**Comment by gantoine** [comment]
@zurdi15 added cache busting to cover images in the recent PR, should be available in the next beta release
