### ISSUE TITLE
[Feature] Group games without metadata match as siblings

### ISSUE THREAD

**Issue by 4lexKidd** [rommapp/romm#966]
I noticed that when a game has different language versions and there is no entry in neither igdb or moby those games remain as single tiles on the platform screen.

It would be nice to have an additional multi-selection tool to mark the current selected games as siblings (if the do not have metadata and would be grouped by the sibling logic).
If new metadata for that game is brought in by a later scan, these manual sibling connections should be canceled and replaced by the existing sibling logic.

Grouping games to collection (which seams to be wip currently) could be a nice workaround but not as clean as a manual sibling. Also i think grouping to collections would not solve the multiple tiles on the screen problem (or extract the tiles to another list-view depending on how it is implemented).

**Comment by gantoine** [comment]
The problem with this approach is that if there was no metadata match, then the titles wouldn't be unique enough to distinguish them from other non-matched games in order to merge them in the UI. And marking this manually as siblings is just as much work as searching IGDB/Mobygames for metadata.
