### ISSUE TITLE
[Feature] More fine-grained control over searches

### ISSUE THREAD

**Issue by SenilePenguin** [rommapp/romm#971]
**Is your feature request related to a problem? Please describe.**
When using a rom manager such as RomVault, it is very easy to get rom names which RomM has trouble searching for. In these situations, you can be left with potentially thousands of entries which will all fail to find metadata due to the names being an unexpected format. For example, these roms are all sorted by RomVault based on No-Intro DATs:

- 0001 - 3 Choume no Tama - Tama and Friends - 3 Choume Obake Panic!! (Japan).zip
- 0002 - 3-pun Yosou - Umaban Club (Japan).zip
- 0003 - 4-in-1 Fun Pak (Japan).zip
- 0004 - 4-in-1 Fun Pak (USA, Europe).zip
- 0005 - 4-in-1 Funpak - Volume II (USA, Europe).zip

Not a single one was able to be found automatically. However, I can locate a majority of them by simply stripping the beginning part and anything with (and including) parenthesis. This regex seems mostly accurate from my testing:
`\d{4} - (.*?) \(`

However, for something more accurate you could probably do the following: remove anything in parentheses, remove the file extensions, and remove `\d{4} - ` if it exists at the beginning, prior to submitting the name to databases for metadata lookup.

**Describe the solution you'd like**
Implement a simple option to allow us to use our own Regex filters, where the first capture group is the term to search. For the latter option, this filter should be used by default on all searches when configured. When used in conjunction with the "Unidentified Games" scan, it would allow the bulk of missing items to be scanned based on specially formatted inputs, and drastically cut down on the amount of manual searching required.

**Describe alternatives you've considered**
As an alternative to the above filter option, perhaps we could connect to a database which looks up rom names by platform and checksums to provide their plain names? I'm not sure if there is a particular database that exists for this purpose and is free to access.

**Comment by gantoine** [comment]
> As an alternative to the above filter option, perhaps we could connect to a database which looks up rom names by platform and checksums to provide their plain names?

We're already working on this behind the scenes, stay tuned!

**Comment by gantoine** [comment]
Closed as will be covered by #186
