### ISSUE TITLE
[Feature] Library Wide Filtering

### ISSUE THREAD

**Issue by Spinnich** [rommapp/romm#973]
Currently, once you select a platform within RomM you can filter your games by genre, franchise, collection, and company.

My feature request is that RomM would have this functionality across the entire RomM library. This way if a user wants to filter by the "Pokémon" collection across multiple platforms they would be able to.

**Comment by gantoine** [comment]
Filtering by platform is now available in the search window, and we're not likely going to add further filtering at this point, given that collections can already be filtered the same way as platforms.
