### ISSUE TITLE
[Question] Can files be "reasonably" replaced?

### ISSUE THREAD

**Issue by zblesk** [rommapp/romm#974]
This should probably be in the "Discussion", but for me the "New" button is removed, so I can't add there. 

When 3.0 came around, I took the opportunity to completely wipe the database, make changes and re-loaded all data. All is well. 

But I recently realized I have files both in .7z and .zip archives; and my RG35XX doesn't seem to be capable of directly running .7z files. 
It would perhaps be best to convert everything into .zip. 

My question is - how is this handled by RomM? 
If there is a whatever.7z file and I add a whatever.zip, will it recognize it's the same thing, or will it try identifying again by making calls to IGDB/Moby? 

And more importantly: if I delete all the .7z files, will a full rescan remove them from the RomM DB? I really don't want to end up with a lot of duplicate entries in RomM pointing to .7z archives that no longer exist.

**Comment by gantoine** [comment]
"Issues" are a good place for this.

> will it recognize it's the same thing, or will it try identifying again by making calls to IGDB/Moby?

Currently, it'll consider it a new game and will try refetching from IGDB/Moby.

> will a full rescan remove them from the RomM DB

Deleting all the .7z files should remove them from RomM after a **_quick scan_**; we purge entries for missing files during scan
