### ISSUE TITLE
ROMM detecting platforms (the folders) but not the ROMS (the roms inside the folders)

### ISSUE THREAD

**Issue by alexnunle** [rommapp/romm#997]
**RomM version**
3.2.0
**Describe the bug**
ROM will detect the folders and catagorize them as platforms, but it will not detect my games (the ROMs that are inside the folders)
**To Reproduce**
1. Click Library
2. Click Scan (whether it's full scan, quick scan, etc)

**Expected behavior**
Detects my roms (like Lollipop Chainsaw iso)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: UNRAID

**Comment by zurdi15** [comment]
Hi! Could you provide how you bonded your host folders to the image? The one pointing to /romm/library would be useful

**Comment by alexnunle** [comment]
> Hi! Could you provide how you bonded your host folders to the image? The one pointing to /romm/library would be useful

![image](https://github.com/user-attachments/assets/384d7b07-0ea7-4851-b58b-7428c09befb5)
this what you need?
currently away from my laptop to remote into my server but ill get my unraid docker config as soon as i can

**Comment by zurdi15** [comment]
Yeah I meant the config. You need to have a roms folder on top of the platforms folder, and bind the parent folder of that roms folder.

**Comment by alexnunle** [comment]
> Yeah I meant the config. You need to have a roms folder on top of the platforms folder, and bind the parent folder of that roms folder.

![image](https://github.com/user-attachments/assets/a9723d10-14b9-4e0a-800a-ca75a80a52e9)

here you go! it detects my platforms,
just not the ROMS. for example that ISO.

![image](https://github.com/user-attachments/assets/61c5a720-be76-42bc-a222-3e53968964eb)

![image](https://github.com/user-attachments/assets/5a9a3b75-a771-4b38-a7c7-a2d3f5824246)

**Comment by zurdi15** [comment]
So, I'm assuming that you have the following path for the PS2 for example: `mnt/user/ROMs/ps2` ? In this case you need to bind until user, or keep it like that and create a `roms` folder under ROMs. The other option is to have a `roms` folder under every platform folder. Check the README.md, the folder structure section.

**Comment by alexnunle** [comment]
okay, I tried doing roms folder under the platform xbox360 and putting the ISO in there. did not detect that game.

**Comment by zurdi15** [comment]
Hmm interesting. Could you provide the container logs when you perform a scan?

**Comment by alexnunle** [comment]
INFO:     [RomM][2024-07-13 10:36:55] · xbox360
INFO:     [RomM][2024-07-13 10:36:56]   Identified as Xbox 360 🎮
WARNING:  [RomM][2024-07-13 10:36:56]   ⚠️ No firmware found, skipping firmware scan for this platform
ERROR:    [RomM][2024-07-13 10:36:56] Roms not found for platform xbox360. Check RomM folder structure here: https://github.com/rommapp/romm?tab=readme-ov-file#folder-structure

**Comment by alexnunle** [comment]
if this matters![image](https://github.com/user-attachments/assets/0a3b3a93-36f4-4995-8bc8-fab82cd73751)

**Comment by gantoine** [comment]
Closed since solved in discord: needs to remove the `roms_folder` binding in `config.yml`
